### ISSUE TITLE
The querystring API is considered Legacy

### ISSUE THREAD

**Issue by bttger** [minio/minio-js#1010]
Just got a message from npm that the querystring API is considered legacy. The minio JS client relies on it.

```
This package has been deprecated
Author message:

The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```
https://www.npmjs.com/package/querystring

**Comment by prakashsvmx** [comment]
@bttger We will upgrade soon. Thank you

**Comment by prakashsvmx** [comment]
Duplicate of #1003

**Comment by moisesbites** [comment]
Up
