### ISSUE TITLE
Cannot upload file with size 0

### ISSUE THREAD

**Issue by powerjett** [minio/minio-js#1011]
For example, I have a file with a size of 0; When uploading, it does not terminate or report an error; You can reproduce the bug yourself; For example, create a new test.txt, do not enter any content;

**Comment by prakashsvmx** [comment]
Please add more details
MinIO Version
minio-js version


**It is working as expected**:

```js

var Minio = require('../../dist/main/minio')

var fs = require('fs')

var s3Client = new Minio.Client({
  useSSL:false,
  endPoint:"localhost",
  port:9000,
  accessKey:"minio",
  secretKey:"minio123"
})

// use if required to test
var metaData = {
  'Content-Type': 'application/octet-stream',
  'X-Amz-Meta-Testing': 1234,
  'example': 5678
}

// Put a file in bucket my-bucketname.
const readableStream = fs.createReadStream("./no-content-file.txt", 'utf8')

s3Client.putObject('test-bucket', 'zero-byte-object.txt', readableStream, {}, function(e) {
  if (e) {
    return console.log(e)
  }
  console.log("Success")
})

```

Verify it with `mc`

```
$ mc stat local/test-bucket/zero-byte-object.txt 
Name      : zero-byte-object.txt
Date      : 2022-04-04 10:22:46 IST 
Size      : 0 B    
ETag      : d41d8cd98f00b204e9800998ecf8427e 
Type      : file 
Metadata  :
  Content-Type: binary/octet-stream 

```

**Comment by powerjett** [comment]
> Please add more details MinIO Version minio-js version
> 
> **It is working as expected**:
> 
> ```js
> var Minio = require('../../dist/main/minio')
> 
> var fs = require('fs')
> 
> var s3Client = new Minio.Client({
>   useSSL:false,
>   endPoint:"localhost",
>   port:9000,
>   accessKey:"minio",
>   secretKey:"minio123"
> })
> 
> // use if required to test
> var metaData = {
>   'Content-Type': 'application/octet-stream',
>   'X-Amz-Meta-Testing': 1234,
>   'example': 5678
> }
> 
> // Put a file in bucket my-bucketname.
> const readableStream = fs.createReadStream("./no-content-file.txt", 'utf8')
> 
> s3Client.putObject('test-bucket', 'zero-byte-object.txt', readableStream, {}, function(e) {
>   if (e) {
>     return console.log(e)
>   }
>   console.log("Success")
> })
> ```
> 
> Verify it with `mc`
> 
> ```
> $ mc stat local/test-bucket/zero-byte-object.txt 
> Name      : zero-byte-object.txt
> Date      : 2022-04-04 10:22:46 IST 
> Size      : 0 B    
> ETag      : d41d8cd98f00b204e9800998ecf8427e 
> Type      : file 
> Metadata  :
>   Content-Type: binary/octet-stream 
> ```


Sorry, I made a mistake
