### ISSUE TITLE
Not compatible with node version >= 16.8

### ISSUE THREAD

**Issue by ikreymer** [minio/minio-js#1015]
With the 7.0.27 release, getting:

```
error minio@7.0.27: The engine "node" is incompatible with this module. Expected version ">8  <16.8.0". Got "17.2.0"
```

Looks like this restriction was added here: https://github.com/minio/minio-js/pull/960/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R26

Is this a typo or minio not compatible with later versions of node? I have been using 7.0.26 with no issues.

**Comment by prakashsvmx** [comment]
I will test and update

**Comment by prakashsvmx** [comment]
@ikreymer  we support only LTS Versions. Please use one of them.

**Comment by avanderpluijm** [comment]
Current node LTS version seems to be 16.14.2. https://nodejs.org/en/download/

**Comment by ikreymer** [comment]
Yes, support LTS would be sufficient for my use case as well. The initial issue occurred when I was installing the latest Node LTS, then also tried locally to get that error message.

Since LTS version will be Node 16 for a few months, perhaps it could be set to `<17` until the next LTS version becomes active? I didn't encounter any issues using 7.0.26 with the latest LTS version.
