### ISSUE TITLE
Add support for latest Node LTS version (v16.14.2)

### ISSUE THREAD

**Issue by W4G1** [minio/minio-js#1017]
Related to #1015 but has been closed.

Latest long term support version of Node is v16.14.2 (See: https://nodejs.org/en/)

**Comment by davidmehren** [comment]
Thanks for the fix in #1018!
This fixes compatibility with Node 16, but with Node 17 still produces an error on install, as the engine string says `< 17`. I'm not sure if this is intentional or should say `<= 17`, but the PR title suggests the latter.

**Comment by prakashsvmx** [comment]
I will  test and send across a PR . thank you.

**Comment by maon-fp** [comment]
Could someone please release this change it'll be helpful to have it on npm ...

**Comment by prakashsvmx** [comment]
This has been released. @maon-fp . PTAL
