### ISSUE TITLE
upgarde from minio 7.0.26 of 7.0.27 failed on node v17.9.0 

### ISSUE THREAD

**Issue by ar4hc** [minio/minio-js#1022]
Upgrade with pnpm  failed with this error:

```
$ pnpm upgrade
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your Node version is incompatible with "registry.npmjs.org/minio/7.0.27".

Expected version: >8  <16.8.0
Got: v17.9.0

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
```

latest commit of minio states that it should be compatible with node 17...?

PS: 
the lock file has:
```
  /minio/7.0.26:
    engines: {node: '>= 4'}
```

**Comment by prakashsvmx** [comment]
The PR has been merged https://github.com/minio/minio-js/pull/1020  Please wait for the release.

@ar4hc thank you

**Comment by CristianMG** [comment]
Hi, The minio package is incompatiblen for now with nestjs. This is a big problem for us, ¿It would be possible release a hotfix with this change? @prakashsvmx

**Comment by prakashsvmx** [comment]
For priority releases /fix please explore min.io/pricing

**Comment by prakashsvmx** [comment]
The release has been done. PTL.
