### ISSUE TITLE
CopySourceOptions, CopyDestinationOptions is not a constructor

### ISSUE THREAD

**Issue by ngochieu642** [minio/minio-js#1024]
## Description

**Dependencies from package-lock.json**
```txt
"minio":  "7.0.27"
"@types/minio": "7.0.13"
"typescript":  "4.6.3"
```

**minimal reproducible example**
```typescript
import {
  CopyDestinationOptions,
  CopySourceOptions,
} from 'minio';

...

const copySourceOption1 = new CopySourceOptions({
  Bucket: 'bucket1',
  Object: 'demo-bucket/1.json',
});

const destOption = new CopyDestinationOptions({
  Bucket: 'bucket1',
  Object: 'compose-bucket/demo-compose.json',
});
```

**Error**
(node:492239) UnhandledPromiseRejectionWarning: TypeError: minio_1.CopySourceOptions is not a constructor

**Comment by prakashsvmx** [comment]
Please update the import statements like in [examples](https://github.com/minio/minio-js/blob/master/examples/compose-object.js).

e.g.
` var Helpers = require("../dist/main/helpers")`

use it like:

`new Helpers.CopySourceOptions( {})`

we will try adding all module/import  builds in near future.

**Comment by ChenYu29** [comment]
> We will update the types soon.

那一版本的可以正常使用new CopySourceOptions呢？

**Comment by prakashsvmx** [comment]
7.0.26 +

**Comment by ChenYu29** [comment]
> the types have not been updated for few releases now. we will update it for the latest release. Please feel free to send a PR.

什么时候更新呢？我现在版本对应为：minio（7.0.26）和@types/minio （7.0.12），依然没有解决问题

**Comment by z-lionel** [comment]
> the types have not been updated for few releases now. we will update it for the latest release. Please feel free to send a PR.

i still have the same problem at version like this 
 "minio": "^7.0.32",
"@types/minio": "^7.0.14",
