### ISSUE TITLE
composeObject fails for S3 when versionId is empty

### ISSUE THREAD

**Issue by leehendricks** [minio/minio-js#1026]
Problem:

When using s3 without object versioning, `composeObject` fails with a Bad Request. The culprit is the resulting query string in `statObject`:

`?versionId=`

minio does't seem to have a problem with this request, but s3 balks.

Solution in `composeObject`:

```
const getStatOptions = (srcConfig) =>{
  const statOptions = {}
  if (!_.isEmpty(srcConfig.VersionID)) statOptions.versionId = srcConfig.VersionID
  return statOptions
}
```
This would be consistent with how `getHeaders` behaves in `CopySourceOptions:`

```
if (!_.isEmpty(this.VersionID)) {
  headerOptions["x-amz-copy-source"]=encodeURI(this.Bucket+"/"+this.Object)+"?versionId="+this.VersionID
}
```

Workaround:

Set CopySourceOptions.VersionID to the string `'null'`, which will result in this statObject query string:

`?versionId=null`

**Comment by prakashsvmx** [comment]
@leehendricks . Thank you for the details :+1: . I will take a look soon.
