### ISSUE TITLE
Documentation on how to use `transport` parameter

### ISSUE THREAD

**Issue by a3957273** [minio/minio-js#1031]
Is it possible to use an `httpsAgent` as a custom transport to `Minio`?  It seems as if Minio takes a transport as a string, but it isn't documented anywhere.  What does this transport represent?

Is it possible to use our own agents, e.g:

```
const client = new Minio.Client({
  ...someConfig,
   transport: new https.Agent({})
})
```

At the moment, this breaks with `request` not being defined on agent.

**Comment by prakashsvmx** [comment]
based on ` useSSL: true,`  the transport would be  `http` or `https` internally.  is there a specific requirement for something more ?
