### ISSUE TITLE
Authorization on presigned URL

### ISSUE THREAD

**Issue by OmerSabic** [minio/minio-js#1032]
I have a set of users that access my content. I want to create a separate presigned URL for each user and make sure only that user can access it (by checking their auth token inside the cookie). If they share it with someone, they would also need to share their account.

Any way of doing this or would it need to be implemented?

**Comment by prakashsvmx** [comment]
such option is not available in S3 Spec. It would not be implemented.  you could explore presigned post poilcy for list of conditions
