### ISSUE TITLE
Presigned Url missing user defined metadata feature

### ISSUE THREAD

**Issue by joaofranciscosantos** [minio/minio-js#1034]
The PostPolicy is missing user defined metadata restrictions. https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html

 To be more specific, https://github.com/minio/minio-js/blob/master/src/main/minio.js#L3586-L3651, it should have another method for custom metadata.

Lets say I want to add metadata key-value called: `{request: 'abc'}`

Just like https://github.com/minio/minio-js/blob/master/src/main/minio.js#L3607, it should be possible to do 
`this.policy.conditions.push(['eq', '$x-amz-meta-request', 'abc])`

**Comment by prakashsvmx** [comment]
@joaofranciscosantos  Will investigate and send a fix soon.
Thank you.

**Comment by joaofranciscosantos** [comment]
I'll update PR soon. I'm also adding Content-Disposition restricition in PostPolicy.

As before, confirm everything is correct
