### ISSUE TITLE
Region hardcoded in `listBuckets`

### ISSUE THREAD

**Issue by louwers** [minio/minio-js#1038]
The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'nl-ams'.

Trying to connect to Scaleway S3-compastible storage. When I specify a `region` property or leave it out, I get:

> S3Error: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'nl-ams'

See code below.

```ts
import { Client } from "minio";

const minioClient = new Client({
  endPoint: "xxx.s3.nl-ams.scw.cloud",
  port: 443,
  useSSL: true,
  accessKey: "xxx",
  secretKey: "xxx",
});

(async function run() {
  await minioClient.listBuckets();
})();
```

**Comment by louwers** [comment]
Yeah OK not super surprising, the region is hardcoded:

https://github.com/minio/minio-js/blob/master/src/main/minio.js#L654

**Comment by harshavardhana** [comment]
Its not, you need to pass the right region. We can't guess region for your deployment.

**Comment by louwers** [comment]
@harshavardhana As you can clearly see in the linked source code, it is hard coded.

When I pass in the region the behavior doesn't change.

**Comment by louwers** [comment]
```js
    this.makeRequest({method}, '', [200], 'us-east-1', true, (e, response) => {
                                                               // ^ here
```

**Comment by louwers** [comment]
Changing it to `this.region` fixes the problem.

**Comment by harshavardhana** [comment]
Yes this shouldn't be hardcoded @louwers - we will fix it.

**Comment by prakashsvmx** [comment]
We will send a fix soon for using the configured region param. Thank you @louwers
