### ISSUE TITLE
[FEATURE ]Does minio plan to support esm?

### ISSUE THREAD

**Issue by cfmj** [minio/minio-js#1042]
**Is your feature request related to a problem? Please describe.**
Does minio plan to support esm?

**Describe the solution you'd like**
 support esm

**Comment by cfmj** [comment]
Use in the browser environment

**Comment by harshavardhana** [comment]
For now no @cfmj however you can compile browser.js JS equivalent, there are some APIs that won't work are

FGetObject
FPutObject

Rest of them work.

**Comment by prakashsvmx** [comment]
@cfmj  i have a react example https://github.com/prakashsvmx/minio-js-web-browser-example
