### ISSUE TITLE
licensing question

### ISSUE THREAD

**Issue by bochen87** [minio/minio-js#1049]
If we are using the plain vanilla min.io docker image (which is AGPL 3.0) and do nothing aside from configuration and we integrate it into our app using this minio-js adapter (which is Apache 2.0) as library, are we facing any copyleft issues with our web application?

**Comment by prakashsvmx** [comment]
Any derivative product needs to comply with AGPL v3. i.e MinIO is Open source for Open source Applications. so the application code needs to be open sourced. 

https://min.io/compliance

**Comment by bochen87** [comment]
> Any derivative product needs to comply with AGPL v3. i.e MinIO is Open source for Open source Applications. so the application code needs to be open sourced.
> 
> https://min.io/compliance

ok, understood. Just out of interest: how can this JS adapter then be apache 2.0 license?

**Comment by prakashsvmx** [comment]
@bochen87 we request you to consult your organization's internal legal team on the compatible licenses. we would not be able to provide detailed legal advise on the licensing. When in doubt, it is better to obtain a commercial license  [min.io/pricing](https://min.io/pricing?ref=minio-js) to protect the organization and its customers if any,  from legal liabilities.
