### ISSUE TITLE
ENOENT Warnings

### ISSUE THREAD

**Issue by draentropia** [minio/minio-js#1050]
Hi there,

I'm trying to show my buckets in a ReactJS application. After JUST importing the minio module using `import * as minio from minio` I'd deployed the app, getting a lot of warnings. See here one example:
`WARNING in ./node_modules/minio/dist/main/xml-parsers.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/blabla/myapp/node_modules/minio/dist/main/xml-parsers.js.map' file: Error: ENOENT: no such file or directory, open '/home/blabla/myapp/node_modules/minio/dist/main/xml-parsers.js.map'`

Here it is the react and minio versions:
    "minio": "^7.0.28",
    "react": "^18.2.0",

Does anyone have an idea of how to remove them?

As extra info: My goal of using this minio dependence is to see the buckets and upload data.

Thanks in advance,
Eli

**Comment by prakashsvmx** [comment]
you could add `GENERATE_SOURCEMAP=false` in env file.
