### ISSUE TITLE
Maybe Bug: Verify if you need this module and configure a polyfill for it

### ISSUE THREAD

**Issue by guanghe1990** [minio/minio-js#1053]
**When I try to bulid my app with Angular13, I encountered a lot of mistakes：**

./node_modules/Minio/dist/main/extensions.js:8:37-54 - Error: Module not found: Error: Can't resolve 'stream' in 'C:\Users\SGH\AngularCode\OceanLims\node_modules\Minio\dist\main'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }

./node_modules/Minio/dist/main/helpers.js:47:37-54 - Error: Module not found: Error: Can't resolve 'stream' in 'C:\Users\SGH\AngularCode\OceanLims\node_modules\Minio\dist\main'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }

./node_modules/Minio/dist/main/helpers.js:86:11-24 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\SGH\AngularCode\OceanLims\node_modules\Minio\dist\main'

./node_modules/Minio/dist/main/helpers.js:88:13-28 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\SGH\AngularCode\OceanLims\node_modules\Minio\dist\main'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
**It seems Webpack5 not include polyfills so minio can't find the module it need, I have no idea how to fix the problem**

**Comment by prakashsvmx** [comment]
@guanghe1990  this is an application/project build dependency issue with **webpack >=5** as it prints above. so please resolve the dependencies accordingly.  

a sample project with react 18 and CRA 5 which had the same issue has been fixed for demo purposes with minio js sdk included.  https://github.com/prakashsvmx/minio-js-react-18-build

Please refer the node built in module poly fills and apply in the project.

**Comment by vrajeshmodi30** [comment]
> @guanghe1990 this is an application/project build dependency issue with **webpack >=5** as it prints above. so please resolve the dependencies accordingly.
> 
> a sample project with react 18 and CRA 5 which had the same issue has been fixed for demo purposes with minio js sdk included. https://github.com/prakashsvmx/minio-js-react-18-build
> 
> Please refer the node built in module poly fills and apply in the project.

What You have changed exactly in your project? can you please mention that part only/ It will be a great help

**Comment by prakashsvmx** [comment]
I also built an example with latest angular https://github.com/prakashsvmx/minio-js-angular please check out.

**Comment by vrajeshmodi30** [comment]
> I also built an example with latest angular https://github.com/prakashsvmx/minio-js-angular please check out.

But can you please tell me what exactly you have done in your react project?

**Comment by prakashsvmx** [comment]
Please take a look at 
https://github.com/prakashsvmx/minio-js-react-18-build/blob/main/config-overrides.js
and
https://github.com/prakashsvmx/minio-js-react-18-build/blob/main/package.json

these are the "project build dependency" 
@vrajeshmodi30
