### ISSUE TITLE
Missing update @types/minio

### ISSUE THREAD

**Issue by joaofranciscosantos** [minio/minio-js#1057]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9205f7999a9a2ec11cecee84b9af881f834a9bd8/types/minio/index.d.ts#L454

```typescript
setContentTypeStartsWith(prefix: string): void;
setContentDisposition(value: string): void;
setUserMetaData(value: Record<string, string>): void;
```

**Comment by joaofranciscosantos** [comment]
Any news about when it will be released?

**Comment by joaofranciscosantos** [comment]
Bump. Let me know if you would like PR for this

**Comment by prakashsvmx** [comment]
Sure. Feel free to send a PR @joaofranciscosantos.

**Comment by joaofranciscosantos** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63193

**Comment by joaofranciscosantos** [comment]
It's merged. Now just waiting on package deployment

**Comment by joaofranciscosantos** [comment]
done
