### ISSUE TITLE
Get metrics

### ISSUE THREAD

**Issue by AssafKatz3** [minio/minio-js#1059]
Hi,
Is there an option to export metrics from this library (not from the server side). We want to monitor the access of our micro service to Minio by Prometheus.
Thanks

**Comment by prakashsvmx** [comment]
You could look at prometheus for exporting metrics.
SDKs are un aware of such functionalities.

**Comment by AssafKatz3** [comment]
> You could look at prometheus for exporting metrics/visualization . also Grafana SDKs are un aware of such functionalities.

Hi,
I want to expose the metrics of calls to this library, this isn't information from Prometheus but from this project.
Thanks

**Comment by prakashsvmx** [comment]
https://github.com/minio/minio/tree/master/docs/metrics/prometheus
https://github.com/minio/minio/blob/master/docs/metrics/prometheus/list.md

**Comment by AssafKatz3** [comment]
> https://github.com/minio/minio/tree/master/docs/metrics/prometheus https://github.com/minio/minio/blob/master/docs/metrics/prometheus/list.md

Hi,
There are the metrics from the server side, I want to get the metrics from the client side (this library), i.e. how often this client read/writes to Minio.
Thanks

**Comment by prakashsvmx** [comment]
Such metrics are not available. and not sure if it will be implemented anytime in any of the sdks.
