### ISSUE TITLE
copyObject does not support setting new metadata

### ISSUE THREAD

**Issue by thomasjahoda** [minio/minio-js#1060]
I want to update the metadata of a file.
According to https://github.com/minio/minio/issues/3316 and https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html, copyObject should support setting new metadata.
I do not see any such property in the CopyConditions of the JS JDK. Could this please be added?

**Comment by prakashsvmx** [comment]
Which version of the sdk is used? @thomasjahoda 

Please have a look at:
https://github.com/minio/minio-js/blob/ac8499d93b40e78eb38e865171fbdac16ee637c7/src/main/helpers.js#L591


I will try to add an example

**Comment by phanmn** [comment]
I have to add this line to CopyDestinationOptions.getHeaders

```
headerOptions['X-Amz-Metadata-Directive'] = 'REPLACE';
```

**Comment by prakashsvmx** [comment]
Thank you for the update.

**Comment by nick4fake** [comment]
So, should we use composeObject with CopyDestinationOptions for metadata update?

**Comment by prakashsvmx** [comment]
https://github.com/minio/minio-js/blob/master/examples/copy-object.js this would be enough.

**Comment by nick4fake** [comment]
@prakashsvmx There is no field for metadata in the copyObject, or am I missing something?

BTW, composeObject also doesn't work:
![image](https://github.com/minio/minio-js/assets/1065993/b7f82203-177e-426b-8902-40ea8ae4ca2f)

Getting this error:
````
This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes
````

**Comment by nick4fake** [comment]
After checking @phanmn solution it *does* help. This ticket should be reopened, as it requires changes to the minio-js source code. Currently this works for me:
````typescript
const copy = new CopyDestinationOptions({
  Bucket: this.configStorage.bucket,
  Object: key,
  UserMetadata: {
    ...meta,
    'content-size': size,
  },
});
const oldFunc = copy.getHeaders;
copy.getHeaders = () => {
  const headers = oldFunc.call(copy);

  headers['X-Amz-Metadata-Directive'] = 'REPLACE';

  return headers;
};
await this.client.composeObject(
  copy,
  [new CopySourceOptions({
    Bucket: this.configStorage.bucket,
    Object: key,
  })],
);
````

**Comment by prakashsvmx** [comment]
We will recheck https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property and apply the changes as required. Thank you.
