### ISSUE TITLE
I want to confirm whether it can only work in nodejs and JS cannot run?

### ISSUE THREAD

**Issue by chenny** [minio/minio-js#1063]
I want to confirm whether it can only work in nodejs and JS cannot run?
env 
js + vue
npm minio 7.0.32
import * as minio from 'minio' 

require  require err ReferenceError: require is not defined
<img width="455" alt="image" src="https://user-images.githubusercontent.com/883329/187891401-97c2f1a5-1459-426a-b798-110746254c8e.png">

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/883329/187891772-f9a1f94a-6a49-49e4-9c87-18835d2aa3a1.png">

**Comment by prakashsvmx** [comment]
It can run on the browser too. (Not every feature is tested. Will do when there is some bandwidth)

You may have to adjust the build settings.

E.g React 
https://github.com/prakashsvmx/minio-js-web-browser-example

**Comment by chenny** [comment]
"dependencies": {
    "@jiaminghi/data-view": "^2.10.0",
    "animate.css": "^4.1.1",
    "axios": "0.26.0",
    "babel-polyfill": "^6.26.0",
    "browserify": "^17.0.0",
    "clipboard": "^2.0.10",
    "cos-js-sdk-v5": "^1.3.5",
    "default-passive-events": "^1.0.10",
    "echarts": "^5.3.2",
    "element-china-area-data": "^4.2.0",
    "element-ui": "^2.15.7",
    "eslint-plugin-html": "^6.2.0",
    "fuse.js": "^3.6.1",
    "good-storage": "^1.1.1",
    "invoice-preview": "^1.0.2",
    "js-cookie": "2.2.0",
    "minio": "^7.0.32",
    "mockjs": "1.0.1-beta3",
    "node-sass": "^7.0.1",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "screenfull": "^4.2.1",
    "v-distpicker": "^1.2.12",
    "v-viewer": "^1.6.4",
    "vue": "^2.6.14",
    "vue-image-crop-upload": "^2.5.0",
    "vue-mobile-calendar": "^3.3.0",
    "vue-print-nb": "^1.7.5",
    "vue-router": "3.0.1",
    "vue-select": "^3.18.3",
    "vue-simple-uploader": "^0.7.6",
    "vuedraggable": "^2.24.3",
    "vuex": "3.0.1",
    "watermark-plus": "^1.2.1",
    "weixin-js-sdk": "^1.6.0"
  }

**Comment by chenny** [comment]
brower mode is not work 
nodejs mode is ok

**Comment by chenny** [comment]
Can it run in the  webpack@4.16.5 ?

**Comment by prakashsvmx** [comment]
@chenny We do not have a way to certify with different module bundlers . we provide simple examples as linked above to demonstrate that it can run . so please refer the respective documentations. and i believe, one of the examples is using webpack 4.
