### ISSUE TITLE
How to get all objects with specific metadata?

### ISSUE THREAD

**Issue by DaliborTrampota** [minio/minio-js#1067]
Hi, 
I'm storing images in minio db and add expiry header to the metadata indicating when the object should be deleted. But I cant figure out how to get all objects where the expiry header is less that Date.now(). How should this be done?
Thanks

**Comment by prakashsvmx** [comment]
ListObjects api has the date so you could write a logic and filter them out. 
There are no direct built in APIs as per s3 spec. 

You could also consider implementation of external solution using bucket Notifications and querying from a db possibly.
