### ISSUE TITLE
how to use nginx proxy?

### ISSUE THREAD

**Issue by 314171441** [minio/minio-js#1068]
how to use nginx proxy?

**Comment by 314171441** [comment]
The front-end does not want to care whether the service is HTTP or HTTPS, or whether it is an IP or domain name.

I just want to use nginx as a proxy;

**Comment by prakashsvmx** [comment]
Please follow https://docs.min.io/docs/setup-nginx-proxy-with-minio.html
sdks would need just endpoint . so the nginx configuration is not in scope of this repo.
