### ISSUE TITLE
Does minio-js support MINIO_SERVER_URL?

### ISSUE THREAD

**Issue by billchen0412** [minio/minio-js#1070]
The latest minio hub page said that there is a param MINIO_SERVER_URL which could be used to generate presigned url on different domain. Does minio-js support this param?
https://hub.docker.com/r/minio/minio/

**Comment by prakashsvmx** [comment]
Please refer to 
https://min.io/docs/minio/kubernetes/upstream/administration/minio-console.html#configuration
https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_SERVER_URL

 for the documentation on `MINIO_SERVER_URL` 
 
 for the sdk, please use the api endpoint url
