### ISSUE TITLE
Access denied when try to open Object URL

### ISSUE THREAD

**Issue by ivankikic** [minio/minio-js#1073]
I created minio.Client, took all objects, wrote them down and then when I try to access one of these links which are supposed to be urls from images that are on minio I get Access Denied.

I made links like this: var publicUrl = mc.protocol + "//" + mc.host + ":" +mc.port + "/" +   "test1" +   "/" +   obj.name;

And I get valid links of images that I have there, and when I put that link in my browser I don't get image, just Access denied

I saw on some example that I should just take one of those links and put them for example in img src but I don't get the image back

**Comment by prakashsvmx** [comment]
Please set anonymous policy for the bucket to make it public then access it like <host>/<bucket>/<object>

https://min.io/docs/minio/linux/reference/minio-mc/mc-anonymous-set.html#set-anonymous-policy-for-bucket

**Comment by ivankikic** [comment]
Is it possible to have private like this is now, but allows me somehow to show that image with minioClient on my React app? Or it must be anonymous public?

**Comment by prakashsvmx** [comment]
You could check presigned url , which the only alternative.

**Comment by ivankikic** [comment]
can I get it chunk by chunk with getObject and then just convert it into image?

**Comment by prakashsvmx** [comment]
No you can use the url retrieved via presignedget as IMG src 

Get the presumed url:
https://github.com/prakashsvmx/minio-js-web-browser-example/blob/0a477a635a92a262b4608de1ddc5839bf2332ad7/src/ListObjects.js#L46

E.g using as a link.
https://github.com/prakashsvmx/minio-js-web-browser-example/blob/0a477a635a92a262b4608de1ddc5839bf2332ad7/src/ListObjects.js#L201
