### ISSUE TITLE
 The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by z-lionel** [minio/minio-js#1075]
composeObject function throw the error , how to fixed it?
```
 this.minioClient.composeObject(destOption, sourceList).then(res => {
        console.log(222, res)
      }).catch(err => {
        console.log('err', err)
 The request signature we calculated does not match the signature you provided. Check your key and signing method.
      })
```

**Comment by prakashsvmx** [comment]
Please refer to the example in:https://github.com/minio/minio-js/blob/master/examples/compose-object-test-example.js

are you running against minio server?

Please share  more details 

please run `mc admin trace <alias>`  
or `this.minioclient.traceOn()` - share the output.

please check if there is a proxy if any.

**Comment by z-lionel** [comment]
> Please refer to the example in:https://github.com/minio/minio-js/blob/master/examples/compose-object-test-example.js
> 
> are you running against minio server?
> 
> Please share more details
> 
> please run `mc admin trace <alias>` or `this.minioclient.traceOn()` - share the output.
> 
> please check if there is a proxy if any.


I refer to the example in: https://github.com/minio/minio-js/blob/master/examples/compose-object.js
Split the video into 5m and upload it
  ```
async uploadFile(fileName: string, file: Buffer, type: string) {
    if (!(await this.isExistsBucket(this.bucketName))) {
      await this.createBucket();
    }
    const metaData = {
      'Content-Type': type,
    };
    let partObjNameList = []

    try {
      await this.minioClient.putObject(
        this.bucketName,
        fileName,
        file,
        file.length,
        metaData,
      );
      return await this.minioClient.presignedGetObject(this.bucketName, fileName);
    } catch (e) {
      throw new BadRequestException(e.message);
    }
  }

```

then i want to merge these video slices on minio

```
 async listObjects(prefix: string, recursive?: boolean) {
    const res = await this.minioClient.listObjects(this.bucketName, prefix, recursive)
    const sourceList = [] as CopySourceOptions[]
    let destOption = {} as CopyDestinationOptions
    res.on('data', (item) => {
      sourceList.push(new Helpers.CopySourceOptions({
        Bucket: this.bucketName,
        Object: item.name,
      }))
    })

    res.on('end', async () => {
      destOption = new Helpers.CopyDestinationOptions({
        Bucket: this.bucketName,
        Object: "mergevideo.mp4"
      })
      this.minioClient.composeObject(destOption, sourceList).then(res => {
        console.log( res)
      }).catch(err => {
        console.log('err', err)
      })
    })
    return 'ok'
  }
```

then i got the error

**Comment by z-lionel** [comment]
> Please refer to the example in:https://github.com/minio/minio-js/blob/master/examples/compose-object-test-example.js
> 
> are you running against minio server?
> 
> Please share more details
> 
> please run `mc admin trace <alias>` or `this.minioclient.traceOn()` - share the output.
> 
> please check if there is a proxy if any.

I got the Trace Results info on web, how can i fixed it?
![image](https://user-images.githubusercontent.com/37678805/199412317-90fc2e8a-b164-4f25-bfe6-464501c2e12c.png)

**Comment by prakashsvmx** [comment]
Please check the policies if any. for production or sla backed support please have a look at https://min.io/pricing.
