### ISSUE TITLE
Assume Role with Minio-js

### ISSUE THREAD

**Issue by ryansteakley** [minio/minio-js#1077]
I have seen https://github.com/minio/minio-js/pull/960 however there is no documentation on how to really use this feature that I can find?

How does a user use something like AWS assume role and create a minioclient? This goes in hand with the previous issue https://github.com/minio/minio-js/issues/841 where in the minio-go side they get the webidentitytoken etc... On minio-js side it is not clear how the js code gets this information when creating the client.

The current example 
```
var Minio = require('minio')

var s3Client = new Minio.Client({
    endPoint:  's3.amazonaws.com',
    accessKey: 'YOUR-TEMP-ACCESSKEYID',
    secretKey: 'YOUR-TEMP-SECRETACCESSKEY',
    sessionToken: 'YOUR-TEMP-SESSIONTOKEN'
})
```

doesn't seem to explain how to provide the fields that were implemeneted in #960 i.e credentialsProvider

Is there documentation or any example of IAM for Service Account in minio-js?

**Comment by prakashsvmx** [comment]
You could use example from https://github.com/minio/minio-js/blob/4fce54bd81188aaa86fe6927786877cd71c2b79b/src/test/functional/functional-tests.js#L40

**Comment by prakashsvmx** [comment]
Example is also provided in the PR.  We will update an example soon.

**Comment by prakashsvmx** [comment]
Please follow the steps  https://github.com/minio/minio/blob/master/docs/sts/assume-role.md

**Comment by ryansteakley** [comment]
From examples since none seem to use webIdentityToken it is not clear what needs to be done here? 
Do I need to pass the webIdentityToken and  the roleARN into 

```
let asRoleProvider = new AssumeRoleProvider({
    stsEndpoint: "s3.amazonaws.com",
    accessKey: 'miniojs',
    secretKey: 'miniojs123',
    webIdentityToken: '/var/secret/etc/',
    roleARN: "arn:aws:...."
})
```

For it work or will these be picked up automatically when using this AssumeRoleProvider?
