### ISSUE TITLE
Possibility to use this library with k6

### ISSUE THREAD

**Issue by jayush12** [minio/minio-js#1079]
Hi, 
I have tried this library to upload file on minio using k6, but not sure if the library is supported in k6.
Please clarify if this library can be used with k6.

**Comment by prakashsvmx** [comment]
What do you mean by k6?. 
Is it s3 compatible object storage ?
Please share links if any. We do not provide any validation for arbitrary providers as it would not be scalable.

**Comment by jayush12** [comment]
K6 is a load testing tool. We are using it to write some test cases and we are using typescript which gets converted into js file. 
[K6 website](https://k6.io/).
When I tried to use this library I start getting error related to missing timers and other modules.

**Comment by prakashsvmx** [comment]
this sdk is designed to work with nodejs environments. to use it directly on the web browser as a dependency, you could refer to https://github.com/prakashsvmx/minio-js-react-18-build for example and adjust the dependencies as per your project setup as the sdk is not fully tested in web environments
