### ISSUE TITLE
CORS Origin error when try to connect to S3 Endpoint

### ISSUE THREAD

**Issue by toninospiderman123** [minio/minio-js#1080]
Hi guys,

When i try to connect to s3 endpoint of IBM COS i get CORS error.

Access to fetch at ..... from origin .... has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

How can i solve this problem?

**Comment by prakashsvmx** [comment]
Cors needs to be enabled from server side. Please check with the server settings. it is not related to this sdk.

**Comment by prakashsvmx** [comment]
Please share more details on how this is sdk is used. 
We are able to provide compatibility support with S3 and MinIO. Please check the respective documentation of the target system

**Comment by toninospiderman123** [comment]
Hi @prakashsvmx,

At the end CDN added CORS Policy to bucket and all works fine.

The CDN Operation guy didn't know that he could add policy.

Thank you for support.

**Comment by prakashsvmx** [comment]
Happy that it is resolved.
