### ISSUE TITLE
Minio javascript SDK

### ISSUE THREAD

**Issue by lovesL** [minio/minio-js#1081]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.
![image](https://user-images.githubusercontent.com/27960630/205231867-c844814a-6ef4-48e4-8217-cbceb6256e72.png)
![image](https://user-images.githubusercontent.com/27960630/205231063-d7bbd087-dbce-4b33-8903-d8db4594ef16.png)
'transport' is empty, but I didn't change it, I don't know why. I found this problem in google's mobile emulator. Sorry, my English is not very good. Hope you can understand

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): ^7.0.32
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by prakashsvmx** [comment]
Thank you for reporting @lovesL .

The SDK is not fully tested in Web browser. the basic support has been validated.  

We will investigate this in Web browser environment.

**Comment by prakashsvmx** [comment]
@lovesL 
` var libraryComments = `(${process.platform}; ${process.arch})``  - this is available only in Node environment. We will add a compatible changes for both environments.

**Comment by prakashsvmx** [comment]
What other library/frameworks are you using ? are you using webpack >5? 
Please have a look at : 
https://github.com/prakashsvmx/minio-js-react-18-build
or if it is vite
https://github.com/prakashsvmx/minio-js-vite-react-app

**Comment by lovesL** [comment]
> What other library/frameworks are you using ? are you using webpack >5? Please have a look at : https://github.com/prakashsvmx/minio-js-react-18-build or if it is vite https://github.com/prakashsvmx/minio-js-vite-react-app

None of the above, I use umi
https://github.com/umijs/umi

**Comment by prakashsvmx** [comment]
I see that the mentioned framework  `https://github.com/umijs/umi` uses `Webpack 5` so check the build settings of the framework.   
Closing this as it is not directly related to this SDK

**Comment by lovesL** [comment]
> I see that the mentioned framework `https://github.com/umijs/umi` uses `Webpack 5` so check the build settings of the framework. Closing this as it is not directly related to this SDK
@prakashsvmx 
There are other solutions. Umi currently does not support closing webpack5
