### ISSUE TITLE
Does minio plan to support webpack5 and vite?

### ISSUE THREAD

**Issue by lovesL** [minio/minio-js#1084]

**Comment by prakashsvmx** [comment]
@lovesL 
Please find the example
https://github.com/prakashsvmx/minio-js-vite-react-app

**Comment by mmm8955405** [comment]
> @lovesL Please find the example https://github.com/prakashsvmx/minio-js-vite-react-app

I think we should reopen this issue, as the node-stdlib-browser has not been updated for a long time. Mini js still cannot be imported through the ES6 module in the vite environment
