### ISSUE TITLE
Support setting secureContext

### ISSUE THREAD

**Issue by charlieyule** [minio/minio-js#1090]
Hi, I found that the `setRequestOptions` method is not be able to set `secureContext` as it is not picked in [`setRequestOptions`](https://github.com/minio/minio-js/blob/4fce54bd81188aaa86fe6927786877cd71c2b79b/src/main/minio.js#L209).

I was hoping you would add the support for setting `secureContext`. It will bring much convenience when we already have the `secureContext` object.

**Comment by prakashsvmx** [comment]
Please feel free to send a PR @charlieyule . community contributions are more valuable.

**Comment by charlieyule** [comment]
@prakashsvmx Thanks for your attention. Pleae nevermind this issue.

I was just about to make a PR, but then I found the `reqOptions` is for `https.request` and it should be of type `https.RequestOptions` which is not supposed to have the `secureContext` attribute at all.

It was weird my IntelliCode suggested that `setRequestOptions` accepts an `AgentOptions`. I thought it's probably an issue in @types/minio.
