### ISSUE TITLE
"Failed to load pdf document" on first load

### ISSUE THREAD

**Issue by jainprabhash** [minio/minio-js#1092]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I am trying to fetch a pdf document from my minio bucket and load it in a new tab on a button click. On the first click, the new tab when trying to load pdf, shows the error, "Failed to load pdf document". But on every subsequent click it opens the pdf correctly. If I have multiple such buttons, each trying to load a new pdf, the issue occurs on the first click of every such button.

## Expected Behavior
The pdf should load on the first instance

## Current Behavior
The pdf is loading from the second click onwards

## Steps to Reproduce (for bugs)
This is what my button onClick looks:
`const openFileInNewTab = (bucketName, fileName) => {
    var file;
    mc.getObject(bucketName, fileName, function (err, dataStream) {
      if (err) {
        console.log("err", err);
      }
      dataStream.on("data", function (chunk) {
        file = new Blob([chunk], { type: "application/pdf" });
      });
      dataStream.on("end", function () {
        const fileURL = URL.createObjectURL(file);
        window.open(fileURL, "_blank");
      });
      dataStream.on("error", function (err) {
        console.log(err);
      });
    });
  };`

## Your Environment

* "minio": "^7.0.32"
* React 18
* MacOS BigSur

**Comment by prakashsvmx** [comment]
I have tried 2 approaches to download the file PDF. there is no issue observed
. it is downloaded in a single click.
As per the description,  if `chunk`s are completed it means the sdk functionality is complete, then your application code needs to be verified for any bugs.

Note: Blob conversion can case increased file sizes in sometimes. 

```javascript
//1. GET and download. less preferred
const openPreView = (path) =>{

    setLoading(true)
    let file
    let countChunks=0
    mc.getObject(bucketName, path, function(err, dataStream) {
      if (err) {
        console.log("err", err);
      }
      dataStream.on("data", function(chunk) {

        console.log(chunk)
        countChunks+=1
        file = new Blob([chunk], { type: "application/pdf" });
      });
      dataStream.on("end", function() {
        setLoading(false)
        const fileURL = URL.createObjectURL(file);
        window.open(fileURL, "_blank");
        console.log("Opening Preview", countChunks);
        URL.revokeObjectURL(fileURL)

      });
      dataStream.on("error", function(err) {
        console.log(err);
      });
    });
  }

// 2. Use presigned url for download. better
  const openPreviewWithSignedUrl = async (path) =>{
    setLoading(true)
    const signedUrl = await mc.presignedGetObject(bucketName, path)
    setLoading(false)
    window.open(signedUrl, "_blank");
  }
```
Just for demonstrating the functionality: 
The code can be found in https://github.com/prakashsvmx/minio-js-react-18-build/commit/862b48d440e829f6bb977f891a136736635b1378

**Comment by prakashsvmx** [comment]
I have also updated the exmaple with large file download ( multiple chunks ) as the above code does not handle it.

**Comment by jainprabhash** [comment]
if the file is large, then there's no way to know that the file is loading on slow internet until the stream's end callback is executed. is there a way load the pdf in data callback and keep updating it as more chunks come?

**Comment by prakashsvmx** [comment]
@jainprabhash  you could try loading using presigned url ?

**Comment by jainprabhash** [comment]
@prakashsvmx but that presigned url exposes many things that we don't want the users to see. Is there a way to tweak the example that you've given in the code to achieve the intended result?
