### ISSUE TITLE
question: with the js sdk how is the best way to purge a bucket

### ISSUE THREAD

**Issue by cstmgl** [minio/minio-js#1093]
hi all,
this is not a bug but more a question.
I was going over the sdk documentation and I'm facing a weird issue, from the UI I can see that we have no problem deleting the content of a bucket (or a folder inside a bucket). and is actually quite fast.

```https://minio-console/api/v1/buckets/my-bucket/delete-objects?all_versions=false``` in the payload I have the list of paths

Now in the sdk I tried removeBucket (requires bucket to be empty) removeObjects or removeObject.
My problem seems to be that when I have a folder for example it returns me only the "prefix" not the objectName and it seems then the delete does nothing.
I guess the only option would be to browse over the bucket with the recursive on listObjects but I was wondering if there is a better way.
Somehow I just could not find a better way. Did I miss something?

**Comment by prakashsvmx** [comment]
There is no direct API in SDKs to purge/remove   **non empty**  bucket. 
You could consider the following:
- list all objects with versions 
- `removeObjects(bucketName, objectsList[, callback])` - use this method to remove objects and versions.
- when no objects/versions left, you could call `removeBucket` 
- If object locking enabled, based on retention mode, you may have to wait/bypass for the retention time to be past to delete objects/versions.

**Comment by prakashsvmx** [comment]
You could explore `https://github.com/minio/minio-js/pull/1076` if it is a prefix
