### ISSUE TITLE
Set bucket quota

### ISSUE THREAD

**Issue by willdochnur** [minio/minio-js#1094]
Hi, i would like to set bucket quota when creating new bucket. Optionally in a seperate method call after bucket creation like `Client.setBucketQuota(bucketName: string, quota: number)`. Thanks.

**Comment by prakashsvmx** [comment]
Quota is an administrative API which is not part of se API so please have a look at (available only in golang) SDKs would not have it.
https://github.com/minio/madmin-go/blob/f82e0aa575d168a512bfac39219524a92d6fdc98/quota-commands.go#L94
