### ISSUE TITLE
Client method to create own request

### ISSUE THREAD

**Issue by willdochnur** [minio/minio-js#1095]
Recently i created another issue where i issued missing method to set bucket quota (#1094). I know it is a lot of work to provide all the features minio console is providing. So why you dont provide a simple method `Client.customRequest` which got just four (five with callback) parameters (bucketName: string, httpMethod: string, path : string, body?: string) to let developers use your lib just as for authentication purposes when there is a method missing in your implementation.

Example code to set bucket quota:
```
const minioClient = new Client({
      endPoint: "play.min.io",
      port: 9000,
      useSSL: true,
      accessKey: "minioadmin",
      secretKey: "minioadmin"
    });

await minioClient.makeBucket("myBucketName", "");

await minioClient.customRequest(
  "myBucketName",
  "PUT",
  "/v1/buckets/myBucketName/quota",
  JSON.stringify({ enabled: true, amount: 1073741824, quota_type: "hard" })
);
```

Thanks.

**Comment by prakashsvmx** [comment]
Please refer to https://github.com/minio/minio-js/issues/1094#issuecomment-1368220198
