### ISSUE TITLE
Is there a way to get file permission (ACL)

### ISSUE THREAD

**Issue by tafel** [minio/minio-js#1100]
## Expected Behavior

I have a private S3 bucket. All files are private, except a few of them, which are uploaded (`putObject` method) to the bucket with the metadata `x-amz-acl = 'public-read'`

This metadata is used by the S3 provider to manage permissions on the file.

When retrieving file stats with `statObject`, this permission information should be available. Or is there another way to know what are files permissions? 

## Current Behavior

I didn't find a way to get this information. `statObject` returns some data, but not file permissions. The `x-amz-acl` metadata is used by the S3 provider to set permission, but is unfortunately not persisted in file metadata.

## Context

I'm using an auto-resize-image API route, which fetches the high quality image, does some cropping dynamically, and returns the cropped image (highly simplified description). But if this image is a private one, it should throw an access denied error. Since the API has obviously all needed permissions to manage public AND private files, I need to find a way to retrieve permissions information per-file.

## Your Environment

* Version used (`minio --version`): 7.0.32 (npm package version)
* Server setup and configuration: Node JS 18.14.0, NPM 9.3.1
* Operating System and version (`uname -a`): Linux a958aca36f8c 5.15.0-60-generic 66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 GNU/Linux (docker image node:18.14.0-alpine3.17)

**Comment by prakashsvmx** [comment]
`https://min.io/docs/minio/linux/operations/checklists/thresholds.html#unsupported-s3-bucket-apis`

Bucket ACLs are not supported in MinIO.


Not sure if the following is what you are looking for:
```javascript

let objectName = "my-large-ac-Object.txt"
let bucketName = "test-amz-bucket"

function getMetaData() {
  s3Client.statObject(bucketName, objectName, (e, res) => {
    console.log("Res Stat.", res)
  })
}

s3Client.putObject(bucketName, objectName, uploadStream, {
  "x-amz-acl": 'public-read',// it may not be part of meta data
  "X-Amz-Meta-x-amz-acl":'public-read' // valid X-Amz-Meta-<header>
}, (e, res) => {
  console.log("Res.", res)
  getMetaData()
})
```
`putObject` Response:
```javascript 
 { 
etag: '0a9739d8f171bb3a216168a2b7376e2e', 
versionId: null 
}
```

`statObject` Response
```javascript
{
  size: 68157440,
  metaData: { 'content-type': 'binary/octet-stream', 'x-amz-acl': 'public-read' },
  lastModified: 2023-02-17T11:29:40.000Z,
  versionId: null,
  etag: '0a9739d8f171bb3a216168a2b7376e2e'
}

```

**Comment by tafel** [comment]
This alternative is working for my case. Thanks for the tip.
