### ISSUE TITLE
Cant remove large file

### ISSUE THREAD

**Issue by DaliborTrampota** [minio/minio-js#1105]
Hi, this is my code

```
async deleteMedia(request, reply) {
        let mediaID = request.params.ID
        if(mediaID.includes('.')) mediaID = mediaID.split('.')[0]
        
        try{
            await this.pg.query("DELETE FROM media WHERE code=$1", [mediaID])
            console.log('here', mediaID)
            let res = await this.minio.removeObject('images', mediaID)
            console.log(res)
            return reply.code(200).send()
        } catch(err) {
            console.log(err)
            return reply.code(404).send()
        }
    }
```

the removeObject line never returns/finishes when trying to delete a large file (189MiB). I cant even delete it from the minio console but other smaller files can be removed just fine.
What is the issue?

**Comment by kannappanr** [comment]
@DaliborTrampota What is the version of MinIO server here? Can you try running `mc support top locks ALIAS` and `mc support profile ALIAS`? Also `mc admin prometheus metrics ALIAS` and paste it here

Can you try uploading a larger object and try deleting that? Can you also paste the output of `mc admin info ALIAS`?

**Comment by kannappanr** [comment]
@DaliborTrampota Closing this issue based on the conversation in slack. Please feel free to reach out to us if you see this issue again

**Comment by Ywine** [comment]
I have encountered a problem, when calling` removeObject`, small files can be deleted directly,4M file deletion will give an error。
`error = 'S3Error: A timeout occurred while trying to lock a resource, please reduce your request rate\n'`
![1729851680386](https://github.com/user-attachments/assets/83da33ca-4b61-4407-b22a-9542372b22bc)

![image](https://github.com/user-attachments/assets/eede0e08-0feb-4b79-bba2-bc713e7e4182)

**Comment by prakashsvmx** [comment]
Please check the server logs. @Ywine . Also please use latest version of minio
