### ISSUE TITLE
removeObjects() does not throw an exception if access is denied

### ISSUE THREAD

**Issue by akhayyat** [minio/minio-js#1110]
`removeObject()` (singular) correctly throws an exception if the user does not have permission to remove the object:

     S3Error: Access Denied

`removeObjects()` (plural), under the same circumstances, go through as if the files are removed, and does not throw any exceptions. If the user has the required permissions, the objects are removed correctly. If not, an exception should be thrown, but it is not.

**Comment by prakashsvmx** [comment]
@akhayyat , thank you. I will send a PR to return the response similar to other sdks.
