### ISSUE TITLE
`removeObjects` doesn't work as expected

### ISSUE THREAD

**Issue by trim21** [minio/minio-js#1129]
is doesn't clear all input entries, instead, it only remove first `maxEntries` entries.

It's expected be delete object in chunk, instead it only delete `entries.slice(0, maxEntries)`

**Comment by prakashsvmx** [comment]
Please run mc admin trace <alias> and check the request and response. 

Please share the example to replicate the issue.

**Comment by prakashsvmx** [comment]
Thank you @trim21 . i have sent a fix in #1131

**Comment by trim21** [comment]
Originally I was planning on fix this on migration…
