### ISSUE TITLE
`accessKey` and `secretKey` were deprecated. Should the JS client also change?

### ISSUE THREAD

**Issue by ChrisVilches** [minio/minio-js#1144]
According to this page (https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_ACCESS_KEY) the variables `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` were deprecated, so I wonder if the JS client should also be changed to have `rootUser` and `rootPassword` instead (which are the new environment variable names to use).

My current setup looks like this (TypeScript):

```ts
    client = new Minio.Client({
      endPoint: process.env.MINIO_ENDPOINT as string,
      port: Number(process.env.MINIO_PORT as string),
      useSSL: process.env.MINIO_SSL === '1',
      accessKey: process.env.MINIO_ROOT_USER as string,
      secretKey: process.env.MINIO_ROOT_PASSWORD as string
    })
```

This part would need to be changed:

```ts
      accessKey: process.env.MINIO_ROOT_USER as string,
      secretKey: process.env.MINIO_ROOT_PASSWORD as string
```

And as a side note, this is the current definition for the constructor params:

```ts
export interface ClientOptions {
    endPoint: string;
    accessKey: string;
    secretKey: string;
    useSSL?: boolean | undefined;
    port?: number | undefined;
    region?: Region | undefined;
    transport?: any;
    sessionToken?: string | undefined;
    partSize?: number | undefined;
    pathStyle?: boolean | undefined;
}
```

**Comment by aldy505** [comment]
Those `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` only affect the server setup, not the client side ones. Even more, AWS' S3 still provides authentication via `accessKey` and `secretKey` (with optional `token` field). I think this is not an issue.

**Comment by prakashsvmx** [comment]
It is a naming and does not impact the functionality . In general we can call it accessKey and secretKey so it looks fine as is.
