### ISSUE TITLE
`listBuckets` ignores Client constructor `region`

### ISSUE THREAD

**Issue by 6XGate** [minio/minio-js#1148]
`listBuckets` is always called with `us-east-1` region.

Stepping through the code attempting debug it shows it always calls makeRequest with the `DEFAULT_REGION` and `makeRequestStream` checks that is passed in and immediately takes the value from `DEFAULT_REGION` due to the `if (region) return _makeRequest(null, region)` right before `this.getBucketRegion(options.bucketName, _makeRequest)`.

Extra info:
MinIO VERSION: **2023-03-22T06:36:24Z**
Node version: **v16.20.0**
Yarn version: **1.22.19**
minio-js version: **7.1.0**

**Comment by aldy505** [comment]
The problem's on this specific line of code: https://github.com/minio/minio-js/blob/02298938b7ee3c350a4c1d254c6ece89c7145005/src/minio.js#L775

We shouldn't use `DEFAULT_REGION` as the region parameter. Should be using `this.region` or an empty string.

**Comment by bliberi** [comment]
Updates on this issue? Is it possible to merge the PR?
