### ISSUE TITLE
Allow setting of rejectUnauthorized in isolation

### ISSUE THREAD

**Issue by jrm86** [minio/minio-js#1162]
The `setRequestOptions` function currently takes a parameter named `options` which is defined as `Pick<https.RequestOptions, (typeof requestOptionProperties)[number]>`. This means that items listed in `requestOptionProperties` are ALL required to exist in the `options` parameter. However, I would like to only set one or a few options, such as setting `rejectUnauthorized` to `false` in a testing environment.

This could be resolved by changing the type to `Partial<Pick<https.RequestOptions, (typeof requestOptionProperties)[number]>>`. This also creates the same `Pick` type, but with each of the contained items as optional instead of required, to be used as needed.

https://github.com/minio/minio-js/blob/23ad6e27122069574214442a7e8399a32c35a769/src/internal/client.ts#LL250C35-L250C35

**Comment by jrm86** [comment]
The difference would be:

this
```
client.setRequestOptions({
            rejectUnauthorized: rejectUnauth,
        });
```
instead of
```
client.setRequestOptions({
            rejectUnauthorized: rejectUnauth,
            agent: undefined,
            ca: undefined,
            cert: undefined,
            ciphers: undefined,
            clientCertEngine: undefined,
            crl: undefined,
            dhparam: undefined,
            ecdhCurve: undefined,
            family: undefined,
            honorCipherOrder: undefined,
            key: undefined,
            passphrase: undefined,
            pfx: undefined,
            secureOptions: undefined,
            secureProtocol: undefined,
            servername: undefined,
            sessionIdContext: undefined,
        });
```

**Comment by trim21** [comment]
> The difference would be:
> 
> this
> 
> ```
> client.setRequestOptions({ rejectUnauthorized: rejectUnauth });
> ```
> 
> instead of
> 
> ```
> client.setRequestOptions({
>     rejectUnauthorized: rejectUnauth,
>     agent: undefined,
>     ca: undefined,
>     cert: undefined,
>     ciphers: undefined,
>     clientCertEngine: undefined,
>     crl: undefined,
>     dhparam: undefined,
>     ecdhCurve: undefined,
>     family: undefined,
>     honorCipherOrder: undefined,
>     key: undefined,
>     passphrase: undefined,
>     pfx: undefined,
>     secureOptions: undefined,
>     secureProtocol: undefined,
>     servername: undefined,
>     sessionIdContext: undefined,
> });
> ```

first argument is already supported， why youneed the second argument？

**Comment by trim21** [comment]
all fields of `https.RequestOptions` is optional already, `https.RequestOptions` is same with `Partial<https.RequestOptions>`, so `Pick<https.RequestOptions, "...">` is same as `Partial<Pick<https.RequestOptions, "...">>`

**Comment by trim21** [comment]
what's your typescript version?

**Comment by jrm86** [comment]
TypeScript version 4.9.5 (this is a temporary requirement until other things are ready for v5). And yes, I saw that the `https.RequestOptions` are indeed optional.

This is the text of the error when I try to use `client.setRequestOptions({ rejectUnauthorized: rejectUnauth });`:

```
Argument of type '{ rejectUnauthorized: boolean; }' is not assignable to parameter of type 'Pick<https.RequestOptions, "agent" | "ca" | "cert" | "ciphers" | "clientCertEngine" | "crl" | "dhparam" | "ecdhCurve" | "family" | "honorCipherOrder" | "key" | "passphrase" | "pfx" | "rejectUnauthorized" | "secureOptions" | "secureProtocol" | "servername" | "sessionIdContext">'.
  Type '{ rejectUnauthorized: boolean; }' is missing the following properties from type 'Pick<https.RequestOptions, "agent" | "ca" | "cert" | "ciphers" | "clientCertEngine" | "crl" | "dhparam" | "ecdhCurve" | "family" | "honorCipherOrder" | "key" | "passphrase" | "pfx" | "rejectUnauthorized" | "secureOptions" | "secureProtocol" | "servername" | "sessionIdContext">': agent, ca, cert, ciphers, and 13 more.
  ```

**Comment by trim21** [comment]
what's your `@types/node` version?

**Comment by jrm86** [comment]
Was at `@types/node` 10; updating to 20 resolved the issue. This can be closed.

**Comment by trim21** [comment]
you should keep it synced with your node version, node10 is already dropped by minio
