### ISSUE TITLE
[Bug] Property 'setRequestOptions' does not exist on type 'Client'

### ISSUE THREAD

**Issue by b0939261761** [minio/minio-js#1163]
Hi,
node.js - 20.1.
minio - 7.1.1
typescript  - 4.9.5

When I updated minio from version 7.0.32 to version 7.1.1, I got an error.

```bash
 error TS2339: Property 'setRequestOptions' does not exist on type 'Client'.
```

```ts
this.client.setRequestOptions({ rejectUnauthorized: false });
```

In the file minio.d.c there is no signature of the function `setRequestOptions(options: RequestOptions): void;`.

The @types/minio package has this signature of the function `setRequestOptions`
[https://github.com/DefinitelyTyped/DefinitelyTyped/blob/73fd4e988115d6a2d5fbf14343c8a28985eab4ad/types/minio/index.d.ts#L651](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/73fd4e988115d6a2d5fbf14343c8a28985eab4ad/types/minio/index.d.ts#L651)

Thanks.

**Comment by trim21** [comment]
already fixed in master branch

**Comment by b0939261761** [comment]
Hi, In the master branch, I did not find the signature of the `setRequestOptions` function.

[https://github.com/minio/minio-js/blob/master/src/minio.d.ts](https://github.com/minio/minio-js/blob/master/src/minio.d.ts)

**Comment by trim21** [comment]
> Hi, In the master branch, I did not find the signature of the `setRequestOptions` function.
> 
> https://github.com/minio/minio-js/blob/master/src/minio.d.ts

Yes, it's written in typescript so we don't need it in d.ts anymore

https://github.com/minio/minio-js/blob/23ad6e27122069574214442a7e8399a32c35a769/src/internal/client.ts#L250

**Comment by trim21** [comment]
you may still need types/minio before next version is released…

**Comment by prakashsvmx** [comment]
The 7.1.1 is to ensure the workflow is tested end to end. so you could wait for the upcoming releases. @b0939261761

**Comment by trim21** [comment]
yes, fixes is not released.
