### ISSUE TITLE
TS2691 when compiling type reference from version 7.1.1

### ISSUE THREAD

**Issue by scarrico-divergent** [minio/minio-js#1166]
I have a library that uses type references from `minio` ie
```ts
import type { Client as MinioClient, ItemBucketMetadata, ResultCallback, UploadedObjectInfo } from "minio";
```

since recent upgrade to the latest release, it has started producing 

```sh
node_modules/minio/dist/main/minio.d.ts:20:29 - error TS2691: An import path cannot end with a '.ts' extension. Consider importing './internal/s3-endpoints' instead.

20 export type { Region } from './internal/s3-endpoints.ts'
```

would it be possible to remove the `.ts` extension from the definition file?

**Comment by LiangliangSui** [comment]
I also encountered the same problem, is there a solution?

**Comment by aldy505** [comment]
@LiangliangSui wait for https://github.com/minio/minio-js/pull/1167
