### ISSUE TITLE
Add error classes in export of the package

### ISSUE THREAD

**Issue by OSA413** [minio/minio-js#1171]
Hello, I'd like to use the error classes to handle every error properly. I'm currently importing errors directly from "minio/dist/main/errors" which is not ideal. Can you please make that it would be possible to import error classes from "minio/errors"?

**Comment by prakashsvmx** [comment]
The refactoring to use typescript is in progress.  We will consider this  along with export of utils as well.

**Comment by trim21** [comment]
we can add subpath export in package.json

**Comment by OSA413** [comment]
That would be great

**Comment by aldy505** [comment]
> we can add subpath export in package.json

@trim21 Hey, did we do this already?

**Comment by trim21** [comment]
> > we can add subpath export in package.json
> 
> @trim21 Hey, did we do this already?

no

**Comment by aldy505** [comment]
> > > we can add subpath export in package.json
> > 
> > 
> > @trim21 Hey, did we do this already?
> 
> no

OK, I'm gonna go back working on this SDK next week. I'll tackle this one first.
