### ISSUE TITLE
CommonPrefixes element repeated in ListV2 output

### ISSUE THREAD

**Issue by chromakode** [minio/minio-js#1176]
Testing out minio (docker tag `RELEASE.2023-06-23T20-26-00Z` via `quay.io/minio/minio`, single node single drive), I noticed my [S3 library](https://github.com/bradenmacdonald/deno-s3-lite-client) was not returning all results when listing objects with common prefixes. Digging into the library, I found that it's receiving multiple `<CommonPrefixes>` tags.

Example output from `GET /bucket/?list-type=2&prefix=&delimiter=%2F&max-keys=1000`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>bucket</Name><Prefix></Prefix><KeyCount>2</KeyCount><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><CommonPrefixes><Prefix>GjdfWPLmdH/</Prefix></CommonPrefixes><CommonPrefixes><Prefix>KfCfPHq7Wh/</Prefix></CommonPrefixes></ListBucketResult>
```

I took a quick peek at the source, and it's puzzling to me how this is happening, since [`ListVersionsResponse`](https://github.com/minio/minio/blob/fcbed41cc36bcc04fe3701f6d540545059e005fa/cmd/api-response.go#L93) only has a single slice of prefixes.

The [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_ResponseSyntax) imply there will only be one `CommonPrefixes` tag, so if this is reproducible behavior, it'll probably break other libs.

**Comment by prakashsvmx** [comment]
Could you please check 
https://github.com/minio/minio-js/blob/d8a6f821b8a7d90f1285f19d664f9a4439a51036/src/xml-parsers.js#L351

**Comment by harshavardhana** [comment]
@chromakode that's just an example AWS S3 sends multiple "CommonPrefixes" if there are multiple common prefixes.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>46034545df6s-tf-state</Name>
  <Prefix>minio-plural-sh/</Prefix>
  <KeyCount>4</KeyCount>
  <MaxKeys>1000</MaxKeys>
  <Delimiter>/</Delimiter>
  <EncodingType>url</EncodingType>
  <IsTruncated>false</IsTruncated>
  <CommonPrefixes>
    <Prefix>minio-plural-sh/bootstrap/</Prefix>
  </CommonPrefixes>
  <CommonPrefixes>
    <Prefix>minio-plural-sh/etcd/</Prefix>
  </CommonPrefixes>
  <CommonPrefixes>
    <Prefix>minio-plural-sh/ingress-nginx/</Prefix>
  </CommonPrefixes>
  <CommonPrefixes>
    <Prefix>minio-plural-sh/minio/</Prefix>
  </CommonPrefixes>
</ListBucketResult>
```

Any library must handle this properly

```
aws s3api list-objects-v2 --delimiter / --bucket 46034545df6s-tf-state --prefix minio-plural-sh/ --profile s3

{
    "CommonPrefixes": [
        {
            "Prefix": "minio-plural-sh/bootstrap/"
        },
        {
            "Prefix": "minio-plural-sh/etcd/"
        },
        {
            "Prefix": "minio-plural-sh/ingress-nginx/"
        },
        {
            "Prefix": "minio-plural-sh/minio/"
        }
    ]
}
```

**Comment by harshavardhana** [comment]
> I took a quick peek at the source, and it's puzzling to me how this is happening, since [`ListVersionsResponse`](https://github.com/minio/minio/blob/fcbed41cc36bcc04fe3701f6d540545059e005fa/cmd/api-response.go#L93) only has a single slice of prefixes.

Looks like you are not understanding how XML marshals a slice. 

```
type List struct {
   XMLName  xml.Name `xml:"http://s3.amazonaws.com/doc/2006-03-01/ List"`
   AA []B
}
```

Always writes like
```xml
<?xml version="1.0" encoding="UTF-8"?>
<List xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <AA>
    <B>value1</B>
  </AA>
  <AA>
    <B>value2</B>
  </AA>
</List>
```


There is no other way to represent a slice in XML otherwise, it isn't like JSON that can write 

```json
"aa": ["value1", "value2", ...]
```

**Comment by chromakode** [comment]
Aha! Thank you for the quick and thorough explanation :grin: 

I had the same misunderstanding as [this xml.Marshal topic](https://stackoverflow.com/a/64502236): that there should be multiple `<Prefix>` nodes per single `<CommonPrefixes>`, like that marshal tag example. Sorry for not checking S3's output before filing an issue. The S3 docs line "CommonPrefixes contains all (if there are any) keys between..." seemed unambiguous to me.

Also, whoops, I see I also filed this to the wrong repo. In any case, thank you both for the kind clarification, much appreciated!
