### ISSUE TITLE
RollupError: "default" is not exported by "node_modules/minio/dist/esm/minio.mjs"

### ISSUE THREAD

**Issue by 53845714nF** [minio/minio-js#1182]
I get the Error:
`RollupError: "default" is not exported by "node_modules/minio/dist/esm/minio.mjs"`

This fails by: `import Minio from 'minio';`

I use it in a React Component, coded in Typescript und build wit vite.

Does anyone know how I can fix the error?

**Comment by trim21** [comment]
`import * as Minio from 'minio';`

**Comment by 53845714nF** [comment]
Thanks a lot.

**Comment by liulipeng721** [comment]
"@umijs/max": "^4.0.67",
react 18
typescript 
webpack

When I use 
const Minio = require('minio');
![b04ef16217c2cba98bd3f0f5914cac2](https://github.com/user-attachments/assets/c0e8f698-f82e-41d4-b229-e937e5b15ce9)




But when I 
import * as Minio from 'minio';

Failed to compile
Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

![1725355521670](https://github.com/user-attachments/assets/89d4b7c1-0bd5-42de-9826-8df6a2d328e5)

**Comment by liulipeng721** [comment]
"minio": "^8.0.1",
