### ISSUE TITLE
incorrect typings for listObjects

### ISSUE THREAD

**Issue by rkreienbuehl** [minio/minio-js#1197]
According to the docs, there should be a possibility to set `listOpts`. In the TypeScript typings the optional `listOpts` is missing.
minio-js version: `7.1.1`

**Comment by prakashsvmx** [comment]
the typescript migration is in progress. `7.1.1` is not a complete typescript migration . it was to help the contributors use the ts workflow and migrate different parts . 

please wait for the complete migration and next release

**Comment by trim21** [comment]
> the typescript migration is in progress. `7.1.1` is not a complete typescript migration . it was to help the contributors use the ts workflow and migrate different parts .
> 
> please wait for the complete migration and next release

I think we can still make a new release before the migration completed

**Comment by trim21** [comment]
Can you try latest version?
