### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:9000  works in debug mode, but fails on production

### ISSUE THREAD

**Issue by Mahdibenamor** [minio/minio-js#1201]
Same details putten here : 

https://github.com/minio/minio-js/issues/994

the problem is that in debug mode,  it works fine, but when i got to docker it fails. 
it's a sticking point for us, and people get angry here.

docker compose config: 

minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ******
      MINIO_ROOT_PASSWORD: *******
    volumes:
      - storage-minio:/data
    command: server --console-address ":9001" /data
    restart: always
    
    
    
   ts code : 
   
    private minioClient = new Minio.Client({
    endPoint: "localhost",
    port: 9000,
    useSSL: false,
    accessKey: "*********",
    secretKey: "**********",
  });

**Comment by prakashsvmx** [comment]
mc admin trace <alias>
Or 
Enable. Trace at the SDK level. 

Not sure `localhost` works with docker . 
 It is networking issue. Not a SDK issue.
