### ISSUE TITLE
import callbackify

### ISSUE THREAD

**Issue by ushastikchb1** [minio/minio-js#1238]
Hello.
I have some projects which use your package. I overrode promisify method to automatically pass a bucket and a region to methods where they are needed.
You added [callbackify](https://github.com/minio/minio-js/blob/master/src/internal/callbackify.js) method in one of the latest versions and wrapped [to some methods](https://github.com/minio/minio-js/blob/master/src/minio.js#L2270-L2285). If I try to update a package version, my code stops working. Could you allow to import [`"./dist/main/internal/*"`](https://github.com/minio/minio-js/blob/master/package.json#L26)? Or may be could you move [callbackify.js](https://github.com/minio/minio-js/blob/master/src/internal/callbackify.js) to another directory?

Thank you.

**Comment by prakashsvmx** [comment]
Please note, any changes outside of this repo/package needs to be managed on your own.   we would not be able to accommodate project specific changes in this repo.

**Comment by ushastikchb1** [comment]
Thank you
