### ISSUE TITLE
Cannot find type definition file for 'minio'.

### ISSUE THREAD

**Issue by MaximDomanov** [minio/minio-js#1257]
When start project in nestjs in console appears message - 
Cannot find type definition file for 'minio'.
The file is in the program because:
Entry point for implicit type library 'minio'

My tsconfig
```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "src",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "esModuleInterop": true,
    "noFallthroughCasesInSwitch": false
  },
  "exclude": ["node_modules", "dist"]
}

```

**Comment by IvanLi-CN** [comment]
<img width="810" alt="image" src="https://github.com/minio/minio-js/assets/30215105/1d02e18d-f947-4504-8258-562569f23d4d">

I tried adding this line and it doesn't report an error when building with tsc.

**Comment by wulff007** [comment]
Hi, I fixed it 
`npm remove minio`
`npm install minio`
