### ISSUE TITLE
isValidBucketName function verifies that the Bucket has errors

### ISSUE THREAD

**Issue by Elssia** [minio/minio-js#1260]
My parameter buctName seems to match alphanumeric start and alphanumeric end but the regex doesn't work;The parameter value I pass is the string minioData
![image](https://github.com/minio/minio-js/assets/74245693/977ef238-9060-43ff-8a5f-da6c32449510)

![image](https://github.com/minio/minio-js/assets/74245693/cba15d58-28b4-4059-baa1-be75025b0f86)

**Comment by harshavardhana** [comment]
You have D capital that is not an allowed bucket names.

Bucket names are lower case

**Comment by Elssia** [comment]
Thank you for your reminder. However, I remember uppercase names used to be legal. That bucket was created by me in the web management backend before. It's possible that uppercase letters don't comply with regulations now. Thank you again

**Comment by harshavardhana** [comment]
> Thank you for your reminder. However, I remember uppercase names used to be legal. That bucket was created by me in the web management backend before. It's possible that uppercase letters don't comply with regulations now. Thank you again

That was years ago. Not anymore
