### ISSUE TITLE
Cannot use Minio in Deno

### ISSUE THREAD

**Issue by riderx** [minio/minio-js#1261]
IT's now allowed to use in Deno:
```
import { Client } from 'npm:minio'

function initR2(c: Context) {
  const accountid = '*****'
  const access_key_id = '*****'
  const access_key_secret = '*****'
  const params = {
    endPoint: `${accountid}.r2.cloudflarestorage.com`,
    region: 'us-east-1',
    useSSL: true,
    accessKey: access_key_id,
    secretKey: access_key_secret,
  }

  console.log('R2 params', params)
  const client = new Client(params)
  console.log('R2 client', client)
  return client
}
initR2()
```
And then i get error like that:
```
e Error: unreachable
    at arch (ext:deno_node/_process/process.ts:16:11)
    at get arch [as arch] (node:process:275:14)
    at new TypedClient (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/minio/7.1.3/dist/esm/internal/client.mjs:98:62)
    at new Client (file:///tmp/sb-compile-edge-runtime/node_modules/localhost/minio/7.1.3/dist/esm/minio.mjs:44:8)
```

**Comment by aldy505** [comment]
The SDK requires some Node.js dependencies. See here

https://github.com/minio/minio-js/blob/6b9845d3c7fa5f5013f3fa1058f85a9480dcd434/src/internal/client.ts#L1-L6

Perhaps Deno support will be available sooner or later. I don't have any idea about that.

**Comment by riderx** [comment]
Deno does support node deps since a year :)
https://docs.deno.com/runtime/manual/node/compatibility
It seems the problem is not them, maybe one of the other npm deps.
Maybe fs is problematic also.

can I try to work on it ?

**Comment by aldy505** [comment]
Sure go ahead. But the typescript rewrite has been going really slow right now.

**Comment by riderx** [comment]
I'm not sure to understand what you mean by "typescript rewrite" ?

**Comment by riderx** [comment]
I just realized it works in Deno with ESM magic!

Just import like that 
```
import { Client } from "https://esm.sh/minio?target=deno"
```
TADA :)

**Comment by riderx** [comment]
For the record here is the issue i get on Deno or Cloudflare workers env:
![CleanShot 2024-02-12 at 22 45 24@2x](https://github.com/minio/minio-js/assets/4084527/7d487f37-ddc4-4efd-8c5a-028e9deea7db)
I created a PR to address all of these issue here:
https://github.com/minio/minio-js/pull/1265

**Comment by yurkimus** [comment]
> I just realized it works in Deno with ESM magic!
> 
> Just import like that
> 
> ```
> import { Client } from "https://esm.sh/minio?target=deno"
> ```
> 
> TADA :)

Thank you!

# And the types

## deno.json

```json
{
  "imports": {
    "minio": "https://esm.sh/minio@8.0.2?target=deno"
  },

  "vendor": true
}
```

## index.js

```javascript
// @deno-types="https://esm.sh/v135/@types/minio@7.1.0/index.d.ts"
import { Client } from 'minio'
```
