### ISSUE TITLE
presignedGetUrl with version id

### ISSUE THREAD

**Issue by rkreienbuehl** [minio/minio-js#1262]
**Is your feature request related to a problem? Please describe.**
Creating a presignedGetUrl is not possible for different versions of files.

**Describe the solution you'd like**
It would be nice, if we can add a versionId to the call for getting a presignedGetUrl, so a specific version of a file can be downloaded.

**Describe alternatives you've considered**
we use minio-js on our server-side. the only solution so far I found is, to download the file to the server and pass it to the client.

**Comment by prakashsvmx** [comment]
Please find an example below to get a presigned url with version id of an object :

```js

import * as Minio from 'minio'

const s3Client = new Minio.Client({
  endPoint: 'play.min.io',
  port: 9000,
  useSSL: true,
  accessKey: 'Q3AM3UQ867SPQQA43P2F',
  secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
})
/**
 * ➜ mc ls --versions play/minio-js-pre-ver
 * [2024-02-07 14:07:51 IST]   117B STANDARD 29887028-16a7-4d97-a596-e7d0d5d8a297 v2 PUT 1.txt
 * [2024-02-07 14:07:48 IST]   117B STANDARD 8bffeac7-257d-4bed-aed5-ce4801af5e03 v1 PUT 1.txt
 */

try {
  const url = await s3Client.presignedUrl('GET', 'minio-js-pre-ver', '1.txt' , 600, { versionId:"8bffeac7-257d-4bed-aed5-ce4801af5e03" });
  console.log('Success', url)
} catch (err) {
  console.log(err.message)
}

```
