### ISSUE TITLE
Error uploading files to minio 

### ISSUE THREAD

**Issue by kusaljr** [minio/minio-js#1270]
When i try uploading file to minio it throws this error 

<img width="805" alt="image" src="https://github.com/minio/minio-js/assets/51640562/4574a00c-9f58-4161-a3f1-9f705b82f229">

i'm using minio client version 7.1.3

**Comment by harshavardhana** [comment]
@kusaljr what is your endpoint pointing to ?

**Comment by kusaljr** [comment]
<img width="362" alt="image" src="https://github.com/minio/minio-js/assets/51640562/11d9bcfe-f097-44e6-9afc-444cc8ed60c8">

this is my minio client configuration, when i try doing other operations like list buckets, files, it works but when i try uploading file it gives me that parseError

**Comment by prakashsvmx** [comment]
What is the method used for uploading ? Please share the piece of code that actually does the `putObject` or `fPutObject`  @kusaljr

**Comment by kusaljr** [comment]
this it the code:
<img width="664" alt="image" src="https://github.com/minio/minio-js/assets/51640562/1ba857ac-43f7-49ed-8428-88c398bdae29">

this is my image object that i was trying to upload
<img width="1088" alt="image" src="https://github.com/minio/minio-js/assets/51640562/d5753777-38a6-4e7d-8941-97cd4643ebd5">

**Comment by prakashsvmx** [comment]
I have tried the below with `"minio": "^7.1.3"`  it looks fine..

code can be found in https://github.com/prakashsvmx/mino-js-consumer/pull/1


```
var Minio = require('minio')
var Fs = require('fs')

var minioClient = new Minio.Client({
    endPoint: 'localhost',
    port: 22000,
    useSSL: false,
    accessKey: 'minio',
    secretKey: 'minio123'
});


var file = "/home/prakash/Pictures/1.png"

  var fileStream = Fs.createReadStream(file)
  var metadata = {
    "content-type": '' // testing
  }
  var fileStat = Fs.stat(file, function(err, stats) {
    if(err) { 
      return console.log('error') 
    }
    minioClient.putObject("test-bucket", "1.png", fileStream, stats.size,
    function(err, objectInfo) {
      if (err) return console.log(err);
      console.log("File uploaded successfully1.", objectInfo);
    })
  })

```
```
 ➜ node api-tests/put-image.js
 
File uploaded successfully1. {
  etag: 'c1e890bca092ccffa92312b21423872d',
  versionId: 'a22b907f-a752-43d8-97a2-1a7e6e4064fa'
}

 ➜ mc ls local22/test-bucket/1.png --versions                                                  
[2024-03-11 10:18:24 IST] 164KiB STANDARD a22b907f-a752-43d8-97a2-1a7e6e4064fa v2 PUT 1.png
[2024-03-11 10:18:03 IST] 164KiB STANDARD 37f98b75-d064-47ef-92a9-8c525a0b0331 v1 PUT 1.png
```

are you running in browser or node environment? what is the node version used ?

**Comment by harshavardhana** [comment]
> <img alt="image" width="362" src="https://private-user-images.githubusercontent.com/51640562/311581121-11d9bcfe-f097-44e6-9afc-444cc8ed60c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzM4MzYsIm5iZiI6MTcxMDEzMzUzNiwicGF0aCI6Ii81MTY0MDU2Mi8zMTE1ODExMjEtMTFkOWJjZmUtZjA5Ny00NGU2LTlhZmMtNDQ0Y2M4ZWQ2MGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA1MDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNWNhNWQzYjM5YzM2YWJhYzVmZTdlMTMyMGVhNjA1ZTNmN2UzNWNlOTc3NWY5MWMwZWRiZjdiYTNlODk2ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mX7ZgrHjEs43KYUi6fBxPUCSonq_y6wbkh4i4Org27I">
> this is my minio client configuration, when i try doing other operations like list buckets, files, it works but when i try uploading file it gives me that parseError
> 
> @harshavardhana

Are you sure you are using the right endpoint and not passing Console UI URL?
