### ISSUE TITLE
Access MinIO with Bearer Authentication?

### ISSUE THREAD

**Issue by Sjoerd82** [minio/minio-js#1272]
I have added an OpenID provider to my MinIO setup. I was thinking that I could then access buckets from my SPA using a JWT bearer token. But I don't see this option in minio-js.

Is this type of access supported?

**Comment by prakashsvmx** [comment]
No, it is not supported.

**Comment by Sjoerd82** [comment]
Thanks for the fast reply! Will implement interactions with minio via our backend then.

_Out of curiosity... (being fairly new to all of this) is there an architectural or security reason to not support this type of access, or is is simply not implemented?_

**Comment by prakashsvmx** [comment]
This is designed for Node Environments and not for browser environments.
