### ISSUE TITLE
AssumeRoleProvider 

### ISSUE THREAD

**Issue by xkkkA** [minio/minio-js#1278]
I am using nodejs to operate minio, and now I want to obtain STS temporary credentials to pass to the front-end. How should I obtain them? I see the AssumeRoleProvider function in the source code, but why is it not open for bitwise conversion? How to use it and how to use it

**Comment by prakashsvmx** [comment]
Currently the typescript migration is in progress. 
for older versions, please refer to examples in https://github.com/minio/minio-js/pull/960

**Comment by prakashsvmx** [comment]
minimum is 15 minutes as per s3 spec i guess. 
you can check server traces
