### ISSUE TITLE
How to disconnect?

### ISSUE THREAD

**Issue by shahinghasemi** [minio/minio-js#1288]
Hello everyone, How can I disconnect the client from minio server? I want this for clean up phase of my tests, otherwise it can't exit properly which causes jest throws error that there are some tasks running while the tests are done.

**Comment by prakashsvmx** [comment]
Please add details like trace and code to help us understand issue if any. If it is application specific, we don't accomodate in this repo.

**Comment by prakashsvmx** [comment]
Please note, the repo has unit and functional tests

**Comment by shahinghasemi** [comment]
The issue was related to `setInterval` that i've put inside my test.
