### ISSUE TITLE
TypeError: transport.request is not a function     at request.js:10:1     at new Promise (<anonymous>)     at request (request.js:9:1)     at Client.makeRequestStreamAsync (client.js:465:1)

### ISSUE THREAD

**Issue by JasmineMoo** [minio/minio-js#1295]
minio 7.0.18
![image](https://github.com/minio/minio-js/assets/50284946/3b7bd160-7bad-4e90-8123-10bae61d5805)
catch error

**Comment by prakashsvmx** [comment]
Please add more details. Like typescript version

**Comment by prakashsvmx** [comment]
Please upgrade to recent versions. 
>minio 7.0.18 

is like few years old

**Comment by JasmineMoo** [comment]
![image](https://github.com/minio/minio-js/assets/50284946/9dc84474-00d2-4bff-a8d6-e12cdf09d8c3)
recent versions catch error 
![image](https://github.com/minio/minio-js/assets/50284946/dcd0e951-c9ee-4dbe-bd8a-42325797ba2e)

**Comment by prakashsvmx** [comment]
try with typesscript 
"typescript": "^5.0.4",
