### ISSUE TITLE
Incorrect return type for `TypedClient.getBucketVersioning()`

### ISSUE THREAD

**Issue by SleepyLeslie** [minio/minio-js#1296]
The function here definitely returns _something_, so its return type shouldn't be `Promise<void>`.

https://github.com/minio/minio-js/blob/86339689677b8e316984f94dfa96f741776fdd8f/src/internal/client.ts#L2095

Here is my suggestion. I didn't look very closely so I might have missed some fields.
```typescript
type VersioningStatus = {
  "Status": "Enabled" | "Suspended",
  "ExcludeFolders": boolean,
  "ExcludedPrefixes": {"Prefix": string}[]
}

getBucketVersioning(bucketName: string): Promise<"" | VersioningStatus>;
```

Note that it currently returns an empty string when versioning has never been toggled on. It might be a good idea to return `{Status: "Disabled"}` instead.

**Comment by prakashsvmx** [comment]
Yes. We will update it. Thank you for the feedback.

**Comment by SleepyLeslie** [comment]
Thanks @prakashsvmx for the fix. But the new typing still doesn't address the possible return value `''` when versioning has never been enabled.

**Comment by fflorent** [comment]
> Thanks @prakashsvmx for the fix. But the new typing still doesn't address the possible return value '' when versioning has never been enabled. Will that be fixed?

Opened https://github.com/minio/minio-js/issues/1303 to track your question.
