### ISSUE TITLE
IncludeVersion flag on listObjects api with GCS does not return objects

### ISSUE THREAD

**Issue by samirp91** [minio/minio-js#1302]
Currently, I have a minio client instantiated with GCS as follows:

```
const MinioClient = new Minio.Client({
	endPoint: process.env.MINIO_ENDPOINT, // storage.googleapis.com
	useSSL: process.env.MINIO_USE_SSL === 'true',
	accessKey: process.env.MINIO_ACCESS_KEY,
	secretKey: process.env.MINIO_SECRET_KEY,
	port: parseInt(process.env.MINIO_PORT)
});
```

I am then calling the `listObjects` function with the `IncludeVersion` flag and I am receiving an empty response. If I call it without the flag, I get back the objects. I have enabled versioning in the GCS bucket as well. 

```
const { bucketName, folder, includeVersions } = params;
	try {
		const objectsStream = MinioClient.listObjects(
			bucketName,
			folder,
			true,
			{
				IncludeVersion: !!includeVersions
			}
		);

		const object = [];
		objectsStream.on('data', (obj) => {
			console.log(obj);
		});
		for await (const obj of objectsStream) {
			object.push(obj);
		}

		return object;
	} catch (error) {
		throw error;
	}
}
```

**Comment by klauspost** [comment]
I don't think GCS supports versioning in their S3 API.

**Comment by samirp91** [comment]
> I don't think GCS supports versioning in their S3 API.

It's listed on their API page. 

https://cloud.google.com/storage/docs/json_api/v1/objects/list

**Comment by klauspost** [comment]
@samirp91 That is not their S3 API.

**Comment by klauspost** [comment]
Either way, feel free to reach out to them.
