### ISSUE TITLE
type lifeCycleRule incorrect

### ISSUE THREAD

**Issue by juliebrunetto83** [minio/minio-js#1306]
It seems that the typing of the Expiration key in lifeCycleRule is incorrect.  Date, Days, DeleteMarker, DeleteAll have all become required since the last update. This creates a typing error when I call the setBucketLifecycle function.
What should I do ?

**Comment by prakashsvmx** [comment]
https://github.com/minio/minio-js/blob/06758a5fdf462fbc21267c133959c3bb7fbd7873/src/internal/type.ts#L359

Looks they are optional.

**Comment by prakashsvmx** [comment]
https://github.com/minio/minio-js/blob/06758a5fdf462fbc21267c133959c3bb7fbd7873/src/internal/type.ts#L323

Yeah looks like..  we can mark them optional. Feel free to send a PR.

**Comment by prakashsvmx** [comment]
fixed as part of #1308
