### ISSUE TITLE
I find a bug, putObject can not  resume upload when use multipart upload , see the source code 

### ISSUE THREAD

**Issue by juoliii** [minio/minio-js#1318]
private async uploadStream(
    bucketName: string,
    objectName: string,
    headers: RequestHeaders,
    body: stream.Readable,
    partSize: number,
  ): Promise<UploadedObjectInfo> {
    // A map of the previously uploaded chunks, for resuming a file upload. This
    // will be null if we aren't resuming an upload.
    const oldParts: Record<number, Part> = {}

    // Keep track of the etags for aggregating the chunks together later. Each
    // etag represents a single chunk of the file.
    const eTags: Part[] = []

    const previousUploadId = await this.findUploadId(bucketName, objectName)
    let uploadId: string
    if (!previousUploadId) {
      uploadId = await this.initiateNewMultipartUpload(bucketName, objectName, headers)
    } else {
      uploadId = previousUploadId
      const oldTags = await this.listParts(bucketName, objectName, previousUploadId)
      oldTags.forEach((e) => {
        oldTags[e.part] = e
      })
    }

in the source code , oldParts aways empty

**Comment by prakashsvmx** [comment]
can you share `mc admin trace -v <ALIAS>` for the complete multipart upload/resume ?

**Comment by juoliii** [comment]
> can you share `mc admin trace -v <ALIAS>` for the complete multipart upload/resume ?

please see the source code client.ts , line 1698，the var oldParts， aways empty，this is a bug , and putObject can not resume upload

**Comment by harshavardhana** [comment]
There is no resume functionality in multipart API.

Relying on listparts() is racy as it's point in time consistent it is not aware of concurrent PUTs on the same uploadId.

And there is no serialization between both. So relying on that to finish complete multipart can potentially lead to corruption. 

You should manage what you uploaded locally if you wish resume disparate parts.

There is no proper way to resume in S3 API which is safe. It is designed for atomic uploads.
