### ISSUE TITLE
Why not expose max_key in listObjectsV2 interface

### ISSUE THREAD

**Issue by Kanna-Neko** [minio/minio-js#1319]
https://github.com/minio/minio-js/blob/20327318cbc528d1fa75ca511d768527aacd17a1/src/minio.js#L320
I found the listObjectV2 interface in go sdk have max_key parameter, and then when I hope to use it in js sdk, but I found it not be exposed.

**Comment by harshavardhana** [comment]
This SDK provides a higher level API,

Go SDK provides more control for other purposes, JS tries to be more simpler.

What is the purpose?

**Comment by Kanna-Neko** [comment]
I'm making a picture album by using minio as a storage system, I hope to use JS as server to handle with minio, then I notice this question because I don't use a DB instead use minio ability to address infomation。

In my case, I'm hope to paging file, so I offered my opinion.

Thank you answer my question.

**Comment by harshavardhana** [comment]
you shouldn't be using List() as way to populate your UI, if you do that it won't scale as an application. 

You have to think about namespace differently.
