### ISSUE TITLE
Not able to load PDF document after getting the URL from presignedGetObject

### ISSUE THREAD

**Issue by nikhil104iic** [minio/minio-js#1331]
I am using presignedGetObject method to generate the URL and this is how it is coming - 
Presigned URL - http://10.2.0.300:9000/testing/1ZBF000043R1001.pdf?response-content-type=application%2Fpdf&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxxxxxxx%2F20240813%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240813T083408Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxxxsignaturexxxx

When I open this URL on browser, I see the PDF loaded. but when I use this link to open the PDF in my application it gives this error - 

AuthorizationQueryParametersErrorError parsing the X-Amz-Credential parameter; the Credential is mal-formed; expecting "<YOUR-AKID>/YYYYMMDD/REGION/SERVICE/aws4_request".1ZBF000043R1001.pdftesting/testing/1ZBF000043R1001.pdf17EB3DCE3B2E1296dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8

This is how I am using it in my application - 

< embed id="pdf_embed" class="pdf_embed" src="http://10.2.0.300:9000/testing/1ZBF000043R1001.pdf?response-content-type=application%2Fpdf&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxxxxxxx%2F20240813%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240813T083408Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxxxsignaturexxxx" width="100%" style="height:calc(100vh - 241px)" type="application/pdf" >

I am not really sure what is missing. Can anyone able to help me please.

**Comment by prakashsvmx** [comment]
Please check the `mc admin trace -v <ALIAS>` for both the requests.

**Comment by harshavardhana** [comment]
> < embed id="pdf_embed" class="pdf_embed" src="http://10.2.0.300:9000/testing/1ZBF000043R1001.pdf?response-content-type=application%2Fpdf&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxxxxxxx%2F20240813%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240813T083408Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxxxsignaturexxxx" width="100%" style="height:calc(100vh - 241px)" type="application/pdf" >
> 
> I am not really sure what is missing. Can anyone able to help me please.

Presigned URLs are not a good idea to be embedded in HTML, if your asset is public set bucket policies to make sure your asset is publicly accessible.

**Comment by nikhil104iic** [comment]
> > < embed id="pdf_embed" class="pdf_embed" src="http://10.2.0.300:9000/testing/1ZBF000043R1001.pdf?response-content-type=application%2Fpdf&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxxxxxxx%2F20240813%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240813T083408Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxxxsignaturexxxx" width="100%" style="height:calc(100vh - 241px)" type="application/pdf" >
> > I am not really sure what is missing. Can anyone able to help me please.
> 
> Presigned URLs are not a good idea to be embedded in HTML, if your asset is public set bucket policies to make sure your asset is publicly accessible.

@harshavardhana - If my bucket is not public, it is private then what are the other options I have I can use it using embed tag ?
