### ISSUE TITLE
garage omit Location in CompleteMultipartUploadResult cause minio js client failed to parse

### ISSUE THREAD

**Issue by wenerme** [minio/minio-js#1332]
garage https://git.deuxfleurs.fr/Deuxfleurs/garage/src/commit/3a87bd1370eb9fefc67deec9d7dfa2187ddf9763/src/api/s3/multipart.rs#L432

MinioJS 
https://github.com/minio/minio-js/blob/d08e54a391adb8fe6630c8cfde66621d6f37b777/src/internal/xml-parser.ts#L282-L303

The response demo

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CompleteMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Bucket>X</Bucket>
    <Key>X</Key>
    <ETag>&quot;572e7a853374de6582ca2b0bc03486e1-1&quot;</ETag>
</CompleteMultipartUploadResult>
```

I don't know which one is correct so I create issues in both project.

xref https://git.deuxfleurs.fr/Deuxfleurs/garage/issues/852

**Comment by prakashsvmx** [comment]
we do not support external libraries. Please refer to other minio sdks and s3 SDKs. 

Please share `mc admin trace <ALIAS> -v`  in case of discrepencies ?
