### ISSUE TITLE
Using minio in umi project generates errors

### ISSUE THREAD

**Issue by liulipeng721** [minio/minio-js#1341]
![b04ef16217c2cba98bd3f0f5914cac2](https://github.com/user-attachments/assets/39325be2-e630-459d-94d5-544504a63728)

"minio": "^8.0.1",
 "@umijs/max": "^4.0.67",
const minioClient = new Minio.Client({
  endPoint: 'xx.xx.xx.xx',
  port: 9000,
  useSSL: false,
  accessKey: 'xxxxx',
  secretKey: 'xxxxx',

});
React  18 
console.log("minio-: ", minioClient)

**Comment by prakashsvmx** [comment]
This looks like application build setup issue. Please check the build process.
