### ISSUE TITLE
Useing minio-v8.0.1  Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).

### ISSUE THREAD

**Issue by liulipeng721** [minio/minio-js#1342]
Useing  import * as Minio from 'minio';     "minio": "^8.0.1",

![1725355521670](https://github.com/user-attachments/assets/a1f06eae-ade6-4bc7-9089-10409c2a2bcd)

**Comment by prakashsvmx** [comment]
Please use supported node version. or adjust webpack settings accordingly
