### ISSUE TITLE
fPutObject() is no return value

### ISSUE THREAD

**Issue by monkeykingblack** [minio/minio-js#1345]
I am currently using the latest version **8.0.1**. When I use the `fPutObject` function, I don't receive the return result like I used to in version **7.1.3**. When I look inside the SDK, I see that the final result uses the `putObject` function but there is no return statement.

Is this a new feature or what that I am missing?

**Comment by prakashsvmx** [comment]
Thank you for reporting @monkeykingblack ,

i have sent a PR https://github.com/minio/minio-js/pull/1346 to return the values

**Comment by monkeykingblack** [comment]
> Thank you for reporting @monkeykingblack ,
> 
> i have sent a PR #1346 to return the values

Thank you
