### ISSUE TITLE
error Creating client

### ISSUE THREAD

**Issue by jfparrado** [minio/minio-js#1349]
This is my code:
import * as Minio from 'minio';

const clientOptions: Minio.ClientOptions = {
  endPoint: 'xxxx',
  port: xxxx,
  useSSL: false,
  accessKey: "xxxx",
  secretKey: "xxxx",
  // region: "xxxx",
};

const minioClient = new Minio.Client(clientOptions);

export default async (path: string, file: File) => {
  // ...
}

But i always get this error "500
The "original" argument must be of type Function

at promisify3 (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/minio.js?v=258a902a:29773:15)
at http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/minio.js?v=2"

how can i resolve this? I am using NUXT3 and i am defining it inside of the folder compables

**Comment by prakashsvmx** [comment]
What is the typescript version and how is the build setup ?

**Comment by prakashsvmx** [comment]
It is not intended for usage in web browser. it can be used node js
