### ISSUE TITLE
`LifecycleRule` is incorrectly typed

### ISSUE THREAD

**Issue by Aloso** [minio/minio-js#1357]
I had the following (working) code using `minio@^7`:

```ts
client.setBucketLifecycle(bucket, {
    Rule: [
        {
            ID: 'BucketPathExpireRule',
            Status: 'Enabled',
            Filter: {
                Prefix: 'combined-documents',
            },
            Expiration: {
                Days: 1,
            },
        },
    ],
});
```

When upgrading to `minio@^8`, I noticed a type error: The `LifecycleRule` type has no property `Filter`, instead, it has a `RuleFilter` property. However, after renaming it, the code stopped working:

> S3Error: The XML you provided was not well-formed or did not validate against our published schema

**Comment by prakashsvmx** [comment]
thank you for reporting:

Yes. the key need renaming.

**Comment by prakashsvmx** [comment]
i hope this is fixed in the latest release.

**Comment by ace0527** [comment]
> <img alt="Image" width="636" height="400" src="https://private-user-images.githubusercontent.com/803674/486423220-d22e5b27-785a-46a6-a524-73e4fa2998a7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTcxNzE5NzQsIm5iZiI6MTc1NzE3MTY3NCwicGF0aCI6Ii84MDM2NzQvNDg2NDIzMjIwLWQyMmU1YjI3LTc4NWEtNDZhNi1hNTI0LTczZTRmYTI5OThhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkwNlQxNTE0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2Q0ZTE0NTZiNjhhNmI2OTZkYzBhN2JlNmY0YzY4ZDE1YzU1ZGY2MTQzYTUyNTI4OGM3MWQ5Yzc2ZDNiZjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pCCe5HBGzVToRVdosc7Hv1lhsNETWT0OIEluduDWM0I">
> [@Aloso](https://github.com/Aloso), yep

holy.. I just tried and found that you must send `Expiration` or `NoncurrentVersionExpiration` or else the request will fail with status 400.., at least for my side(although I don't need `NoncurrentVersionExpiration` this config at all) ,  but I don't know whether you would cause this error if remove your `NoncurrentVersionExpiration`  config.


Besides this, I also found that if you send `Filter` with params `prefix` and `Tag` you will also fail with this error:
```
          Filter: {
            Prefix: '',
            Tag: [
              { Key: MinioTagKey.Status, Value: MinioTagValue.Invalid },
            ],
          },
```
```S3Error: Filter must have exactly one of Prefix, Tag, or And specified```

You can only request successfully like this: 
```
          Prefix: '',
          Filter: {
            Tag: [
              { Key: MinioTagKey.Status, Value: MinioTagValue.Invalid },
            ],
          },
```

But what's funny is that in the minio source code,  the prefix param in the ` RuleFilter` is required: 
```
export type RuleFilter = {
  And?: RuleFilterAnd;
  Prefix: string;
  Tag?: Tag[];
};
```
so you have to change the type to LifecycleConfig manually.

after all , thanks for you information, I 've been struggling with this for 3 hours.I think I will still end up this with confusions lol.
