### ISSUE TITLE
Why there is no way to get content-type for from any api in this js sdk

### ISSUE THREAD

**Issue by lechuhuuha** [minio/minio-js#1361]
why js sdk not even return any content type from object

in go sdk
![ảnh](https://github.com/user-attachments/assets/2126dc34-ee12-474e-b013-a6e091227a09)

in js sdk
![ảnh](https://github.com/user-attachments/assets/0acf87aa-7e2a-4569-b64a-5d48bb1fffbd)

can this be fix?
thanks

**Comment by prakashsvmx** [comment]
Thank you, 
Will update the documentation. 

The content type can be accessed with metadata like below.
```js
const statTest = async () =>{
    const statInfo = await minioClient.statObject("test-bucket","1.txt")
    console.log(statInfo)
}

statTest()
```

### Result
```json
{
  size: 2,
  metaData: { 'content-type': 'text/plain' },
  lastModified: 2024-11-28T07:16:39.000Z,
  versionId: null,
  etag: '80ec144fdfd47f7f32e96fc58b2e01ee-1'
}

```
