### ISSUE TITLE
Can't resolve 'node:fs'

### ISSUE THREAD

**Issue by Harpoonhu** [minio/minio-js#1364]
![image](https://github.com/user-attachments/assets/9dbe7d8b-4f9d-40f5-9886-81024f24517e)
When I created the client,   this error came out

**Comment by Harpoonhu** [comment]
react:18.3.1
node:20.11.1
minio:8.0.2
minioClient.fPutObject('test','test.js','/test.js')

**Comment by prakashsvmx** [comment]
This is not intended for Web Environments.  We will add it may be in future.
