### ISSUE TITLE
Difficulty Connecting to Supabase S3-Compatible Storage

### ISSUE THREAD

**Issue by amirs18** [minio/minio-js#1370]
---

**Issue: Difficulty Connecting to Supabase S3-Compatible Storage**

I am trying to connect to Supabase's S3-compatible storage but am encountering some difficulties. The Supabase endpoint I am working with is structured as follows:

```
https://xxxxxxxxxxxx.supabase.co/storage/v1/s3
```

Could you provide guidance or examples on how to establish a connection to this endpoint? Any help or documentation links would be greatly appreciated.

---

**Comment by prakashsvmx** [comment]
Please check respective documentation of the provider. 
We support S3 APIs . minio sdks and S3 sdks are mostly functionally compatible. Ensure that the provider is compatible with such S3 sdks and cmd .   Not sure if S3 APIs support with such urls as endpoints.

**Comment by amirs18** [comment]
InvalidEndpointError: Invalid endPoint : xxxxxxxxxxxxxx.supabase.co/storage/v1/s3
    at new TypedClient (file:///home/node/.cache/deno/npm/registry.npmjs.org/minio/8.0.2/dist/esm/internal/client.mjs:58:13)
    at new Client (file:///home/node/.cache/deno/npm/registry.npmjs.org/minio/8.0.2/dist/esm/minio.mjs:32:8)

}

**Comment by amirs18** [comment]
This is the error I'm getting as you can see nothing related to the provider

**Comment by prakashsvmx** [comment]
The S3 APIs have virtual style or path style
https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html
https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.htm


So the above api endpoint is not a valid S3 endpoint.

**Comment by amirs18** [comment]
It uses the path style and it works with the @aws-sdk/s3-client pkg so I'm finding it hard to believe it's not compatible... I will link a code example shortly

**Comment by prakashsvmx** [comment]
`xxxxxxxxxxxxxx.supabase.co` may be valid but NOT ` xxxxxxxxxxxxxx.supabase.co/storage/v1/s3`

**Comment by amirs18** [comment]
i feal like you are not willing to hear me out...
the below code works 
this is the link to supabase s3 compatibility now it is in alpha but it works 
https://supabase.com/docs/guides/storage/s3/compatibility

please take a moment to check if there is a way to make the minio libery also work 
```
import { S3 } from "@aws-sdk/client-s3";

const s3Aws = new S3({
  region: "us-east-1",
  endpoint: "https://xxxxxxxxxxxxxx.supabase.co/storage/v1/s3",
  credentials: {
    accessKeyId: S3_ACCESS_KEY,
    secretAccessKey: S3_SECRET_KEY,
  },
  forcePathStyle: true,
});
```

**Comment by amirs18** [comment]
https://github.com/minio/minio-js/blob/master/src/internal/client.ts

look at line 450 

if you change it to 

```
    const startPath = opts.startPath ?? '/'
    let path = startPath;
```

and change this if block its working

```
    if (virtualHostStyle && !opts.pathStyle) {
      // For all hosts which support virtual host style, `bucketName`
      // is part of the hostname in the following format:
      //
      //  var host = 'bucketName.example.com'
      //
      if (bucketName) {
        host = `${bucketName}.${host}`;
      }
      if (objectName) {
        path = `/${objectName}`;
      }
    } else {
      // For all S3 compatible storage services we will fallback to
      // path style requests, where `bucketName` is part of the URI
      // path.
      if (bucketName) {
        path = `${startPath}/${bucketName}`;
      }
      if (objectName) {
        path = `${startPath}/${bucketName}/${objectName}`;
      }
    } 
```

**Comment by prakashsvmx** [comment]
As per S3 Spec path style should be: as specified in the doc:

So please work with your provider.. or feel free to fork and do the changes as per your requirements. 

https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access

![image](https://github.com/user-attachments/assets/7e635f87-f88e-4960-a9c8-c741d9c370b8)
