### ISSUE TITLE
Ignore the following headers:

### ISSUE THREAD

**Issue by fkautz** [minio/minio-js#241]
Authorization
Content-Type
Content-Length
User-Agent

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-go/pull/109 - add comments from this commit for ignored headers for more information for developers in future

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-js/blob/master/src/main/signing.js#L108, you must have not seen my comment on #241 

From this
```javascript
    if (request.headers.hasOwnProperty(key) && ignoredHeaders.indexOf('Authorization') === -1) {
```

To this 
```javascript
   if (request.headers.hasOwnProperty(key) && ignoredHeaders.indexOf(key) === -1) {
```
