### ISSUE TITLE
npmjs package 0.2.0 doesn't in package.json

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#277]
https://github.com/minio/minio-js/blob/master/package.json#L3

We should really commit it before making an upstream release. This will cause confusion.

**Comment by abperiasamy** [comment]
Please go ahead and remove this release. This is totally not acceptable.

**Comment by fkautz** [comment]
Based on previous conversation, this was redacted, and latest version published as 0.2.1.

**Comment by harshavardhana** [comment]
You should tag 0.2.1 as well.
