### ISSUE TITLE
Improve our error messages for all exceptions. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#361]
```
// set minimum/maximum length of what Content-Length can be
+  setContentLength(min, max) {
+    if (min > max) {
+      throw new errrors("min can not be more than max")
+    }
+    if (min < 0) {
+      throw new errors("min has to be > 0")
+    }
+    if (max < 0) {
+      throw new errors("max has to be > 0")
+    }
+    this.policy.conditions.push(["content-length-range", min, max])
+  }
```

For invalid argument, lets add 'InvalidArgumentException'

**Comment by harshavardhana** [comment]
> +      throw new errrors("min can not be more than max")

Another problem is this @krishnasrinivas did you test this ?

**Comment by harshavardhana** [comment]
> Another problem is this @krishnasrinivas did you test this ?

The only way to avoid them is we add tests for each failure condition - even when the failure occurs, we have to verify the type associated with the error.

**Comment by krishnasrinivas** [comment]
yes, this needs to be fixed. tests needs to be added as well
