### ISSUE TITLE
Temporary redirect error for a bucket in eu-west-1 region. 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#374]
```
var s3Client = new Minio({
  endPoint: 'https://s3.amazonaws.com',
  accessKey: '************',
  secretKey: '************'
})

s3Client.statObject('myuniquebucketnameforevery', 'minio.js', function(e, stat) {
  if (e) {
    return console.log(e)
  }
  console.log(stat)
})
```

```
$ node stat-object.js
{ requestid: null,
  code: 'TemporaryRedirect',
  message: 'Are you using the correct endpoint URL?' }
```

```
$ mc ls myuniquebucketnameforevery.s3.amazonaws.com
[2015-12-09 12:32:37 PST]  45KiB minio.js
```

**Comment by harshavardhana** [comment]
Looks like transparently S3 fixed itself. its working fine now. 

```
$ node stat-object.js
eu-west-1
{ size: 45689,
  etag: 'cdc831c70b2a8a63e493001fffb30ff1',
  contentType: 'application/javascript',
  lastModified: 'Wed, 09 Dec 2015 20:32:37 GMT' }
```

**Comment by maxnordlund** [comment]
I got this just now for eu-north-1, not sure why though as this library doesn't give much information in the error (like the response).

**Comment by harshavardhana** [comment]
> I got this just now for eu-north-1, not sure why though as this library doesn't give much information in the error (like the response).

We can only give what server gives and server give enough info apparently @maxnordlund

**Comment by maxnordlund** [comment]
Darn it. But it would be nice if it could follow redirects, or at least include the `Location` header to see what it wants, right?

**Comment by harshavardhana** [comment]
> Darn it. But it would be nice if it could follow redirects, or at least include the `Location` header to see what it wants, right?

Unfortunately, AWS S3 doesn't set the Location header sends as an XML response. The nodejs http package cannot redirect without Location header. So this is a server bug which we can't do much unfortunately.

**Comment by maxnordlund** [comment]
That is truly a bummer. Would it be possible to attach the response to the error, so you can inspect it in a repl?
