### ISSUE TITLE
http: Set Expect header 100-continue for put requests

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#421]
```
     [java] DEBUG [org.apache.http.headers] >> Expect: 100-continue
     [java] DEBUG [org.apache.http.wire]  << "HTTP/1.1 100 Continue[\r][\n]"
     [java] DEBUG [org.apache.http.wire]  << "[\r][\n]"
     [java] DEBUG [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 100 Continue
     [java] DEBUG [org.apache.http.headers] << HTTP/1.1 100 Continue
```

**Comment by harshavardhana** [comment]
8.2.3 Use of the 100 (Continue) Status

The purpose of the 100 (Continue) status (see section 10.1.1) is to allow a client that is sending a request message with a request body to determine if the origin server is willing to accept the request (based on the request headers) before the client sends the request body. In some cases, it might either be inappropriate or highly inefficient for the client to send the body if the server will reject the message without looking at the body.

Requirements for HTTP/1.1 clients:

      - If a client will wait for a 100 (Continue) response before
        sending the request body, it MUST send an Expect request-header
        field (section 14.20) with the "100-continue" expectation.
      - A client MUST NOT send an Expect request-header field (section
        14.20) with the "100-continue" expectation if it does not intend
        to send a request body.

**Comment by krishnasrinivas** [comment]
@harshavardhana i had used 100-continue in minio-js to fix the wrong region problem for putObject so that it can be resumed. AB pointed out two problems with it:
* the requests get slower because request needs to wait for the server to say 100-continue
* many s3 server implementations might not implement 100-continue

**Comment by harshavardhana** [comment]
> the requests get slower because request needs to wait for the server to say 100-continue

This we need to verify, then all aws-sdks are slower if this assumption is correct. 

> many s3 server implementations might not implement 100-continue

100-continue is perhaps implemented on Swift and Ceph.  Then If aws-sdk defaults to '100-continue' this would break all other servers?. 

I think both are wrong assumptions here.

**Comment by harshavardhana** [comment]
A simple example to observe is this, we do not yet trap 100-continue and validate the headers which can be easily done. 

```
$ curl -i -X PUT -T README.md -H 'Expect: 100-continue' https://play.minio.io:9000/testbucket/
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Accept-Ranges: bytes
Etag: "923325b19546e6a3eac092b2c60eac84"
Server: Minio/UNOFFICIAL.2016-01-08T22-46-01Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: B2AOL6CYSOJ1HJH5
Date: Fri, 15 Jan 2016 03:47:55 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

**Comment by harshavardhana** [comment]
https://tools.ietf.org/html/rfc7231#page-35 - 

```
 A client that receives a 417 (Expectation Failed) status code in
      response to a request containing a 100-continue expectation SHOULD
      repeat that request without a 100-continue expectation, since the
      417 response merely indicates that the response chain does not
      support expectations (e.g., it passes through an HTTP/1.0 server).
```

**Comment by krishnasrinivas** [comment]
Expect header was removed from minio-go. Closing this issue.
