### ISSUE TITLE
get-object.html sample does not work

### ISSUE THREAD

**Issue by wannaxue** [minio/minio-js#427]
Given the input as below to create the Minio 
>>
      var s3Client = new Minio({
        endPoint: '127.0.0.1',
        port: 9000,
        accessKey: '...',
        secretKey: '...',
        insecure: true
      });
<<
and get the error in console like below
>>
Uncaught TypeError: Cannot set property 'keepAlive' of undefined                     minio-browser.js:718
<<

**Comment by krishnasrinivas** [comment]
@wannaxue for browser use you can just comment out the line:
```js
 transport.globalAgent.keepAlive = true
```
in minio.js

I will merge in the fix for this to disable keepAlive for browser environments.

**Comment by wannaxue** [comment]
Still no luck to get it work after bypass this one and got another "region is not a string" error. I tried the nodejs sample and it does not work as well and report the error as below. Any clue?

>>
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:107:11)
    at Object.urlParse [as parse] (url.js:101:5)
    at new Client (i:\source\minio.js:43:25)
    at Object.<anonymous> (i:\gitrepos\test\runMinio.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
<<

**Comment by harshavardhana** [comment]
> Still no luck to get it work after bypass this one and got another "region is not a string" error. I tried the nodejs sample and it does not work as well and report the error as below. Any clue?

Are you using the ``minio`` released at npm ? - current examples are incompatible with what was released, much of it has been re-written.

**Comment by harshavardhana** [comment]
> Still no luck to get it work after bypass this one and got another "region is not a string" error. I tried the nodejs sample and it does not work as well and report the error as below. Any clue?
> Are you using the minio released at npm ? - current examples are incompatible with what was released, much of it has been re-written.

Can you verify again with - https://github.com/minio/minio-js#install-from-source ?

**Comment by wannaxue** [comment]
Yes, firstly, I used the npm to install the minio, then I tried the source install from git, it works for the listBuckets sample, but the listObjects still not work and got error as below.
>>
i:\gitrepos\minio-js\examples>node get-object.js
buckets : [ { name: 'xxf',
    creationDate: Mon Feb 01 2016 05:04:48 GMT+0800 (中国标准时间) } ]

i:\source\signing.js:199
    throw new TypeError('region should be of type "string"')
          ^
TypeError: region should be of type "string"
    at signV4 (i:\source\signing.js:199:11)
    at _makeRequest (i:\source\minio.js:345:29)
    at DestroyableTransform.<anonymous> (i:\source\minio.js:395:11)
    at DestroyableTransform.emit (events.js:117:20)
    at i:\gitrepos\minio-js\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at process._tickCallback (node.js:419:13)
<<

My client is setup up as below.
>>
var s3Client = new Minio({
  endPoint: '127.0.0.1',
  port:9000,
  accessKey: '...',
  secretKey: '...',
  insecure: true
});
<<

**Comment by krishnasrinivas** [comment]
we'll get back on this.

**Comment by krishnasrinivas** [comment]
@wannaxue 
i see that the script name is get-object.js and output is listBuckets:
```
buckets : [ { name: 'xxf',
creationDate: Mon Feb 01 2016 05:04:48 GMT+0800 (中国标准时间) } ]
```
and you mention that it is listObjects.

list-objects on my local system works fine. can you paste your complete script?

**Comment by wannaxue** [comment]
Here is my full code -
>>
var Minio = require('../dist/main/minio')

var s3Client = new Minio({
  endPoint: '127.0.0.1',
  port:9000,
  accessKey: '...',
  secretKey: '...',
  insecure: true
});


s3Client.listBuckets(function(e, buckets) {
  if (e) return console.log(e)
  console.log('buckets :', buckets)

  buckets.forEach(function  (bucket) {
    // List all object paths in bucket my-bucketname.
    var objectsStream = s3Client.listObjects(bucket.name, '', true)
    objectsStream.on('data', function(obj) {
      console.log(obj)
    });
    objectsStream.on('error', function(e) {
      console.log(e)
    });
  });
});
<<

and here is my console output -
>>
I:\gitrepos\minio-js\examples>node get-object.js
buckets : [ { name: 'xxf',
    creationDate: Mon Feb 01 2016 05:04:48 GMT+0800 (中国标准时间) } ]

I:\source\signing.js:199
    throw new TypeError('region should be of type "string"')
          ^
TypeError: region should be of type "string"
    at signV4 (I:\source\signing.js:199:11)
    at _makeRequest (I:\source\minio.js:345:29)
    at DestroyableTransform.<anonymous> (I:\source\minio.js:395:11)
    at DestroyableTransform.emit (events.js:117:20)
    at I:\gitrepos\minio-js\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at process._tickCallback (node.js:419:13)
<<

**Comment by krishnasrinivas** [comment]
@wannaxue can you paste output of `minio version`

**Comment by wannaxue** [comment]
minio version
Version: 2015-12-23T01:51:12Z
Release-Tag: OFFICIAL.2015-12-23T01-51-12Z
Commit-ID: 155a4110b16c73f9fcec6597c203abf69c339ed1

**Comment by krishnasrinivas** [comment]
We fixed a bug related to this in minio server, can you compile the minio server from latest source? Instructions are available here:
https://github.com/minio/minio

**Comment by philxia** [comment]
Awesome! The latest minio works.

**Comment by harshavardhana** [comment]
Closing.. this minio server with fix has been released.
