### ISSUE TITLE
net: Socket hang up while using bucket-exists.js example with minio server

### ISSUE THREAD

**Issue by steffenmllr** [minio/minio-js#431]
Hey there!

I just wanted to try out minio and minio-js on my local osx environment but it doesn seem to work:

```
./minio server ./mydata
```
```js
var Minio = require('minio')

var s3client = new Minio({
  endPoint:  'localhost',
  accessKey: '***',
  secretKey: '***',
  port: 9000,
  insecure: true,
  region: 'us-east-1'
});
s3client.bucketExists('mybucket', function(e) {
    console.log(e);
})
```

All I get is a `{ [Error: socket hang up] code: 'ECONNRESET' }`

Do you have suggestions on how to set this up for local development ?

**Comment by krishnasrinivas** [comment]
@steffenmllr let me check.

**Comment by krishnasrinivas** [comment]
@steffenmllr tried to reproduce this problem with various combinations of setup but could not.
Do you see any errors on the `./minio server ./mydata` console output?
Can you try if `mc` works fine? you should have a brief output on `./minio server` console like this:
```
To configure Minio Client:

    $ wget https://dl.minio.io/client/mc/release/linux-amd64/mc

    $ chmod 755 mc

    $ ./mc config host add myminio http://localhost:9000 *** ***

    $ ./mc ls myminio/mybucket
```

**Comment by krishnasrinivas** [comment]
@steffenmllr also can you check if any other process is running on 9000? `lsof -i tcp:9000`

Also can you try running minio on different port and check:
`./minio --address ":10000" server ./mydata`

**Comment by harshavardhana** [comment]
Easy to reproduce start with 

```
$ cat main.go
package main

import (
	"fmt"
	"log"
	"net/http"

	reuse "github.com/jbenet/go-reuseport"
)

func main() {
	listen, err := reuse.Listen("tcp", "0.0.0.0:9000")
	if err != nil {
		log.Fatalln(err)
	}
	fmt.Printf("Listening on %s\n", listen.Addr())

	server := &http.Server{}
	for {
		_, err := listen.Accept()
		if err != nil {
			log.Fatalln(err)
		}
		go server.Serve(listen)
	}

}
``` 

```
$ go run main.go 
```

Now start minio server as well 

```
$ sudo lsof -iTCP:9000 -sTCP:LISTEN
COMMAND   PID   USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
main    52821 harsha    4u  IPv4 0x56757194c2040e1      0t0  TCP *:cslistener (LISTEN)
minio   52822 harsha    4u  IPv6 0x56757194c40d1f1      0t0  TCP *:cslistener (LISTEN)
```

Now run 'bucket-exists.js'

```
var Minio = require('minio')

var s3Client = new Minio({
  endPoint: 'localhost',
  port: 9000,
  insecure: true,
  accessKey: 'xxxxx',
  secretKey: 'xxxxx'
})

s3Client.bucketExists('testbucket', function(e) {
  if (e) {
    return console.log(e)
  }
  console.log("True")
})
```
```
$ node bucket-exists.js
```

This will hang, now kill ``52821``
```
$ kill 52821
```

```
$ node bucket-exists.js
{ [Error: socket hang up] code: 'ECONNRESET' }
```

**Comment by steffenmllr** [comment]
@krishnasrinivas Thanks that was the problem, something was running at 9000. There should really be an error when Minio can not open the port like when the folder does not exist

**Comment by harshavardhana** [comment]
> @krishnasrinivas Thanks that was the problem, something was running at 9000. There should really be an error when Minio can not open the port like when the folder does not exist

It is out of control from minio server, if another process has opened a socket with SO_REUSEADDR and SO_REUSEPORT. As stated in previous comment. 

What we need to see is why 'golang' http client is behaving different than 'nodejs' http client.

**Comment by krishnasrinivas** [comment]
The problem is not because of SO_REUSEPORT but because on macos minio is listening on ipv6 address (whereas it fails on linux saying port is already in use)

```
$ sudo lsof -iTCP:9000 -sTCP:LISTEN

COMMAND   PID   USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME

main    52821 harsha    4u  IPv4 0x56757194c2040e1      0t0  TCP *:cslistener (LISTEN)

minio   52822 harsha    4u  IPv6 0x56757194c40d1f1      0t0  TCP *:cslistener (LISTEN)
```

working on a fix where during the start,  minio makes sure that 9000(or the requested port) is not used on any of the ipv6 or ipv4 addresses.

**Comment by harshavardhana** [comment]
> The problem is not because of SO_REUSEPORT but because on macos minio is listening on ipv6 address (whereas it fails on linux saying port is already in use)
> 
> $ sudo lsof -iTCP:9000 -sTCP:LISTEN
> 
> COMMAND   PID   USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
> 
> main    52821 harsha    4u  IPv4 0x56757194c2040e1      0t0  TCP *:cslistener (LISTEN)
> 
> minio   52822 harsha    4u  IPv6 0x56757194c40d1f1      0t0  TCP *:cslistener (LISTEN)
> working on a fix where during the start, minio makes sure that 9000(or the requested port) is not used on any of the ipv6 or ipv4 addresses.

Ah you are right!

**Comment by harshavardhana** [comment]
> The problem is not because of SO_REUSEPORT but because on macos minio is listening on ipv6 address (whereas it fails on linux saying port is already in use)
> 
> $ sudo lsof -iTCP:9000 -sTCP:LISTEN
> 
> COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
> 
> main 52821 harsha 4u IPv4 0x56757194c2040e1 0t0 TCP *:cslistener (LISTEN)
> 
> minio 52822 harsha 4u IPv6 0x56757194c40d1f1 0t0 TCP *:cslistener (LISTEN)
> working on a fix where during the start, minio makes sure that 9000(or the requested port) is not used on any of the ipv6 or ipv4 addresses.
> Ah you are right!

it also means that node doesn't do ipv6 by default, whereas golang http client defaults to ipv6.

**Comment by harshavardhana** [comment]
Minio current master is fixed, new release will have the aforementioned fixes @krishnasrinivas
