### ISSUE TITLE
api: bucketExists callback error should give clarity

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio-js#440]
s3Client.bucketExists('mybucket', function(e) {
  if (e) return console.log('Bucket does not exist.')
  console.log('Bucket exists.')
})

here error is not able to differentiate between actual error and bucket not existing on S3.

**Comment by harshavardhana** [comment]
what is pending on this one @krishnasrinivas ?

**Comment by krishnasrinivas** [comment]
@harshavardhana will fix soon

**Comment by krishnasrinivas** [comment]
err.code already has the needed info:
```
krishna@escape:~/dev$ node bucket-exists.js
{ [S3Error: The specified bucket does not exist]
  code: 'NoSuchBucket',
  bucketname: 'krisuploadd',
  requestid: '5EAD2E5FC3CD2F02',
  hostid: '6xFaDyWWaJI9iuw/MhWjv/hZFm4jwpHI5ubOKPwWWIaf12sD1kddxYG8OL6uD2AEkSGXNMeskJ8=',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null }
krishna@escape:~/dev$ 
```

documentation needs to be updated
