### ISSUE TITLE
api: Add GetBucketPolicy and SetBucketPolicy

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#445]
For reference implementation look at - github.com/minio/minio-go

**Comment by harshavardhana** [comment]
Assigned to // cc @vadmeste

**Comment by brendanashworth** [comment]
Ref: https://github.com/minio/minio-js/pull/485 adds `GetBucketPolicy`, no `SetBucketPolicy` as of yet

**Comment by brendanashworth** [comment]
This has been fixed in https://github.com/minio/minio-js/commit/237c1a8d180f5d569f6fd20caf7c2537920e7636.
