### ISSUE TITLE
putObject request resource leak

### ISSUE THREAD

**Issue by neomantra** [minio/minio-js#449]
I was using minio-js in a populator script performing many `putObject` calls. I found that the script never exited.  I wrapped my script with [why-is-node-running](https://github.com/mafintosh/why-is-node-running) and the culprit seems to be something with `http.request`.

I could reproduce by simply running the [minio-js put-object sample](https://github.com/minio/minio-js/blob/master/examples/put-object.js). Prepare a minio test server and create the bucket `my-bucketname`; this requires successful requests to reproduce. For my convenience, I commented out the "ogg" putObject, but left the rest.  Run the example and it will print the `Successfully ...` messages, but it won't exit. 

Wrap it in [why-is-node-running](https://github.com/mafintosh/why-is-node-running) and you will see this in the output for each `putObject`:
```
# TCP
/Users/anon/projects/minio-js/dist/main/minio.js:430 - var req = _this2.transport.request(reqOptions, function (response) {
/Users/anon/projects/minio-js/dist/main/minio.js:453 - if (region) return _makeRequest(null, region);
/Users/anon/projects/minio-js/dist/main/minio.js:384 - this.makeRequestStream(options, stream, sha256sum, statusCode, region, cb);
```

If you run `lsof -p [pid]` on the program, you will see the TCP file descriptors are still lingering. [I had thousands with my script.]

This is using the latest minio-js (554f5bb) and node 6.2.

**Comment by krishnasrinivas** [comment]
@neomantra thanks for reporting. We will fix this.
