### ISSUE TITLE
Example update: presigned post policy

### ISSUE THREAD

**Issue by koolhead17** [minio/minio-js#457]
We need to add/implement API example in presigned post policy to accept 'curl' command. It currently requires web  browser.

**Comment by krishnasrinivas** [comment]
@koolhead17 following code is a better way to demo presignedPostPolicy than `curl` hence kept that way.

```
minioClient.presignedPostPolicy(policy, function(err, postURL, formData) {
  if (err) return console.log(err)

  var req = superagent.post(postURL)
  _.each(formData, function(value, key) {
    req.field(key, value)
  })

  // file contents.
  req.attach('file', '/path/to/hello.txt', 'hello.txt')

  req.end(function(err, res) {
    if (err) {
      return console.log(err.toString())
    }
    console.log('Upload successful.')
  })
})
```

Though example wise other libs use curl, this code directly demonstrates how JS developers can construct POST form using the POST policy and hence more readily consumable.

**Comment by koolhead17** [comment]
@krishnasrinivas In that case, i should close this 👍
