### ISSUE TITLE
docs: API.md is not consistent with mentioning function signatures

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#464]
Missing function signature. 

https://github.com/minio/minio-js/blob/master/API.md#presignedPostPolicy

v/s

Has function signature

https://github.com/minio/minio-js/blob/master/API.md#presignedputobjectbucketname-objectname-expiry

**Comment by harshavardhana** [comment]
This needs to be fixed on docs.minio.io as well.

**Comment by krishnasrinivas** [comment]
@harshavardhana this is fixed can you check?

**Comment by harshavardhana** [comment]
This is closed.
