### ISSUE TITLE
Use querystring and url modules

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio-js#490]
Explore querystring and url modules instead of constructing things by hand.

signing can be like:

```
authHeader = signV4(method, url, headers, accessKey, secretKey, region)
```

**Comment by deekoder** [comment]
We have not had the cycles to fix this issue. This is also a great item for community contribution, if anyone wants to take it up.

**Comment by deekoder** [comment]
We will close this issue and reopen when we have the cycles to fix it.
