### ISSUE TITLE
api: Add GetBucketNotification, SetBucketNotification and RemoveAllBucketNotification

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#492]
Additionally also implement listen bucket notification minio extended API.

**Comment by brendanashworth** [comment]
Part of this API was added in https://github.com/minio/minio-js/commit/7c46409c0da3f8756037af69bf97827983fd1a78, so I'll be renaming `deleteBucketNotification` to `removeAllBucketNotification` and then add `listenBucketNotification`.

**Comment by brendanashworth** [comment]
This can be closed, I think.
