### ISSUE TITLE
Yank 2.0.2

### ISSUE THREAD

**Issue by passcod** [minio/minio-js#502]
You pushed a breaking change on a patch version bump, which naturally broke everything. Could you yank version 2.0.2 or re-release a 2.0.3 without the breaking change so it doesn't break everything?

**Comment by harshavardhana** [comment]
> You pushed a breaking change on a patch version bump, which naturally broke everything. Could you yank version 2.0.2 or re-release a 2.0.3 without the breaking change so it doesn't break everything?

We just made 3.0.0 for this reason can you migrate to that?

**Comment by passcod** [comment]
You should still yank or correct on the 2.0.x release branch because with
caret requirements anyone getting something depending on `^2.0.0` or
`^2.0.1` will get 2.0.2 which has the breaking change. It does not matter
whether *I* can upgrade to 3.0.0. There are versions of the library
depending on `^2` in places I cannot upgrade easily, or at all.

**Comment by harshavardhana** [comment]
> You should still yank or correct on the 2.0.x release branch because with
> caret requirements anyone getting something depending on `^2.0.0` or
> `^2.0.1` will get 2.0.2 which has the breaking change. It does not matter
> whether *I* can upgrade to 3.0.0. There are versions of the library
> depending on `^2` in places I cannot upgrade easily, or at all.

I can't yank it since its been more than 24hrs npm doesn't allow it, its been deprecated btw with a message to indicate the issue.

**Comment by harshavardhana** [comment]
> I can't yank it since its been more than 24hrs npm doesn't allow it, its been deprecated btw with a message to indicate the issue.

Thanks for letting us know it was our mistake.

**Comment by krishnasrinivas** [comment]
@harshavardhana if we make a npm release 2.0.3 with the same code as 2.0.1, it will mitigate the problem. i.e doing `npm update/install` will pickup 2.0.3 instead of 2.0.2

**Comment by harshavardhana** [comment]
> @harshavardhana if we make a npm release 2.0.3 with the same code as 2.0.1, it will mitigate the problem. i.e doing npm update/install will pickup 2.0.3 instead of 2.0.2

Let me make that..

**Comment by harshavardhana** [comment]
You should be able to use '2.0.3' now @passcod - @krishnasrinivas can you validate on your end.

**Comment by krishnasrinivas** [comment]
installs 2.0.3 now:
```
krishna@escape:/tmp$ npm install  parse-server-s3like-adapter
parse-server-s3like-adapter@2.0.1 node_modules/parse-server-s3like-adapter
├── url-join@1.1.0
├── thenify-all@1.6.0 (thenify@3.2.0)
└── minio@2.0.3 (async@1.5.2, xml@1.0.1, es6-error@2.1.1, mkdirp@0.5.1, through2@0.6.5, concat-stream@1.5.2, block-stream2@1.1.0, source-map-support@0.2.10, moment@2.15.1, lodash@3.10.1, xml2js@0.4.17)
krishna@escape:/tmp$
```

**Comment by passcod** [comment]
Thank you!
