### ISSUE TITLE
Issues in JS example on https://docs.minio.io/docs/javascript-client-quickstart-guide

### ISSUE THREAD

**Issue by alexmkdn** [minio/minio-js#503]
Hello I tried to copy-paste examples, but got runtime errors. 
To solve the problem I used "var minioClient = **new Minio**" instead of "var minioClient = new Minio.Client".

**Comment by harshavardhana** [comment]
> Hello I tried to copy-paste examples, but got runtime errors. 
> To solve the problem I used "var minioClient = new Minio" instead of "var minioClient = new Minio.Client".

All the examples and quickstart points to 'new Minio.Client'  we have to two releases 3.0.x and 2.0.x they both are incompatible. 

Let me know if you still have issues..

**Comment by harshavardhana** [comment]
Closing @alexmkdn - please re-open if you see issues with the updated documentation.
