### ISSUE TITLE
Make minio client usable in a browser

### ISSUE THREAD

**Issue by naftalivanderloon** [minio/minio-js#512]
Because of the use of nodejs specific libraries like fs and buffer, the client can't be used in browser javascript apps made with ie. angular.
Would be great to have a (stripped down) version that works in a browser

**Comment by krishnasrinivas** [comment]
@naftalivanderloon 
if you type `gulp` in the minio-js directory it produces `dist/main/minio-browser.js`
You can use it in browser like this: https://github.com/minio/minio-js/blob/master/examples/get-object.html

BTW, you don't want to use presigned URLs for accessing objects from browser?

**Comment by harshavardhana** [comment]
minio-js already works in the browser but the recommended approach is to use 'presignedURLs' since access keys on the browser are considered to be a security risk. 

Please re-open if minio-js doesn't work on the browser.
