### ISSUE TITLE
Quick start example throws error - InvalidAccessKeyID

### ISSUE THREAD

**Issue by kmkanagaraj** [minio/minio-js#513]
Quick start example available here https://github.com/minio/minio-js#quick-start-example---file-uploader throws following error 

```
{ [S3Error: The access key ID you provided does not exist in our records.]
  code: 'InvalidAccessKeyID',
  key: '',
  bucketname: '',
  resource: '/europetrip',
  requestid: '3L137',
  hostid: '3L137',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null }

```

**Comment by harshavardhana** [comment]
> Quick start example available here https://github.com/minio/minio-js#quick-start-example---file-uploader throws following error
> 
> { [S3Error: The access key ID you provided does not exist in our records.]
>   code: 'InvalidAccessKeyID',
>   key: '',
>   bucketname: '',
>   resource: '/europetrip',
>   requestid: '3L137',
>   hostid: '3L137',
>   amzRequestid: null,
>   amzId2: null,
>   amzBucketRegion: null }

Looks like 'play' credentials were changed should work fine now.

**Comment by kmkanagaraj** [comment]
Works fine now, thanks
