### ISSUE TITLE
Set default URL for presignedUrl

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-js#514]
In a docker-compose file I build : 

- minio => minio:9000
- api => api:3000
- nginx => 0.0.0.0:80

The nginx redirections : 

* 0.0.0.0/  => minio:9000
* 0.0.0.0/api  => api:3000

## Expected behaviour
When requesting the API for a resource, the API should return a public URL to access to it not the container's address.

## Actual behaviour
The API returns a presigned url built with the docker address and not the public address. If I edit the returned host with the public host the key mismatch and I can't access to the resource.

## Steps to reproduce the behaviour

Run a docker with these containers :

1. A minio container on minio:9000
2. A server API container on api:3000
- Instantiate minio and set the endpoint/port to minio's container.
3. A nginx server on 80 redirecting / to minio and /api to the API

## How I fixed it

To fix this issue I setup my nginx to modify the host : 

```
location / {
    proxy_set_header Host minio:9000;
    proxy_pass        http://minio:9000;
  }
```

And on the API side I rewrite the host before sending the presignedUrl : 
```js
MinioStorage.prototype.getURL = function(bucketName, filename, cb, expiry) {
	expiry = expiry || 3600*24*2; // 2 days
	var self = this;
	this.minioClient.presignedGetObject(bucketName, filename, expiry, function(err, presignedUrl) {
		if(cb) {
			cb(err, {
				container: bucketName,
				filename: filename,
				url: presignedUrl.replace(self.internalURL, self.publicURL)
			});
		}
	});
};
```

## Minio version
RELEASE.2016-09-11T17-42-18Z

### Minio client configuration
I think it could be nice to customize the public url that minio should use to generate presignedUrl directly when a client instantiate the minioClient.

Something like : 

```js
this.minioClient = new Minio({
		endPoint: ...,
		port: ...,
		secure: ...,
		accessKey: ...,
		secretKey: ...,
		publicUrl: 0.0.0.0 /* Here the URL I want to use in presigned url */
});
```

### Docker configuration
Or, add a Environment variable to allow docker to inject to it : PUBLIC_URL

Thank you.

Opened from https://github.com/minio/minio/issues/2848

**Comment by harshavardhana** [comment]
Closing this bug as "won't fix" ... presigned URLs when used with proxy should point to proxy server and let the proxy load balance the requests instead of minio-js attempting to override URLs in this manner.

**Comment by tspoke** [comment]
Yes, of course but how we can say to minio to give a proxy URL instead of a local one ? 
My code transform a local minio URL into a proxy url.

**Comment by harshavardhana** [comment]
> Yes, of course but how we can say to minio to give a proxy URL instead of a local one ? 
> My code transform a local minio URL into a proxy url.

You have to use the proxy URL as part of  'minioClient' basically the endpoint is already the proxy URL.

**Comment by JonasT** [comment]
@harshavardhana it is very uncommon for docker services that they aren't aware of their own publicly reachable URL/host to return proper URLs directly. so since nobody has suggested it yet, I suggest to revisit this based on that fact, if alone that most other containers have such an option and I just spend a while googling around assuming I was blind until I found this here

in addition, this seems like something that wouldn't add much complexity to the server, and it is wasting people's time because everyone needs to invest coding their app/proxy to replace things to give out a proper URL that works

**Comment by terrywbrady** [comment]
I had some success with this issue by adding a hostname alias to my minio container.  I have summarized the approach here: https://stackoverflow.com/a/61214488/3846548

**Comment by christianechevarria** [comment]
> The API returns a presigned url built with the docker address and not the public address. If I edit the returned host with the public host the key mismatch and I can't access to the resource.

I'm basically grappling with this, it's been a big time-sink so far. 

Originally I was getting `signature mismatch` errors due to the host discrepancy on the browser, so I followed the approach outlined by @harshavardhana and set up an NGINX proxy -- I'm now getting a `403 forbidden` with no logging from the MC (MinIO Client) -- maybe I'm not hitting the MinIO service, but I don't think that's the case

Is this still a viable strategy to dealing with this problem?

I'll take any pointers at this point, below is all the relevant stuff in case there's something obvious I'm missing

This is the docker-compose.yaml

```yaml
version: "3.6"
services:
  nuxt:
    build: ./nuxt
    ports:
      - "5000:5000"
    volumes:
      - ./nuxt:/usr/src/app/nuxt
      - /usr/src/app/nuxt/node_modules
    restart: always

  minio:
    build: ./minio
    # Use port 9000 to run the service
    ports:
      - "9000:9000"
    volumes:
      - "minio_data:/data"
    environment:
      MINIO_ACCESS_KEY: "STUFF"
      MINIO_SECRET_KEY: "STUFF"

  # Proxies requests to internal services
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: on-failure

volumes:
  minio_data:
```

The browser code

```javascript
    async uploadImage(file, progress, error, option) {
      // Get a presignedUrl from a `minio-js` powered route
      const res = ...
      
      // Rename url for clarity
      let uploadLink = res.data.MinIOLink.url

      // Replace internal docker url with public url
      uploadLink = uploadLink.replace('minio:9000', 'localhost/minio')

      const uploadRes = await fetch(uploadLink, {
        method: 'PUT',
        body: file,
        headers: {
          'Content-Type': 'image/jpeg',
        },
      })
```

`nginx.conf`


```conf
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 1024;
}

http {
         server {
            listen 80;
            server_name localhost 127.0.0.1;

            location / {
                proxy_pass          http://nuxt:5000;
                proxy_set_header    X-Forwarded-For $remote_addr;
            }

            location /minio {
                # Set Host header to avoid MinIO's signature discrepancy issue
                proxy_set_header    Host minio:9000;
                proxy_pass          http://minio:9000;
            }
        }
}
```

NGINX logging

```bash
2020/08/25 02:30:50 [error] 6#6: *66 readv() failed (104: Connection reset by peer) while reading upstream, client: 172.29.0.1, server: localhost, request: "PUT /minio/7020/filename.jpg?X-Amz-Algo...
```

**Comment by christianechevarria** [comment]
@terrywbrady I saw that you setup up a custom network, when you edit `/etc/hosts` that's the host machine running docker, right?

**Comment by terrywbrady** [comment]
@christianechevarria , that is correct.

**Comment by mumair5393** [comment]
@christianechevarria were you able to resolve 403 Forbidden issue?

**Comment by mihow** [comment]
I have the same issue and it seems like a very common use case: Run MinIO within docker compose, generate presigned URLs from an application within the same compose network, but access the presigned URLs from the web browser on the host machine. 

This is also documented here, but the minio team seems uninterested in providing a solution. 
https://github.com/minio/minio/issues/10222
