### ISSUE TITLE
listenBucketNotification API out of sync with documentation

### ISSUE THREAD

**Issue by jmorrell** [minio/minio-js#528]
When working with version 3.0.0 installed via npm, the actual API for `listenBucketNotification` is out of sync with the documentation as of: https://github.com/minio/minio-js/pull/505 which is not reflected in the published version.

Perhaps this merits publishing a version 3.1.0? I lost a good bit of time trying to understand what was going on and publishing a new version would be a quick fix.

If this is untenable for some reason feel free to close, but thought you should be aware that this could be confusing for users.

**Comment by harshavardhana** [comment]
Published 3.1.0 and docs should reflect the correct API now. Thanks @jmorrell
