### ISSUE TITLE
putObject ignore contentType

### ISSUE THREAD

**Issue by mix5003** [minio/minio-js#530]
putObject always upload as 'application/octet-stream'

for example
```JS
var _100kb = new Buffer(100*1024)
_100kb.fill('a')
minioClient.putObject('data', 'test.png', _100kb, 'image/png', function(err, etag) {})
```
test.png in server is 'application/octet-stream' not 'image/png'

**Comment by harshavardhana** [comment]
Thanks @mix5003 for reporting. We will fix it right away.
