### ISSUE TITLE
upper case in endPoint results in invalid signature, code 403.

### ISSUE THREAD

**Issue by pszabop** [minio/minio-js#542]
If you have an upper case character in an endpoint it results in invalid signature response from minio when using pre-signed URLs.

Somewhere in the pipeline the endpoint must get coerced to mono-cased when generating a or validating a signature, but the URL is not coerced and thus they don't match.  This could be in minio-js, minio server, or superagent.  I can't tell which.

This is mostly a gotcha, not really necessary to fix, but please keep this as a future warning to other users.   If you are in the habit of using camelCase with docker container names it's quite easy to paste a camelCase name into the endPoint specification...

Details at http://stackoverflow.com/questions/42050505/minio-presigned-put-with-superagent-results-in-a-403

**Comment by krishnasrinivas** [comment]
@pszabop thanks, we'll check.

**Comment by krishnasrinivas** [comment]
fixed by 18022f0b895e869ebdfc358a488f4ee30db32cf5
