### ISSUE TITLE
Add the ability to add additional upload parameters to a putObject and fPutObject

### ISSUE THREAD

**Issue by PsyTae** [minio/minio-js#555]
Our company uses extra parameters when uploading files to the s3 such as the `Metadata: { someKey : 'STRING_VALUE' }` object. It would be nice to be able to add additional parameters as AWS-SDK does. as referenced [Here](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property).

**Comment by krishnasrinivas** [comment]
ETA 4/12

**Comment by PsyTae** [comment]
How is this going?

**Comment by deekoder** [comment]
We dont have the cycles to work on this @PsyTae. Certainly the community can help out if this feature is really needed. I will close for now and we can reopen it when someone is working on it.
