### ISSUE TITLE
Question: Are there some ES6 or React examples to use minio-js?

### ISSUE THREAD

**Issue by christtrc** [minio/minio-js#556]
I want to use minio-js in a react project.  Any help?

**Comment by krishnasrinivas** [comment]
@christtrc what do you want to achieve? because minio-js is not tied to react-js. It is mostly used on the server side to interact with S3 compatible storage.

**Comment by krishnasrinivas** [comment]
@christtrc have a look at a sample project on how minio-js and S3 can be used here: https://docs.minio.io/docs/javascript-shopping-app

In case you have questions, you can re-open the issue. Closing it for now.
