### ISSUE TITLE
listObjects stream

### ISSUE THREAD

**Issue by luhkevin** [minio/minio-js#561]
Your `listObjects` function returns stream chunks that look like this:

```
{ name: 'foobar`,
  lastModified: 2017-03-15T06:21:24.000Z,
  etag: '1351a5430b213abf98d1c6f487e42f7f',
  size: 25 }
```

This is not a valid JSON string. `JSON.parse()` returns a syntax error on this. 
I realize having the stream output valid JSON is not a requirement, but it would be much more convenient if it did. 

How are we supposed to use the output of `listObjects` if it doesn't return something "nice"?

**Comment by harshavardhana** [comment]
> How are we supposed to use the output of listObjects if it doesn't return something "nice"?

It is upto you to just JSON.stringify() on the received value, i don't see why would listObjects() enforce a data encoding format. JavaScript object is native and is free of format encoding and enforcement of any time. So as a user you are free to convert them into any format you feel like could be XML, JSON, YAML. etc

**Comment by luhkevin** [comment]
Gotcha, this was my bad! I did not realize that `JSON.stringify` worked here.
