### ISSUE TITLE
typescript definitions

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio-js#567]
Could also be an opportunity to re-write it with typescript instead of using babel.
Rewriting is not really rewriting, typescript superset of es6, changing from babel to typescript and renaming .js to .ts should be 99.99% ok

**Comment by deekoder** [comment]
Needs to be discussed.

**Comment by masaeedu** [comment]
@deekoder What is this blocked by?

**Comment by harshavardhana** [comment]
For the time being we planned to not implement this @masaeedu . Any counter requirements from community would be helpful to conclude the viability of implementing this.

**Comment by masaeedu** [comment]
@harshavardhana TypeScript definitions serve as documentation for your API, which makes the API easier to discover and prevents incorrect usage. For editors like VS Code, this benefit extends to users that are not using TypeScript at all.

Not familiar with the "counter requirements" term, hopefully this is what you were looking for.

**Comment by harshavardhana** [comment]
> @harshavardhana TypeScript definitions serve as documentation for your API, which makes the API easier to discover and prevents incorrect usage. For editors like VS Code, this benefit extends to users that are not using TypeScript at all.

This is not the original bug the original bug is about re-writing this project in typescript which was decided not to.  Now about the API docs https://docs.minio.io/docs/javascript-client-api-reference - it is quite beneficial to have the types indicated in your favorite editor as well we will see if there are tools which can do this for us apart from rewriting the entire project in typescript.

**Comment by masaeedu** [comment]
The title of the issue is "typescript definitions", which can be accomplished without rewriting the entire project. You just need to export an `index.d.ts` file that describes your module's API. Can't speak for @dcharbonnier, but I think the "rewrite in TypeScript" angle was meant to be an idea for going further than simply writing definitions.

**Comment by harshavardhana** [comment]
Then it makes sense to do it we will discuss more internally.  Perhaps you can open a new bug in this regard will help us to triage it properly ?
