### ISSUE TITLE
Implement promises / generators

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio-js#568]
this is now standard, we should be able to do 
```javascript
try {
  let url = await client.presignedPutObject("mybucket", "hello.txt", 1*DAY);
} catch(e) {
  console.log("F***");
  throw e;
}
```

**Comment by deekoder** [comment]
ETA: 2017-07-07 12:00

**Comment by brendanashworth** [comment]
@dcharbonnier there is now a promise-based API as of https://github.com/minio/minio-js/pull/605.

**Comment by harshavardhana** [comment]
> @dcharbonnier there is now a promise-based API as of #605.

Closing this as fixed @dcharbonnier  . Please re-open if you have any problems.
