### ISSUE TITLE
make presigned*Objects synchronous

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio-js#569]
it would be nice to to have an other method with the region parameter that make this synchronous.
if should be enough to split the two parts of your method

**Comment by harshavardhana** [comment]
> it would be nice to to have an other method with the region parameter that make this synchronous.
> if should be enough to split the two parts of your method

why synchronous? you just want to avoid one getBucketLocation() call ? - on a long living program if your buckets are same this only a one time activity. 

But what we can do is instead provide is enhance the constructor which takes region parameter which is defaulted for all buckets, that way you avoid getBucketLocation() if you are hitting the same region all the time. 

https://godoc.org/github.com/minio/minio-go#NewWithRegion

**Comment by dcharbonnier** [comment]
the problem is that you have a callback all the time so you need to design your call has asynchronous but the only "read" asynchronous call is the first one (and I can't imagine a case on which you don't know the region), all the other case you call the callback on the same loop.
I'm not saying that this possibility should not be removed but a one step method has use cases (I don't want to serialize objects asynchronously if I don't need) and cost nothing on development, it will just make the existing code cleaner.

**Comment by krishnasrinivas** [comment]
@dcharbonnier if we return promises if callback was not provided it would have the desired behavior of synchronous code flow.

**Comment by dcharbonnier** [comment]
The promises are just a different way to write asynchronous code but it does not change the distinction between synchronous and asynchronous code.

**Comment by deekoder** [comment]
Pending discussion in the team.

**Comment by beaulac** [comment]
The specific use-case I'm encountering issues with involves using a virtual getter in Mongoose to automatically populate signed URLs. Unfortunately these getters cannot be async 😭

It would really be helpful to have an exposed synchronous method that allows providing `region` as an argument. The async method would just have to call this one in the `getBucketRegion` callback – this shouldn't have any impact on existing usage / backward compatibility.

**Comment by dcharbonnier** [comment]
Here is a "solution/hack" I'm using since 4 years @beaulac 

```
import signing = require("minio/dist/main/signing");
public presign(
    method: "GET" | "PUT",
    path: string,
    expire: number = 7 * DAY,
    region: string = "us-east-1"
  ): string {
    path = path.replace(/^\//, "");
    const bucketName = path.substr(0, path.indexOf("/"));
    const objectName = path.substr(path.indexOf("/") + 1);
    const reqOptions = this.client.getRequestOptions({
      method,
      region,
      bucketName,
      objectName
    });

    return signing.presignSignatureV4(
      reqOptions,
      this.client.accessKey,
      this.client.secretKey,
      region,
      new Date(),
      expire
    );
  }
```
