### ISSUE TITLE
Remove the dependency on moment library

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio-js#570]
big nice lib but also a big dependency and a huge performance issue
there is few operations on the dates that could be separated on a custom class to keep the rest of the code nice and testable
https://jsperf.com/m9871/1

**Comment by brendanashworth** [comment]
@dcharbonnier do you have a specific use case where you're spending much time in the moment library? There might be alternatives which are 3x faster, but if [each call](https://github.com/minio/minio-js/blob/8c0ca7c6c8caf6a7bfba2d5bd425331a9909149b/src/main/minio.js#L377) is a precursor to an HTTP request, it'll be dwarfed by any network latency, or just the HTTP library.

**Comment by dcharbonnier** [comment]
it's not 3x faster, moment is 10 times slower in this case. Create 1k public urls and you will see the difference. Anyway there is no excuse for using moment in a project like this one.

**Comment by deekoder** [comment]
We will address this @dcharbonnier
