### ISSUE TITLE
Get a permanent URL for object

### ISSUE THREAD

**Issue by sidhantpanda** [minio/minio-js#588]
Hey, there is provision for getting a preSignedUrl but we need to supply an expiry time. 

Is it possible to get a permanent link to the object, so that the url can be saved in the db upon completion of put object request? How to correctly set the bucket policy for this, as the policies listed are not the same as the policies in S3?

**Comment by krishnasrinivas** [comment]
@sidhantpanda 

There can't be a permanent presigned URL.

What you can do instead is, create objects whose names are:

public/obj1
public/obj2
public/obj3
public/obj4
public/obj5

And make the prefix `public/` publicly accessible using this command:
`mc policy download myminio/testbucket/public/`

more about mc: https://github.com/minio/mc

**Comment by sidhantpanda** [comment]
@krishnasrinivas is there a way to have URLs to public objects without making an API call to Minio? I want to render pages with images and videos served directly from the Minio server.

**Comment by harshavardhana** [comment]
> @krishnasrinivas is there a way to have URLs to public objects without making an API call to Minio? I want to render pages with images and videos served directly from the Minio server.

To list objects one needs to make an API call you can use following CLI to get the list as well alternatively. 

```
mc policy links play/testbucket --recursive 
https://play.minio.io:9000/testbucket/0001-dsync.patch
https://play.minio.io:9000/testbucket/filename.txt
https://play.minio.io:9000/testbucket/mc
https://play.minio.io:9000/testbucket/my-objectname
https://play.minio.io:9000/testbucket/test1
https://play.minio.io:9000/testbucket/test1.txt
https://play.minio.io:9000/testbucket/test2.txt
https://play.minio.io:9000/testbucket/1/ldap/client.go
https://play.minio.io:9000/testbucket/1/ldap/example.go
https://play.minio.io:9000/testbucket/accounts/1.original.jpg
https://play.minio.io:9000/testbucket/accounts/2.original.jpg
https://play.minio.io:9000/testbucket/accounts/c4a3ec89-3adf-40dc-822f-2d5ca8e22e32.original.jpg
https://play.minio.io:9000/testbucket/documents/1_files/issue
https://play.minio.io:9000/testbucket/documents/2_files/issue
https://play.minio.io:9000/testbucket/resumes/4.large.png
https://play.minio.io:9000/testbucket/resumes/4.original.pdf
https://play.minio.io:9000/testbucket/resumes/4.thumb.png
```

**Comment by sidhantpanda** [comment]
when I run `mc policy links my_bucket/public`, I get the following error:
```mc: <ERROR> Unable to list policies of a non S3 url `my_bucket/public`. `ListBucketPolicies` is not supported for `filesystem`.```

Are links only supported for S3?

**Comment by krishnasrinivas** [comment]
> @krishnasrinivas is there a way to have URLs to public objects without making an API call to Minio? I want to render pages with images and videos served directly from the Minio server.

Yes, you can serve images/videos directly from Minio server to web-browser without authentication if you set the the policy on the bucket as "download"

`mc policy download myminio/testbucket/`

more about mc: https://github.com/minio/mc

**Comment by sidhantpanda** [comment]
Hi @krishnasrinivas,
I have to do this every time I put an object. Is there no simple way of putting an object publicly?

**Comment by sidhantpanda** [comment]
Nvm, my bad, it working now!

**Comment by aprilandjan** [comment]
After set the policy of specific bucket to `download` in minio server, we can  get the resource public url as follow: 

```javascript:
var publicUrl = minioClient.protocol + '//' + minioClient.host + ':' + minioClient.port + '/' + minioBucket + '/' + obj.name
```

**Comment by TAnas0** [comment]
@harshavardhana
I have files successfully stored in Minio. I can list the links to different objects using the command you `provided:`mc policy links myminio/mybucket --recursive
I have my policies right for the different object and I can access them anonymously.

Is there a way I can get the same results using Python Client API?

In fact what interests me the most is the `https://play.minio.io:9000/` since I can append to it the rest of the link. Is that address fix? Is it configurable? etc
Thanks in advance

**Comment by harshavardhana** [comment]
You have to construct the url yourself. You know endpoint, bucket and you have object name.

**Comment by TAnas0** [comment]
@harshavardhana
While debugging, the minioClient in question has only an attribute `_endpoint_url` which is equal to `http://localhost:9000`
Using the command:
> ./mc policy links myminio/mediabucket --recursive
`http://172.19.0.3:9000/mediabucket/pexels-photo-620332X.jpeg`
`http://172.19.0.3:9000/mediabucket/user159/email/pexels-photo-620332XX.jpeg`
`http://172.19.0.3:9000/mediabucket/pexels-photo-620332.jpeg`

How can I retrieve this endpoint: `http://172.19.0.3:9000`?
I know it is configured in config.json but I don't know what the best approach is, since I don't know if it changes or not, and how would that affect my app once I try to deploy it.

**Comment by harshavardhana** [comment]
Please come to slack.minio.io for discussion like these, we can avoid discussing here on closed issues or feel free to open a new one under minio-py

**Comment by phuyem** [comment]
These stuff are really useful, but not well documented. The discussion here is confusing but does help at the end. Thanks

**Comment by harshavardhana** [comment]
@phuyem the documentation is not capturing FAQs ATM. We are working on finishing it for further usefulness and clarity.

**Comment by rainbowhat** [comment]
> @harshavardhana
> While debugging, the minioClient in question has only an attribute `_endpoint_url` which is equal to `http://localhost:9000`
> Using the command:
> 
> > ./mc policy links myminio/mediabucket --recursive
> > `http://172.19.0.3:9000/mediabucket/pexels-photo-620332X.jpeg`
> > `http://172.19.0.3:9000/mediabucket/user159/email/pexels-photo-620332XX.jpeg`
> > `http://172.19.0.3:9000/mediabucket/pexels-photo-620332.jpeg`
> 
> How can I retrieve this endpoint: `http://172.19.0.3:9000`?
> I know it is configured in config.json but I don't know what the best approach is, since I don't know if it changes or not, and how would that affect my app once I try to deploy it.

Anyway to hide the port?

**Comment by prabhuSub** [comment]
Hi,
Is there a way to get these links through a Python API call?
Suggestions would be much appreciated. I know about the **presigned_get_object** method for the client to fetch the link to the file, which is downloadable, but it is not a direct link to the file like an 's3://bucket-name/file.csv' would do, or even the above link examples would do.
How to fetch such links using Python API is my question/concern. Any suggestions would help! Thank you and appreciate your time reading this.

**Comment by Dannybrown2710** [comment]
> > @harshavardhana
> > While debugging, the minioClient in question has only an attribute `_endpoint_url` which is equal to `http://localhost:9000`
> > Using the command:
> > > ./mc policy links myminio/mediabucket --recursive
> > > `http://172.19.0.3:9000/mediabucket/pexels-photo-620332X.jpeg`
> > > `http://172.19.0.3:9000/mediabucket/user159/email/pexels-photo-620332XX.jpeg`
> > > `http://172.19.0.3:9000/mediabucket/pexels-photo-620332.jpeg`
> > 
> > 
> > How can I retrieve this endpoint: `http://172.19.0.3:9000`?
> > I know it is configured in config.json but I don't know what the best approach is, since I don't know if it changes or not, and how would that affect my app once I try to deploy it.
> 
> Anyway to hide the port?

Use Proxy server

**Comment by anirbandas18** [comment]
> > @krishnasrinivas is there a way to have URLs to public objects without making an API call to Minio? I want to render pages with images and videos served directly from the Minio server.
> 
> To list objects one needs to make an API call you can use following CLI to get the list as well alternatively.
> 
> ```
> mc policy links play/testbucket --recursive 
> https://play.minio.io:9000/testbucket/0001-dsync.patch
> https://play.minio.io:9000/testbucket/filename.txt
> https://play.minio.io:9000/testbucket/mc
> https://play.minio.io:9000/testbucket/my-objectname
> https://play.minio.io:9000/testbucket/test1
> https://play.minio.io:9000/testbucket/test1.txt
> https://play.minio.io:9000/testbucket/test2.txt
> https://play.minio.io:9000/testbucket/1/ldap/client.go
> https://play.minio.io:9000/testbucket/1/ldap/example.go
> https://play.minio.io:9000/testbucket/accounts/1.original.jpg
> https://play.minio.io:9000/testbucket/accounts/2.original.jpg
> https://play.minio.io:9000/testbucket/accounts/c4a3ec89-3adf-40dc-822f-2d5ca8e22e32.original.jpg
> https://play.minio.io:9000/testbucket/documents/1_files/issue
> https://play.minio.io:9000/testbucket/documents/2_files/issue
> https://play.minio.io:9000/testbucket/resumes/4.large.png
> https://play.minio.io:9000/testbucket/resumes/4.original.pdf
> https://play.minio.io:9000/testbucket/resumes/4.thumb.png
> ```

What is the equivalent API call to this CLI command that will provide me the same output?

**Comment by anirbandas18** [comment]
> You can use list objects api and presigned get url.
> A sample web implementation can be found in
> https://github.com/prakashsvmx/minio-js-web-browser-example/blob/f0513c63c2d3b51f20467387556ad7c91cd93c78/src/ListObjects.js#L37
> 
> Also you can make the bucket public using policy so you can directly access the objcets

This is useful

**Comment by CanRau** [comment]
Had to use `mc policy set download alias/bucket/`

note the `set` after `policy`

**Comment by prakashsvmx** [comment]
@CanRau  

some built in policies are provided for ease of use and convenience.

Please check 
https://docs.min.io/docs/javascript-client-api-reference#setBucketPolicy

you could export the policy using `mc` and use/modify or create a new policy and apply it as per your requirements.


```
# Set the policy on a bucket
$ mc policy set download local/test-bucket
Access permission for `local/test-bucket` is set to `download`

# get the policy json
$ mc policy get-json local/test-bucket


# Pass this via API
```

**Comment by dijey099** [comment]
For those who want to get permanent url via python, use this code:

`from minio import Minio
from minio.error import S3Error
import urllib3, json


def main():
    # httpClient = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs='path/to/public.crt')    # download certificate from minio server for self-signed

    bucket = "video"
    minio_endpoint = "192.168.xxx.xxx:9000"
    access_key = "xxxXxxx"
    secret_key = "xxxXxxx"
    secure_state = False
    pre_url = "http"   # if secure_state true, use https

    client = Minio(
        minio_endpoint,
        access_key=access_key,
        secret_key=secret_key,
        secure=secure_state,
        # http_client=httpClient    # uncomment if you use SSL
    )

    # client.delete_bucket_policy(bucket)

    # policy = client.get_bucket_policy(bucket)
    # print(policy)

    policy = {
        "Statement": [
            {
                "Action": [
                    "s3:GetBucketLocation",
                    "s3:ListBucket",
                    "s3:ListBucketMultipartUploads"
                ],
                "Effect": "Allow",
                "Principal": {
                    "AWS": "*"
                },
                "Resource": "arn:aws:s3:::" + bucket,
                "Sid": ""
            },
            {
                "Action": [
                    "s3:AbortMultipartUpload",
                    "s3:DeleteObject",
                    "s3:GetObject",
                    "s3:ListMultipartUploadParts",
                    "s3:PutObject"
                ],
                "Effect": "Allow",
                "Principal": {
                    "AWS": "*"
                },
                "Resource": "arn:aws:s3:::" + bucket + "/*",
                "Sid": ""
            }
        ],
        "Version": "2012-10-17"
    }
    client.set_bucket_policy(bucket, json.dumps(policy))

    objects = client.list_objects(bucket, prefix='', recursive=True)
    for obj in objects:
        url = "{}://{}/{}/{}".format(pre_url, minio_endpoint, bucket, obj.object_name)
        print(url)

    # url = client.get_presigned_url("url", bucket, 'nuiraza/nuiraza.mp4')
    # print(url)

if __name__ == "__main__":
    try:
        main()
    except S3Error as exc:
        print("error occurred.", exc)`

**Comment by hiven** [comment]
All my files are public as they are for images etc. Is there no way using the python API just to get the URL of these. Using predesigned URL on public images doesn't make sense in this case and it seems a bit of a round about way to have to construct URL from name, bucket, end point etc without just being able to call something like object_url.

**Comment by prakashsvmx** [comment]
@hiven , If bucket is public the url would be like `http[s]://host[:apiport]/bucket/path/object`.
E.g CDN url, refrence an image in an IMG tag in html
