### ISSUE TITLE
Methods emit 'error' event without proper error handling

### ISSUE THREAD

**Issue by zllovesuki** [minio/minio-js#591]
`putObject` and `listObjects` will emit `error` event if the server drops the connection unexpectedly:

```
Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at TLSSocket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

This error event should be passed to `err` in the callback instead of crashing the process.

**Comment by zllovesuki** [comment]
Upon a little investigation, it seems that `pipesetup()` will pass the `error` events to ["downstream"](https://github.com/minio/minio-js/blob/2a2966e152d744a9c7e01ed47106d328c7944188/src/main/helpers.js#L237).

However, it looks like that in `src/main/minio.js`, some `pipesetup()` invocations do not handle `error` events [example 1](https://github.com/minio/minio-js/blob/f23c59070dc6b7ffc43c8470b950989dacc78ab6/src/main/minio.js#L1162) [example 2](https://github.com/minio/minio-js/blob/f23c59070dc6b7ffc43c8470b950989dacc78ab6/src/main/minio.js#L1275)  [example 3](https://github.com/minio/minio-js/blob/f23c59070dc6b7ffc43c8470b950989dacc78ab6/src/main/minio.js#L1830) 

I might be wrong, but that's my best guess...

**Comment by krishnasrinivas** [comment]
@zllovesuki 
```
    this.makeRequest({method, bucketName, query}, '', 200, '', (e, response) => {
      if (e) return transformer.emit('error', e)
      pipesetup(response, transformer)
    })
```

if response emits an error it will be propogated to transformer, the caller of this function will have to handle the emitted error. Anyhow, unhandled exceptions would crash the server, it wont crash if you dont handle the emitted errors.

Hence we need to see where we are not handling any exceptions.

**Comment by krishnasrinivas** [comment]
@zllovesuki till we figure out you can use this:
https://nodejs.org/api/process.html#process_event_uncaughtexception

this will avoid the crashing of the process.

**Comment by krishnasrinivas** [comment]
@zllovesuki https://github.com/minio/minio-js/pull/592 should fix the problem

**Comment by zllovesuki** [comment]
@krishnasrinivas using `uncaughtException` is not an option for me as my code requires a very strong consistency maintained with minio. 

However, #592 seems to do the trick (not tested, as I use `presignedPutObject` and use third party libs to handle the `.pipe()` instead).
