### ISSUE TITLE
Can we expect minio as bower package ?

### ISSUE THREAD

**Issue by avinashl3175** [minio/minio-js#594]
If we want to integrate minio directly from client side javascript then we don't have any option currently. We need to depend upon APIs services (like nodejs, Java, etc) to access minio. Making an AJAX call and then performing file upload or download, which slow downs the performance.

If we would have minio sdk either as bower or direct as javascript library package, it would be great and easier for a developer for integration; even data transaction would be a way faster.

**Comment by deekoder** [comment]
We have to discuss a bit about this. Will update soon.

**Comment by krishnasrinivas** [comment]
@avinashl3175 you can run `yarn browserify` inside the minio-js source directory to generate `dist/minio-browser-js` you can use this for client side app. But note that we have done just basic testing with minio.

**Comment by runner-mei** [comment]
@krishnasrinivas I run gulp browserify and use it in browser, and require Buffer fail

**Comment by runner-mei** [comment]
I hope set priority to hight.

**Comment by krishnasrinivas** [comment]
@runner-mei can you post your html/js snippet so that I can reproduce the problem here?

**Comment by runner-mei** [comment]
@krishnasrinivas I import minio.js,  change to  minio-browserify.js and ok.

**Comment by krishnasrinivas** [comment]
@runner-mei I tested it this way and it worked fine:

```
<!doctype html>
<html>
  <body>
    <script type="text/javascript" src="minio-browser.js"></script>
    <script>
      var s3Client = new Minio.Client({
      endPoint: 'localhost',
      port: 9000,
      secure: false,
        accessKey: 'SXO8VW2OFKKP2OG7AC85',
        secretKey: 'CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3'
      })

      var size = 0
      // Get a full object.
      s3Client.getObject('test', 'passwd', function(e, dataStream) {
        if (e) {
          return console.log(e)
        }
        dataStream.on('data', function(chunk) {
          size += chunk.length
        })
        dataStream.on('end', function() {
          console.log("End. Total size = " + size)
        })
        dataStream.on('error', function(e) {
          console.log(e)
        })
      })
    </script>
  </body>
</html>

```

If you can provide me a sample code where you see the error then we can fix it.

**Comment by runner-mei** [comment]
@krishnasrinivas My code is wrong.  minio-js is ok in the browser.

**Comment by harshavardhana** [comment]
> @krishnasrinivas My code is wrong. minio-js is ok in the browser.

minio-js works with browser as expected. closing this..
