### ISSUE TITLE
Can add path option?

### ISSUE THREAD

**Issue by runner-mei** [minio/minio-js#596]
Can add path option?
````js
var s3Client = new Minio.Client({
      endPoint: 'localhost',
      port: 9000,
      path: "/minio",
      secure: false,
        accessKey: 'SXO8VW2OFKKP2OG7AC85',
        secretKey: 'CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3'
      })
````

Why need path option?
I run a proxy before minio server
````
browser -->  proxy --> my app
               |
               +------> minio server
````

**Comment by harshavardhana** [comment]
this is incompatible requirement with S3 API why is this needed?

**Comment by runner-mei** [comment]
@harshavardhana I run nginx proxy between browser and minio server. I need dispatch request by url prefix.

like as:
http://xxxx/app     -> my app
http://xxxx/minio  -> minio server

**Comment by krishnasrinivas** [comment]
@runner-mei you can route based on bucket

http://xxxx/mybucket -> minio server

http://xxxx/minio -> minio server will not work as nginx changes the path and causes signature error

**Comment by runner-mei** [comment]
@krishnasrinivas I hope url is http://xxxx/minio/mybucket!

**Comment by krishnasrinivas** [comment]
@runner-mei no, if nginx modifies the URL from  http://xxxx/minio/mybucket ->  http://localhost:9000/mybucket and routes it to minio server then there will be signature error. i.e nginx should not modify the path.

Hence the solution is to no modify the `path` component of the URL, hence it can route http://xxx/mybucket -> http://localhost:9000/mybucket

**Comment by krishnasrinivas** [comment]
Re-open this if you have more questions @runner-mei, closing this now.
