### ISSUE TITLE
I have some problems when I want to use Minio in a Ts project

### ISSUE THREAD

**Issue by oMinGWo** [minio/minio-js#597]
I want to use minio in my ts project.
I didn't find a ts guaid and I can only use js guaid
after i npm install --save minio in my project path, i dont know how to import minio in my project
i tried to use 'var Minio=require('minio')' but my brower told me that can not find minio

so could you please tell me how to import minio or how to use minio in ts file
thank you

update:
I can import minio.js which in /dist/main, but my project can not find the depencies used in minio.js just as fs.js

**Comment by deekoder** [comment]
Will check @oMinGWo and get back to you soon.

**Comment by krishnasrinivas** [comment]
@oMinGWo can you post your TS source? It will help resolve the issue faster

**Comment by oMinGWo** [comment]
Sorry, i can't provide the TS source. The framework we used is angularJS2.0 and what we have achieved is uploading files to aliyun oss. However, our requirement needs us to change the oss server from aliyun to a private server. We choosed minio but our project can't import minio. So...i am here.
Here is our angularjs2.0 seed: https://github.com/mgechev/angular-seed

**Comment by krishnasrinivas** [comment]
@oMinGWo this works:

https://github.com/krishnasrinivas/node-typescript-boilerplate/blob/master/src/main.ts

**Comment by oMinGWo** [comment]
This solution can import minio.js successfully but my browser told me that cannot find the depencies used in minio.js. Here are the screenshot.
![image](https://user-images.githubusercontent.com/7437349/27112407-86dbd630-50e9-11e7-80e0-f8e03ece4cb8.png)

**Comment by krishnasrinivas** [comment]
BTW, for client side apps you should use presigned URLs and not store access/secret keys in the client app.

http://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html http://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html

Any reason you are not using presigned URL method on the client side?

**Comment by oMinGWo** [comment]
I dont think it's about presigined URLs.
When I run 'npm install minio' in an empty file and write a js file. The file can work successful. But when I run 'npm install minio' in my project path. The result is the same -- can not find the js file required in minio.js.

Here are my code.
`import * as Minio from 'minio';`
```
this.minioCliet=new Minio.Client({
          endPoint: 'play.minio.io',
          port: 9000,
          secure: true,
          accessKey: 'Q3AM3UQ867SPQQA43P2F',
          secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
        });
```

Maybe it's about environment but I really don't know why and want to know how to fix it

**Comment by krishnasrinivas** [comment]
https://github.com/krishnasrinivas/angular-seed

You can check https://github.com/krishnasrinivas/angular-seed/blob/master/src/client/app/home/home.component.ts

I added minio-browser.js (which can be found in `node_modules/minio/dist/main/minio-browser.js`) in the 
same directory where home.component.ts is available and it worked.

I was not able to figure out how to import `node_modules/minio/dist/main/minio-browser.js` directly into TS, so I copied it to the source directory and got it working.

note that minio-browser.js is browserified source of minio.

**Comment by oMinGWo** [comment]
@krishnasrinivas hey, have you done some other opertions except moving minio-borwser.js to the same path with the ts file?

**Comment by krishnasrinivas** [comment]
@oMinGWo no, you can git clone and `yarn install` and check that it works

**Comment by oMinGWo** [comment]
@krishnasrinivas it doesn't work because there is another error which is 'unexpected token <'. Do you have another idea about this? It's probably a error about systemjs

**Comment by maxmarkus** [comment]
Adding it to the project like mentioned in seed gitter would work: 
```
let additionalPackages: ExtendPackages[] = [
{
    name: 'minio',
    path: 'node_modules/minio/dist/main/minio.js'
}
```
and importing it like `import * as minio from 'minio'`
Unfortunately there are no official types yet provided ( https://www.npmjs.com/package/@types/minio ) , so you need to create them yourself, inside `tools/manual_typings/project` in order to make typescript compiler aware of minio.

I think you always need the types, even if you copy the files there.

**Comment by oMinGWo** [comment]
@maxmarkus in the addtionalPackages, when I input the path to minio, my browser told me cannot find the js files required in minio.js and when i input minio-browser.js, my browser told me that another error: 'unexpected token <'.
In the angular-seed issues, they thought this is about systemjs version.
I really dont know how to fix this. orz...

**Comment by krishnasrinivas** [comment]
@maxmarkus yes but types file is not mandatory as TS assumes implicit type.

@oMinGWo are you doing `import * as minio from './minio-browser.js'` make sure you are not doing `import * as minio from 'minio-browser.js'`

You would be missing something because https://github.com/krishnasrinivas/angular-seed works fine for me. If you can create a minimal repo where this problem can be reproduced then I can show you the fix.

**Comment by deekoder** [comment]
Hope this works now. If not please reopen this issue @maxmarkus  and @oMinGWo

**Comment by maxmarkus** [comment]
@krishnasrinivas Not fully true, types are only not mandatory unless you enable **--noImplicitAny** flag. Which we have set in order to ensure and enforce type safety.
