### ISSUE TITLE
Choose single linter, make pass, and make stricter

### ISSUE THREAD

**Issue by brendanashworth** [minio/minio-js#604]
Right now there are two linters in the project, jscs and jshint. jshint is configured to be lenient and let anything pass (right now, semicolons are optional and show up sometimes, while two-space indentation is preferred but four-space is allowed, etc). jscs is stricter but doesn't match the current code base and as such fails. The following should happen to fix this:

- [ ] pick either jshint or jscs, and run that on `npm test`
- [ ] select preferred code style for the code base that is stricter
- [ ] adopt changes to code base to follow new code style

**Comment by krishnasrinivas** [comment]
> pick either jshint or jscs, and run that on npm test

can you pick one? mentioning the reasoning behind it?

> select preferred code style for the code base that is stricter

we have tried to follow 2 spaces and no semi-colons

> adopt changes to code base to follow new code style

Can you send a PR fixing it?

**Comment by brendanashworth** [comment]
@krishnasrinivas sure, thanks for the info. I'll take on the issue then and put in these changes soon.
