### ISSUE TITLE
linter should enforce more rules

### ISSUE THREAD

**Issue by brendanashworth** [minio/minio-js#608]
The linter in this repository should enforce more rules to keep the codebase cleaner. All lint issues should error. This includes:

- [ ] `no-var` (https://github.com/minio/minio-js/pull/607#commitcomment-23268896)
- [ ] `prefer-const` (https://github.com/minio/minio-js/pull/607#commitcomment-23268896)
- [ ] `space-before-blocks` (https://github.com/minio/minio-js/pull/607#commitcomment-23269062)
- [ ] `quotes` (prefer 'single')

Also:
- [ ] `examples/`, `gulpfile.js` should be linted

**Comment by deekoder** [comment]
We have not had the cycles to fix this issue. Will close it and reopen it when we are able to. This is also a great item for community contribution, if anyone wants to take it up.
