### ISSUE TITLE
Set Header Cache-Control

### ISSUE THREAD

**Issue by Mike1707** [minio/minio-js#609]
Hey guys,

is there a way to set the Header for Cache-Control while using the presignedPostPolicy-function?

The output in the formData-object after signing should look like: 

`formData['Cache-Control'] = 'public, max-age=31536000'`

If there is actually no possibility to set Cache-Control, it would be very helpful to implement a short function for own headers which should be signed and/or something like setCacheControl(..).

I hope you can help me with my issue. Thanks in advance!
Mike

**Comment by brendanashworth** [comment]
Hi @Mike1707 thanks for opening an issue. Currently there's [no public API](https://github.com/minio/minio-js/blob/ace4c30be9af036c0356d6e050f2132f155d3080/src/main/minio.js#L2048) to do this in minio-js, or in [minio-go](https://godoc.org/github.com/minio/minio-go#PostPolicy) (our reference implementation). Do you have a specific use case that would warrant something like this being added?

p.s. in the meantime, you should be able to do this:
```javascript
var policy = minio.newPostPolicy();

policy.formData['cache-control'] = 'public, max-age=...';

minio.presignedPostPolicy(policy, function() {
  // ...
});
```

**Comment by Mike1707** [comment]
Hi @brendanashworth thanks for your fast reply. Unfortunately, your workaround is not working because I receive from Amazon S3 the following response: 

`
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Extra input fields: cache-control</Message>
`

Maybe I'm doing it wrong:

```
var policy = minioClient.newPostPolicy();
		policy.setBucket(bucketName);
		policy.setKeyStartsWith(filename);
		var expires = new Date();
		expires.setSeconds(12 * 60 * 60);
		policy.setExpires(expires);
		policy.setContentType('image/jpeg');
		policy.setContentLengthRange(1024, 5 * 1024 * 1024);
		policy.formData['cache-control'] = 'public, max-age=31536000';

		minioClient.presignedPostPolicy(policy, function(err, postURL, formData) { 
                     // send postURL and formData to Client-App
                });

```

My use case is that my users load hundreds of thousands of small pictures from my Amazon S3 for their iOS/Android-Ap. Without Cache-Control that would be too much traffic. Therefore, it is necessary for me to enable this feature. 

I hope you have another idea. Thanks,
Mike

**Comment by krishnasrinivas** [comment]
```
var policy = minioClient.newPostPolicy();
		policy.setBucket(bucketName);
		policy.setKeyStartsWith(filename);
		var expires = new Date();
		expires.setSeconds(12 * 60 * 60);
		policy.setExpires(expires);
		policy.setContentType('image/jpeg');
		policy.setContentLengthRange(1024, 5 * 1024 * 1024);
		policy.formData['Cache-Control'] = 'public, max-age=31536000';
                policy.policy.conditions.push(['eq', '$Cache-Control', 'public, max-age=31536000'])

		minioClient.presignedPostPolicy(policy, function(err, postURL, formData) { 
                     // send postURL and formData to Client-App
                });
```

**Comment by Mike1707** [comment]
Hey @krishnasrinivas this works perfectly fine and fits my purpose perfectly. 

Thanks again and I will close this issue.
