### ISSUE TITLE
Make object name optional

### ISSUE THREAD

**Issue by masaeedu** [minio/minio-js#610]
I want to store and retrieve objects based solely on their etag. All associated metadata will be maintained separately. At the moment the only way I can see to do this is to list the bucket every time I need to retrieve an object by etag and pick out its associated key, which I randomly generate while inserting.

It would be nice if the object name could be made an optional part of the API, so that I could simply upload a stream and get back an etag, which I can later use to read the stream.

**Comment by krishnasrinivas** [comment]
@masaeedu Minio is AWS-S3 compatible which does not allow optional object name and GET based on ETag. However what you can do is generate an object name using UUID (to make it unique) when uploading. You can store this in your DB which can be used for downloading.

**Comment by masaeedu** [comment]
@krishnasrinivas This is what I'm already doing, but I have to deal with the additional hassle of listing the bucket to check for collisions with my UUID. If I could treat the etag as the UUID it would make more sense semantically and would be more convenient; duplicate data is never uploaded to the server.

**Comment by krishnasrinivas** [comment]
A random uuid that looks like `8da015f4-6745-4692-8e82-5d75a49d6aab` is as much hash collision resistant as md5. If you want to deduplicate you can compute md5 (or sha) and use it as the object name.

**Comment by masaeedu** [comment]
@krishnasrinivas Yes, but that requires me to pipe the whole stream into a file or something as I compute its hash, then open the file and send that stream alongside the computed hash to minio. Before I was just passing the stream directly to `putObject`.

**Comment by harshavardhana** [comment]
Feel free to close this issue if resolved @masaeedu

**Comment by krishnasrinivas** [comment]
@masaeedu also you should not assume that ETag will always represent MD5, we might change it in future to a randomly generated UUID

**Comment by masaeedu** [comment]
@krishnasrinivas I was assuming it to be unique by content. It wouldn't matter to me what hashing algorithm is used so long as it represents a unique ID for the uploaded content.

**Comment by Clan-Utility** [comment]
> @masaeedu if you don't want to do store it on the client, you can do it on the server like this:
> 
> ```
> [object xyz]
>      |
>      | -> stream to crypto.Hash ------------\
>      |                                { md5 hash ETag }
>      | -> stream to minio.putObject()         \
>                            \                   \
>                        { temp UUID }            \
>                              \                   \
>                               \ -------------> minio.copyObject() --> { your new object }
>                                                    \
>                                                  deleteObject(temp)
> ```
> This uses two objects on the server, but gives you the result. Does this approach work for you?

Why you have {temp UUID} returned from minio.putObject()? According to the doc, minio.putObject() returns etag of the uploaded object.
