### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by masaeedu** [minio/minio-js#611]
Following on from #567, this issue tracks adding TypeScript definitions to describe the implemented JS API. This would involve creating a `.d.ts` file describing the public facing API and submitting it to the DefinitelyTyped repository or adding it to the minio-js module.

**Comment by brendanashworth** [comment]
@masaeedu thanks for opening an issue. After talking with @krishnasrinivas we think we'd want to include it in this repository. Would you be interested in taking this on, or would you defer to someone else?

**Comment by masaeedu** [comment]
@brendanashworth Sure. I've been tackling this by converting all your `*.js` files to `*.ts` files, then going through it to fix all the errors due to missing type annotations; once all type errors are gone I can compile the whole project to generate an `index.d.ts` describing your exported API, and PR this file.

You can follow progress in https://github.com/masaeedu/minio-js, although perhaps it is a good idea to have a PR just to allow you to verify the correctness of the annotations I am adding.

**Comment by deekoder** [comment]
Looking fwd to your pr @masaeedu

**Comment by masaeedu** [comment]
I'm actually finding some bugs as I go through this process: e.g. https://github.com/minio/minio-js/blob/8c0ca7c6c8caf6a7bfba2d5bd425331a9909149b/src/main/minio.js#L663 references `new errors.isValidBucketNameError`, which should probably be `new errors.InvalidBucketNameError`. You folks sure you don't just want to keep the converted TypeScript files?

**Comment by brendanashworth** [comment]
Ah @masaeedu, good catch. There are perks to switching to a typed language 😄 I don't think we have any plans to switch the client to TypeScript right now though, I think we want to keep it in JS for now. Unfortunately our tests aren't very thorough so we miss some things like that. We'd love a PR that fixes it though ❤️

**Comment by harshavardhana** [comment]
@masaeedu would you mind sending a PR and we can take your work from there?

**Comment by dcharbonnier** [comment]
Anytime someone check your code with typescript he discover issues in your code without even writing a test, look like a good argument no ? I think you didn't check typescript enough... it's javascript it's not a weird language like coffeescript. It's **just** type annotations.

**Comment by krishnasrinivas** [comment]
> I think you didn't check typescript enough... it's javascript it's not a weird language like coffeescript. It's just type annotations.

Guilty of not giving a good enough thought for TS. We'll check it.

**Comment by masaeedu** [comment]
@harshavardhana Sorry for not responding earlier, wasn't using the project. I've opened a PR with whatever I had as you requested, hope that is of some minimal use.

**Comment by harshavardhana** [comment]
> @harshavardhana Sorry for not responding earlier, wasn't using the project. I've opened a PR with whatever I had as you requested, hope that is of some minimal use.

No problem @masaeedu - thanks for all the hard work.

**Comment by rightisleft** [comment]
+1 Would love to see this completed

**Comment by barinbritva** [comment]
PR about typings - #669. May be it will be useful.

**Comment by dcharbonnier** [comment]
I think this can be closed, the types are available with @types.
Next step is https://github.com/canalplus/rx-player/blob/master/doc/why_typescript.md

**Comment by krishnasrinivas** [comment]
Thanks @masaeedu @barinbritva @dcharbonnier will close this

@dcharbonnier no plans of rewriting typescript for now. https://reasonml.github.io/ looks interesting.

**Comment by dcharbonnier** [comment]
yes, nice like transpiling golang to javascript or using coffeescript, can't wait for it
