### ISSUE TITLE
fPutObject doesnt work on browser

### ISSUE THREAD

**Issue by nikaelvergara** [minio/minio-js#617]
Following the examples from [here](https://github.com/minio/minio-js/blob/master/examples/get-object.html), i can confirm that minio-browser.js does work.

However when I tried using minio.fPutObject() to upload a document i encountered the following error on the browser.

```
minio-browser.js:1807 Uncaught (in promise) TypeError: _fs2.default.stat is not a function
    at _async2.default.waterfall.size (minio-browser.js:1807)
    at fn (minio-browser.js:7509)
    at minio-browser.js:7976
    at minio-browser.js:6929
    at minio-browser.js:7469
    at minio-browser.js:6930
    at Object.async.waterfall (minio-browser.js:7473)
    at Client.fPutObject (minio-browser.js:1806)
    at (index):23
    at minio-browser.js:1431
```

Just want to confirm if this is intended and fPutObject() or fGetObject() only works when ran via node.

**Comment by harshavardhana** [comment]
fPutObject() requires filesystem access, it will never work in browser. You are supposed to just use putObject() in browser. @nikaelvergara

**Comment by nikaelvergara** [comment]
@harshavardhana understood. thanks.

**Comment by hassanascend** [comment]
> fPutObject

Can you explain it little bit more

**Comment by prakashsvmx** [comment]
fPutObject is designed to stream content from native filesystems . 

e.g if node sdk is in  node environment, the sdk would stream the file contents to minio or s3 compatible object storage if a path/stream is passed.

```javascript
var v_100Mb_file = '/home/prakash/MinIO/TestData/LargeData/100MB.bin'
const v_100Mb_metaData = {
  "test-v":"100MB"
}

s3Client.fPutObject('source-v-bucket', '100MB.bin', v_100Mb_file, v_100Mb_metaData, function(err, res) {
  if (err) return console.log('err:', err)
  console.log('100 MB:', res)
})

```
