### ISSUE TITLE
setBucketPolicy overwrite the previous policy on the bucket

### ISSUE THREAD

**Issue by kishoresanke** [minio/minio-js#618]
* setBucketPolicy overwrite the previous policy on the bucket
* there is no way to append policies to the bucket

**Comment by krishnasrinivas** [comment]
thanks for letting us know of this issue @kishoresanke

**Comment by krishnasrinivas** [comment]
Will not be able to fix this immediately.

**Comment by deekoder** [comment]
We have not had the cycles to fix this issue.   This is also a great item for community contribution, if anyone wants to take it up.

**Comment by deekoder** [comment]
We will close this issue and reactivate it when we have cycles.

**Comment by deekoder** [comment]
This will soon be not an issue. We are changing the API style. PR #663. Closing this as invalid.
