### ISSUE TITLE
options object arg with named properties vs list of unnamed args

### ISSUE THREAD

**Issue by mvayngrib** [minio/minio-js#626]
great job guys! 

This is a matter of preference I guess, but I think the api would be easier to follow if methods accepted options objects with named properties, vs a list of params, e.g.:

```js
client.putObject({
  bucketName,
  objectName,
  body,
  size,
  contentType
})
```

vs 

```js
client.putObject(bucketName, objectName, stream, size, contentType[, callback])
```

this would especially help with cases of optional arguments

**Comment by krishnasrinivas** [comment]
Thanks @mvayngrib for the feedback, we'll discuss this internally.
Mostly we will make it conform to this style: https://github.com/minio/minio-go/issues/747

**Comment by deekoder** [comment]
We have standardized the current api style across several minio sdks, hence we will close this as a won't fix at this time. Please feel free to reactivate if you feel this needs to be fixed.
