### ISSUE TITLE
Remove list 1001 objects test from functional test

### ISSUE THREAD

**Issue by kannappanr** [minio/minio-js#629]
Listobjects test that lists 1001 objects fails in the removeObject part of the code. Removing the test from functional tests, as it needs to be debugged and will block the release of minio-js SDK

**Comment by krishnasrinivas** [comment]
```
  1) functional tests listObjects removeObject(bucketName, objectName, callback)__Remove 1001 objects:
     Error: connect ETIMEDOUT 147.75.201.93:9000
      at Object.exports._errnoException (util.js:907:11)
      at exports._exceptionWithHostPort (util.js:930:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```

This happens only on appveyor, looks very much an appveyor environment problem. Hence @kannappanr is removing the testcase for now.

**Comment by kannappanr** [comment]
Code has been removed and the corresponding PR is https://github.com/minio/minio-js/pull/628

Did not close the issue automatically because of incorrect format to refer this issue.

So, closing it manually
