### ISSUE TITLE
PresignedPutObject test fails on s3 gateway

### ISSUE THREAD

**Issue by poornas** [minio/minio-js#633]
Needs investigation of underlying issue.
In addition, the error log needs to capture the failure.
```json
{
  "name": "minio-js",
  "status": "FAIL",
  "function": "presignedPutObject(bucketName, objectName, expires, cb)",
  "args": "",
  "alert": "",
  "duration": 254,
  "error": ""
}
```

Mint image built from  commit 158108152fc86c52d5543995e0e7634bf1b6da74
Minio version:
Version: 2017-09-25T21:57:17Z
Release-Tag: RELEASE.2017-09-25T21-57-17Z
Commit-ID: d3eb5815d9951fdb82d0134b7651368bab71d72e

**Comment by krishnasrinivas** [comment]
should be fixed by https://github.com/minio/minio/pull/4972

**Comment by kannappanr** [comment]
Should be fixed by minio/minio-go#828

**Comment by kannappanr** [comment]
Closing this as minio/minio-go#828 has merged and vendorized, hence we do not see this issue with the latest build of Minio.

**Comment by harshavardhana** [comment]
Closing as fixed.
