### ISSUE TITLE
 ECONNRESET after X requests

### ISSUE THREAD

**Issue by reptilbud** [minio/minio-js#638]
Hi,

This is probably a bug because I just do:

```javascript
const minio = require('minio');
const client = new minio.Client({
    endPoint: 'endpoint.test.com',
    port: 9002,
    secure: false,
    accessKey: 'my_access_key',
    secretKey: 'my_secret_key',
});
```

Then I create a loop like that:

```javascript
for (let i = 0 ; i < 100 ; i ++) {
    const res = yield client.statObject('user', 'avatar_of_user'); 
    console.log('====> ', res);
}
```
(of course, my "yield" is encapsulated inside a generator function)

When I run this snippet, the first 8 - 9 calls works and then I got the error 

`(node:55702) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: read ECONNRESET
(node:55702) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

If you have any idea or if you know how to avoid this, please let me know.

Cheers !

**Comment by vadmeste** [comment]
Hey @reptilbud,

I think what you need to do is to add a try/catch around  `const res = yield client.statObject('user', 'avatar_of_user'); `

Also can you provide a minimal code that reproduces your error ? I wasn't able to reproduce on my side.

Thanks,

**Comment by reptilbud** [comment]
Hey @vadmeste 

I forgot to say when I created the ticket that I'm using Azure and I run minio in docker.
I don't understand what was happening cause now when I run my snippet all seems to be working fine...
So forgot about it, and I'm sorry if you spent time on it, I will monitor it and get you informed if I succeed to reproduce it again.

Thanks man
