### ISSUE TITLE
statObject hangs process until socket times out

### ISSUE THREAD

**Issue by aliu-d3d** [minio/minio-js#640]
If statObject() is called successfully, the client does not seem to clean up its sockets correctly.  This  leads to the entire process hanging for ~15 seconds until the socket times out.

**Comment by aliu-d3d** [comment]
Workaround for now:
```
    process._getActiveHandles().forEach(handle => {
        if(handle instanceof net.Socket) {
            handle.unref();
        }
    });
```

**Comment by harshavardhana** [comment]
Same issue as #641

**Comment by krishnasrinivas** [comment]
This issue affects all calls for which there is empty response body:
makeBucket
bucketExists
statObject
removeBucket
removeObject
copyObject
setBucketNotification
setBucketPolicy
removeIncompleteUpload

will send in the fix.
