### ISSUE TITLE
Error too many open files (ECONNRESET)

### ISSUE THREAD

**Issue by danielfdsilva** [minio/minio-js#641]
When trying to remove multiple files from minio (circa 10.000) the client throws an error:
```
Unhandled rejection Error: getaddrinfo ENOTFOUND localhost localhost:9000
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26)
```
and the server logs:
```
ERRO[0336] Unable to delete an object rra/tiles/b/14/6472/8685.pbf  cause=open /guts/projects/rra/.resources/test-minio/minio-data/.minio.sys/buckets/rra/tiles/b/14/6472/8685.pbf/fs.json: too many open files in system source=[object-handlers.go:1077:objectAPIHandlers.DeleteObjectHandler()] stack=fs-v1.go:647:fsObjects.DeleteObject <autogenerated>:424:(*fsObjects).DeleteObject object-handlers-common.go:241:deleteObject object-handlers.go:1076:objectAPIHandlers.DeleteObjectHandler api-router.go:62:(objectAPIHandlers).DeleteObjectHandler-fm
```

To delete the files I'm getting the list with `listObjectsV2` (storing them in an array) and then looping over the array and deleting each file with `removeObject`.
This happens both with the docker and the locally installed version of minio. Doesn't seem to happen if I use an S3 bucket.

Any hints?

**Comment by harshavardhana** [comment]
Can you open this issue on minio/minio server?. Looks like this is not a minio-js problem.

**Comment by danielfdsilva** [comment]
done https://github.com/minio/minio/issues/5093

**Comment by danielfdsilva** [comment]
Reopening. After some investigation turns out that the problem is with minio-js
See https://github.com/minio/minio/issues/5093#issuecomment-338829836

**Comment by harshavardhana** [comment]
Thanks @danielfdsilva we will investigate further.

**Comment by harshavardhana** [comment]
you can as a work-around set `s3Client.agent = http.globalAgent` after the constructor initialization.

**Comment by krishnasrinivas** [comment]
fixed by https://github.com/minio/minio-js/pull/646
