### ISSUE TITLE
Error getting large file

### ISSUE THREAD

**Issue by danielfdsilva** [minio/minio-js#642]
Whenever I try to get a large file (in this case 700Mb) the process crashes with the following error:

```
/guts/projects/rra/.resources/test-minio/large-file/index.js:36
    dataStream.on('data', chunk => (data += chunk));
                                            ^
illegal access
```

This is the code I'm using for the upload:
```
'use strict';
var Minio = require('minio');

const s3 = new Minio.Client({
  endPoint: 'localhost',
  port: 9000,
  secure: false,
  accessKey: 'minio',
  secretKey: 'miniostorageengine'
});
const BUCKET = 'rra';

if (process.argv[2] === 'up') {
  s3.fPutObject(BUCKET, 'large-file', './large.osm', 'application/octet-stream', (err, etag) => {
    if (err) return console.log('err', err);
    console.log('large file uploaded');
  });
}

if (process.argv[2] === 'down') {
  s3.getObject(BUCKET, 'large-file', (err, dataStream) => {
    if (err) {
      return console.log('err', err);
    }

    var data = '';
    dataStream.on('data', chunk => (data += chunk));
    dataStream.on('end', () => console.log('done. size:', data.length));
    dataStream.on('error', err => console.log('error', err));
  });
}
```

When I upload the file this error pops up in the minio server:
```
ERRO[0021] unable to remove /guts/projects/rra/.resources/test-minio/large-file/minio-data/.minio.sys/multipart/rra/large-file in /guts/projects/rra/.resources/test-minio/large-file/minio-data/.minio.sys/multipart/rra  cause=file not found source=[fs-v1-multipart.go:672:fsObjects.CompleteMultipartUpload.func1()]
```
Not sure why it tries to remove anything since it's a newly spawned server.

Every time I try to download the file I get this:
```
ERRO[0162] Unable to write to client.                    cause=write tcp 127.0.0.1:9000->127.0.0.1:50011: write: broken pipe source=[object-handlers.go:181:objectAPIHandlers.GetObjectHandler()] stack=fs-v1.go:437:fsObjects.GetObject <autogenerated>:419:(*fsObjects).GetObject object-handlers.go:180:objectAPIHandlers.GetObjectHandler api-router.go:56:(objectAPIHandlers).GetObjectHandler-fm
```

Server version:
```
Version: 2017-09-29T19:16:56Z
Release-Tag: RELEASE.2017-09-29T19-16-56Z
Commit-ID: 60cc6184d253efee4a3120683517028342229e21
```

**Comment by danielfdsilva** [comment]
Any large file will do. You can generate one with `dd if=/dev/zero of=large.gen bs=1024k count=700`

**Comment by vadmeste** [comment]
@danielfdsilva can you paste your nodejs version ?

**Comment by danielfdsilva** [comment]
@vadmeste Was using node `6.11.4`.

With node `7.10.1` or `8.6.0` I get this:
```
/guts/projects/rra/.resources/test-minio/large-file/index.js:36
    dataStream.on('data', chunk => (data += chunk));
                                            ^
RangeError: Invalid string length
    at IncomingMessage.dataStream.on.chunk (/guts/projects/rra/.resources/test-minio/large-file/index.js:36:45)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at IncomingMessage.Readable.push (_stream_readable.js:136:10)
    at HTTPParser.parserOnBody (_http_common.js:123:22)
    at Socket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
```

Errors on the server are the same

**Comment by vadmeste** [comment]
@danielfdsilva the first error `illegal access` looks like an internal bug in V8 of nodejs

@danielfdsilva, `RangeError: Invalid string length` means data reached string size limitation. Even this small js code will trigger the issue:

```js
var i = 0
var buf = ''

for (i = 0; i < 1024*1024*1024; i++) {
    buf += '0123456789';
}
```

**Comment by danielfdsilva** [comment]
@vadmeste That clears the situation. Thanks!

**Comment by vadmeste** [comment]
@danielfdsilva, however the upload works fine for me. Are you able to reproduce it ?

**Comment by danielfdsilva** [comment]
@vadmeste The upload succeeds, I just find weird that an error is displayed.

**Comment by vadmeste** [comment]
> @vadmeste The upload succeeds, I just find weird that an error is displayed.

Are you still able to see the error ? is it reproducible ?

**Comment by vadmeste** [comment]
@deekoder, we probably should close this issue since no answer from the author.

**Comment by danielfdsilva** [comment]
@vadmeste Apologies, this went under the radar.

The error happens every time I upload the file. The upload completes successfully, but this message is printed:
```
ERRO[0021] unable to remove /guts/projects/rra/.resources/test-minio/large-file/minio-data/.minio.sys/multipart/rra/large-file in /guts/projects/rra/.resources/test-minio/large-file/minio-data/.minio.sys/multipart/rra  cause=file not found source=[fs-v1-multipart.go:672:fsObjects.CompleteMultipartUpload.func1()]
```
I was able to see this on another computer as well, but as far as I can tell there are no implications.

**Comment by vadmeste** [comment]
@danielfdsilva, do you have concurrent code that are uploading the same file at the same time ?

I tested your snippet but I wasn't able to reproduce it.

Can you test again with a minimal snippet, independent from your project ?

**Comment by danielfdsilva** [comment]
@vadmeste Just updated to the latest version `RELEASE.2017-10-27T18-59-02Z` and the error doesn't show up anymore. Apparently it was fixed with this release.

Not further actions. Closing.
