### ISSUE TITLE
Accept SSL cert as an argument for minio-js functional test

### ISSUE THREAD

**Issue by ebozduman** [minio/minio-js#647]
minio-js functional test ran against the latest minio release, `minio.RELEASE.2017-11-15T22-20-02Z`, fails with the following error message:
```
{
  "name": "minio-js",
  "function": "\"before all\" hook",
  "duration": 33,
  "status": "FAIL",
  "error": "Error: self signed certificate at Error (native) at TLSSocket.<anonymous> (_tls_wrap.js:1092:38) at TLSSocket._finishInit (_tls_wrap.js:610:8) at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)"
}
```
We need to support self-signed certificates.

**Comment by krishnasrinivas** [comment]
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; can be set instead
https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request
