### ISSUE TITLE
`client.bucketExists` inconsistent behavior 

### ISSUE THREAD

**Issue by ruslan-polutsygan** [minio/minio-js#648]
Hello

If I configure `minio.client` with region - `client.bucketExists` throws error with `e.code === 'NotFound'`.
```
var client = new Minio.Client({
  endPoint: 'host',
  accessKey: 'ACCESSKEYID',
  secretKey: 'SECRETACCESSKEY'
})

client.bucketExists('bucketname', function(e) {
  if (e) {
    return console.log(e.code); /// 'NotFound'
  }
  console.log("True");
})
```

But if I `minio.client` configured without region - behavior is as documented.
```
var client = new Minio.Client({
  endPoint: 'host',
  accessKey: 'ACCESSKEYID',
  secretKey: 'SECRETACCESSKEY'
})

client.bucketExists('bucketname', function(e) {
  if (e) {
    return console.log(e.code); /// 'NoSuchBucket'
  }
  console.log("True")
})
```
Why is that?

**Comment by vadmeste** [comment]
Hey @ruslan-polutsygan, does the bucket exist ?

**Comment by ruslan-polutsygan** [comment]
Hi @vadmeste. No, it does not.

**Comment by ruslan-polutsygan** [comment]
Besides, 
The thing that `client.bucketExists` throws error - doesn't seems expected for me. Its name hints that either true or false has to be return. And situation "bucket doesn't exist" is not exceptional in this case, it is normal for this function. It(situation) is exceptional for any function that relies on bucket existence (put file, for example).
I understand it is not crucial issue, just FYI :)

**Comment by vadmeste** [comment]
@ruslan-polutsygan, true/false is not enough.. because sometimes, we can have some errors like, network problem etc.. so we really need to return an error here.

By the way, are you testing against Minio or AWS S3 ?

**Comment by ruslan-polutsygan** [comment]
Network problem - is exceptional situation for this case. From my perspective, this is case for `new 

I'm testing with local minio server.

**Comment by vadmeste** [comment]
> Network problem - is exceptional situation for this case. From my perspective, this is the case for new Error

New() can be successful, but there is still chance to have network problem when you make the isBucketExist() call.

> I'm testing with local minio server.

Thanks, will test it.. and compare Minio & AWS S3 behavior.. and see what S3 spec tells exactly.

**Comment by ruslan-polutsygan** [comment]
> New() can be successful, but there is still chance to have network problem when you make the isBucketExist() call.

Sorry, I mean that "network problem" is exceptional situation and error should be thrown in this case, but "bucket does not exist" - not exceptional for this method, it is expected. 

> will test it

Thank you.

**Comment by dcharbonnier** [comment]
completely agree with @ruslan-polutsygan if should be possible to write
```
try {
   const exists = await client.bucketExists('bucketname');
   if(!exists) {
       await client.createBucket('bucketname');
   }
} catch(e) {
   console.log("error", e);
}
