### ISSUE TITLE
feature: add s3.upload for compatibility 

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [minio/minio-js#649]
Hi,

I am missing `s3.upload` compat and couldn't find any tickets, where this might have been discussed. `s3.upload` would be crucial for libraries like `multer-s3` to work correctly in streaming scenarios.

The signature is...

```js
var params = {Bucket: 'bucket', Key: 'key', Body: stream};
s3.upload(params, function(err, data) {
  console.log(err, data);
});
```

If this is interesting for you, the maintainers, I can offer implementing it.

Thanks

**Comment by harshavardhana** [comment]
Not sure what is this issue about can you elaborate more ? What is missing and what error do you see ?

**Comment by deekoder** [comment]
ping @eljefedelrodeodeljefe

**Comment by deekoder** [comment]
Closing. Please reopen if you want to discuss further about this error you encounter.
