### ISSUE TITLE
makeBucket function always use us-east-1 region, not custom region setting of server

### ISSUE THREAD

**Issue by tomcsi** [minio/minio-js#651]
The SDK use us-east-1 region in makeBucket function instead of the custom region settings. The minio server always report error: InvalidRegion

Why not using custom region?

https://github.com/minio/minio-js/blob/b2ae5767a893a5c77d9b52288526ae06514a3888/src/main/minio.js#L533

**Comment by kannappanr** [comment]
We allow use of custom region. us-east-1 is used here to calculate the signature. Please refer to the S3 documentation here
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html

**Comment by kannappanr** [comment]
Closing the issue. Please open a new issue, if you have further questions.
