### ISSUE TITLE
Using minio lib for google cloud storage

### ISSUE THREAD

**Issue by ruslan-polutsygan** [minio/minio-js#652]
Hi

[Google Cloud Storage doc for migration from Amazon S3](https://cloud.google.com/storage/docs/migrating#migration-simple). 
It says that in order to switch from Amazon S3 to GCS, only credentials and endpoint have to be changed. 
I did a quick try - no success.

Should this work for `minio-js` lib? 
(I'm aware about Minio GCS Gateway)

Thanks in advance

**Comment by krishnasrinivas** [comment]
no, minio-js uses signature-v4 which is not compatible to GCS's signature-v2.

> (I'm aware about Minio GCS Gateway)

you can use minio-gcs gateway to migrate, yes.

**Comment by ruslan-polutsygan** [comment]
OK. Thanks

**Comment by ruslan-polutsygan** [comment]
Hello.
OK. I've been trying `minio gcs gateway`.

1. When I start it - there is a message " *** Warning: Not Ready for Production *** ". 
2. I can't create bucket via library - I'm getting exception `S3Error: The specified bucket is not valid.` Bucket name is `s-t-abbacacaabbacacaabbacaca`. It is valid name. I can create it from both `http://127.0.0.1:9000` and google cloud web interface. 

Can you advice anything?

**Comment by ruslan-polutsygan** [comment]
Bucket name `s-t-abbacacaabbacacaabbacaca` is valid for minio server itself (when I run minio in server mode).

**Comment by ruslan-polutsygan** [comment]
I make two api calls. First - `minio.bucketExists`, second - `minio.makeBucket`
First call is fine.
Second call xml response (somewhere inside library):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>InvalidBucketName</Code>
    <Message>The specified bucket is not valid.</Message>
    <Key></Key>
    <BucketName></BucketName>
    <Resource>/tabbacacaabbacacaabbacaca</Resource>
    <RequestId>3L137</RequestId>
    <HostId>3L137</HostId>
</Error>
```

Also, I can't see any API calls in Google dashboard. Does this mean that request is rejected by minio gateway?
Am I doing anything wrong?

Thanks

**Comment by harshavardhana** [comment]
Have you configured GCS gateway correctly following the docs here https://github.com/minio/minio/blob/master/docs/gateway/gcs.md?

**Comment by ruslan-polutsygan** [comment]
Yes. When I run `127.0.0.1:9000`, I can see all buckets/files currently exists on storage, able to upload files using gateway web interface, and create buckets as well.

**Comment by harshavardhana** [comment]
You should open now a GitHub issue on minio/minio since this is a server issue and close this.

**Comment by ruslan-polutsygan** [comment]
Thx
Issue is there https://github.com/minio/minio/issues/5261

**Comment by nick4fake** [comment]
For anyone coming here from future: Minio works with GCS (we use it in prod)
