### ISSUE TITLE
presignedPostPolicy is incorrectly promisified

### ISSUE THREAD

**Issue by doomsower** [minio/minio-js#653]
`presignedPostPolicy` callback has 3 arguments, and `promisify` helper function only handles two, therefore when using  promisified version I cannot obtain formData

**Comment by kannappanr** [comment]
`presignedPostPolicy`  callback should have had only 2 arguments. The second one being a list the one we have for [copyObject](https://docs.minio.io/docs/javascript-client-api-reference#copyObject)
Will modify the API to be consistent with copyObject API.
