### ISSUE TITLE
Release 3.2.3 doesn't work in the browser

### ISSUE THREAD

**Issue by gusajz** [minio/minio-js#654]
Hi, 

Release 3.2.3 merged #646 which includes this code:

`response.socket.end()`

The issue is that `socket` property is available in node but not in the browser (see https://github.com/substack/http-browserify)

This results in `Uncaught TypeError: Cannot read property 'end' of undefined` after each call of `putObject` and `getObject`.

Thanks!

**Comment by krishnasrinivas** [comment]
Thanks for letting us know @gusajz we will check what the best way is to fix this.
