### ISSUE TITLE
InvalidEndpointError: Invalid endPoint : apigateway.eu-west-1.amazonaws.com

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio-js#662]
isValidEndpoint is a bit simple....

**Comment by krishnasrinivas** [comment]
Is apigateway.eu-west-1.amazonaws.com an S3 endpoint?

**Comment by kannappanr** [comment]
Closing the issue as apigateway.eu-west-1.amazonaws.com is an Amazon API Gateway endpoint and not an S3 endpoint. Please refer to https://docs.aws.amazon.com/general/latest/gr/rande.html#apigateway_region

**Comment by dcharbonnier** [comment]
sorry, wrong title @kannappanr 
Please read https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region
