### ISSUE TITLE
Any plan to support AWS IAM Roles

### ISSUE THREAD

**Issue by appleboy** [minio/minio-js#665]
This feature has been implemented in Go SDK: https://github.com/minio/minio-go/commit/5d7ee332f62e83d36beba669be671801180abb89

**Comment by kannappanr** [comment]
Answered on slack, adding the response here for reference.

```it is quite easy to do as a simple wrapper outside of minio-js @appleboy  - all you need to do is request `curl http://169.254.169.254/latest/meta-data/iam/security-credentials/<role-name>`
the returned value is in json which can be easily peeked into.```

all you need to do is JSON.parse() the output from a httpGet request on http://169.254.169.254/latest/meta-data/iam/security-credentials/<role-name>

[12:11 AM]
The structure is of this form

[12:11 AM]
```> js = JSON.parse(`{
...   "Code": "Success",
...   "Type": "AWS-HMAC",
...   "AccessKeyId" : "accessKey",
...   "SecretAccessKey" : "secret",
...   "Token" : "token",
...   "Expiration" : "%s",
...   "LastUpdated" : "2009-11-23T0:00:00Z"
... }`)
{ Code: 'Success',
  Type: 'AWS-HMAC',
  AccessKeyId: 'accessKey',
  SecretAccessKey: 'secret',
  Token: 'token',
  Expiration: '%s',
  LastUpdated: '2009-11-23T0:00:00Z' }
> js
{ Code: 'Success',
  Type: 'AWS-HMAC',
  AccessKeyId: 'accessKey',
  SecretAccessKey: 'secret',
  Token: 'token',
  Expiration: '%s',
  LastUpdated: '2009-11-23T0:00:00Z' }
> js.AccessKeyId
'accessKey'```

**Comment by appleboy** [comment]
@kannappanr Thanks.
