### ISSUE TITLE
Please be configurable the region correctly

### ISSUE THREAD

**Issue by sarkiroka** [minio/minio-js#668]
Hi there
I try to use the minioclient with aws, but the region settings in config ("region": "eu-west-1") not worked

```
S3Error: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
```
After that I saw in the source has hard coded "us-east-1" values. But I cannot create pull request because the client code is too complex for me :(

**Comment by kannappanr** [comment]
Can you try the following code with your access and secret key and let us know what you find?
```var Minio = require('minio')

var s3Client = new Minio.Client({
  endPoint: 's3.amazonaws.com',
  accessKey: 'Your Access Key',
  secretKey: 'Your Secret Key'
})
// Create a bucket name my-bucketname.
s3Client.makeBucket('miniojstestbucket', 'eu-west-1', function(e) {
  if (e) {
    return console.log(e)
  }
  console.log("Success")
})```

You can also paste your code that you used to create the issue. Also what version of minio-js are you using? If I understand correctly, you are trying to use minio-js against AWS. In that scenario, I am not sure what you mean by config. Could you please explain?

**Comment by sarkiroka** [comment]
my minio client version is `"minio": "4.0.0",`
my code is super simple, I just want to list all of buckets:
```
minioClient.listBuckets(function (err, buckets) {...}
```
With minio server it works, but with aws it only work when I use the default region. 

I try replace all of "us-east-1" string to my region in minio client lib in node_modules, and this worked for me. But this is not good solution of course :)

**Comment by kannappanr** [comment]
@sarkiroka I tried the following code and I was able to list buckets that were created in the `eu-west-1 ` region.
```
var Minio = require('minio')

var s3Client = new Minio.Client({
  endPoint: 's3.amazonaws.com',
  accessKey: 'Your Access ID',
  secretKey: 'Your Secret Key'
})

s3Client.listBuckets(function(e, buckets) {
  if (e) return console.log(e)
  console.log('buckets :', buckets)
})
```
I also issued `aws cli` command to confirm that my bucket was created in the `eu-west-1` region.

**Comment by krishnasrinivas** [comment]
@sarkiroka you dont have to use region field in options of Minio.Client(options) as we figure out the region automatically. Region is needed only for makeBucket call

**Comment by kannappanr** [comment]
@sarkiroka Closing the issue due to inactivity. Please feel free to re-open the issue if you have further questions on this issue.
