### ISSUE TITLE
make region optional in makeBucket

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio-js#671]
For minio users, the region should not be required
@barinbritva the parameter is optional on the typing it should not https://github.com/minio/minio-js/blob/ccd2c236e65609c2d0f847f93fcef0c3d56ed34d/src/main/minio.js#L497

**Comment by dcharbonnier** [comment]
in TypeScript you could write for a modern api
`async makeBucket(name: string, region?: string) {`

**Comment by barinbritva** [comment]
@dcharbonnier, in doc says: "Default value is us-east-1..." But in code, yes, it is required. I will fix it.

Do you mean something like this?
![screenshot_1](https://user-images.githubusercontent.com/4758362/36422649-074fd332-164e-11e8-905d-f7953bc1bd56.png)
Can you explain what actually you mean?

**Comment by dcharbonnier** [comment]
the comment was for the minio dev, not for the types, I think region should just be a string, there is no way to maintain the list of region and this assume people use S3 and not a compatible service
`makeBucket(name: string, region:string): Promise<void>` should be ok

**Comment by barinbritva** [comment]
As I understand region is required now, but user may pass an empty string.
I run minio server with us-east-1 region and call `makeBucket` like this:
```typescript
minio.makeBucket('test', '', (error: Error|null) => {
    console.log(error);
});
```
No error, bucket was created.
