### ISSUE TITLE
Cannot add user-defined Metadata in "putObject"

### ISSUE THREAD

**Issue by ipeychev** [minio/minio-js#674]
`putObject` function does not support adding user-defined Metadata. This limitation exist only in `minio-js` and `minio-java` SDKs. This issue is a request to make the JS SDK consistent.

Link to the original discussion:
https://minio.slack.com/archives/C3NDUB8UA/p1519981712000257

**Comment by kannappanr** [comment]
@ipeychev Thanks for the filing the issue. We will add this feature.

**Comment by kannappanr** [comment]
Do not have the cycles to look into this right now. Moving it to the future.

**Comment by kannappanr** [comment]
Fixed by #698.
