### ISSUE TITLE
improved doc example:

### ISSUE THREAD

**Issue by cekvenich** [minio/minio-js#688]
Here is an improved example for your docs:

```
function list(key, secret, bucket, folder) {
	console.log(folder)
	const s3Cli  = new Minio.Client({
		endPoint: 's3.amazonaws.com',
		accessKey: key,
		secretKey: secret
	})//
	const objectsStream = s3Cli.listObjectsV2(bucket, folder, true)
	let ret = []
	return new Promise(function(resolve, reject) {
		objectsStream.on('data', function(obj) {
			ret.push(obj)
		})
		objectsStream.on('end', function() {
			resolve(ret)
		 })
		objectsStream.on('error', function(e) {
			console.log(e)
			reject(e)
		})
	})//pro
}//

list('k','s','b','f/')
	.then(function(result){
		console.log(result)
	})
```

hth

**Comment by harshavardhana** [comment]
Thanks Please send PR @cekvenich

**Comment by deekoder** [comment]
ping @cekvenich  are you able to send us a PR?

**Comment by cekvenich** [comment]
Sorry guys, I'd love to, but my time is so tight.

**Comment by deekoder** [comment]
we need to update all our docs with promise support!

**Comment by krishnasrinivas** [comment]
@deekoder https://docs.minio.io/docs/javascript-client-api-reference it's already updated (search for promise)

@cekvenich the example that we have currently https://github.com/minio/minio-js/blob/master/examples/list-objects-v2.js is simpler and easier to understand then the one you have given here. Also it is not taking advantage of the stream and instead accumulating the results in the memory. It is best to document just the primitives and leave it to the developers if they want to build on top of it.

**Comment by kannappanr** [comment]
Closing this issue based on comments by @krishnasrinivas
