### ISSUE TITLE
Cannot force delete bucket through Minio-Js SDK

### ISSUE THREAD

**Issue by builtbyproxy** [minio/minio-js#695]
Currently I can find no way to force delete a bucket with the minio-js sdk.
Obviously i can loop through every object in the bucket and delete them. However this is turning out incredibly costly for a bucket with multiple files.

In [this issue](https://github.com/minio/minio/issues/3624#) @harshavardhana mentions you can force a bucket to delete through the CLI with ```mc rm -r --force```. However since I am making use of the SDK this doesn't help me.

Is there a way I can add a -force parameter to my removeBucket method?

Thankyou

**Comment by kannappanr** [comment]
@builtbyproxy Thanks for filing this issue. I don't think we will be able to provide a way to do that. But I can discuss internally and see if we can add an API similar to https://github.com/minio/minio-go/blob/master/docs/API.md#RemoveObjects .  That way, you can remove multiple objects and the actual delete operation will not be that costly.

**Comment by builtbyproxy** [comment]
Thanks @kannappanr for the help, a force parameter would be absolutely ideal but any solution you could provide beyond a forEach loop would be welcome, i know something like this is possible in an AzureDB query but ill have to get back to you when i find the code that did it. Mainly im looking to minimize the amount of requests I have to make. If i can run a loop on minio that wouldn't be as much as an issue.

Thankyou again for your help
