### ISSUE TITLE
deleteObjects for javascript SDK

### ISSUE THREAD

**Issue by adewergifosse** [minio/minio-js#702]
Hi,

Your documentation does not mention any method to delete multiple objects of one bucket (like AWS, or even minio go: https://docs.minio.io/docs/golang-client-api-reference#RemoveObjects)

Is the documentation incomplete or is it not implemented for the javascript SDK ?

Many thanks

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-js/pull/697 @adewergifosse fixes this.

**Comment by adewergifosse** [comment]
Great thank you, any idea of when this will be released ?

**Comment by kannappanr** [comment]
@adewergifosse We will try to make a release soon, hopefully by end of the week

**Comment by deekoder** [comment]
Closing now. You will have this in the next release.
