### ISSUE TITLE
promisify removeObjects

### ISSUE THREAD

**Issue by loremaps** [minio/minio-js#704]
Great work on #697 and perfect timing :D

I think the promisified version of `removeObjects` is missing. Similar to `removeObject`: https://github.com/minio/minio-js/blob/9cad7e3b31a9c1d7b8d60b12fd9ee7202ccc599d/src/main/minio.js#L2073

It would be also great to update the typescript definitions.

**Comment by jazoom** [comment]
This bit me just now. removeObjects() was released over 2 months ago and your docs suggest the callback is optional. When will a release be cut with this fix?

**Comment by krishnasrinivas** [comment]
@jazoom thanks for letting us know.

**Comment by krishnasrinivas** [comment]
I will re-open this issue for tracking purposes.

**Comment by harshavardhana** [comment]
This is released and fixed..

**Comment by jazoom** [comment]
Thanks for letting me know :-)
