### ISSUE TITLE
Doesn't work with Angular 6

### ISSUE THREAD

**Issue by SPGB** [minio/minio-js#718]
Because crypto, fs, path, and stream are no longer exposed via webpack polyfills, attempting to use this dependency results in multiple
`ERROR in ./node_modules/minio/dist/main/minio.js
Module not found: Error: Can't resolve 'crypto' in '[omitted]/node_modules/minio/dist/main'` errors.

Pulling an answer from https://github.com/angular/angular-cli/issues/1548#issuecomment-386871992 "crypto-browserify can be used in combination with a tsconfig path mapping to map crypto to the package."

**Comment by kannappanr** [comment]
@SPGB Thanks for reaching out. We will take a look and get back to you.

**Comment by kanagarajkm** [comment]
I am looking into this

**Comment by kanagarajkm** [comment]
@SPGB you cannot use `/node_modules/minio/dist/main/minio.js` in browser. you need to use `/node_modules/minio/dist/main/minio-browser.js`. You can run `yarn browserify` inside mino-js source directory to generate `minio-browser.js`

**Comment by kanagarajkm** [comment]
@SPGB can you please check whether the above answer works?

**Comment by kannappanr** [comment]
@SPGB Closing this issue as answered. Please feel free to reach out if you think this does not work for you.

**Comment by athithrao** [comment]
ERROR in ./node_modules/minio/dist/main/minio.js
Module not found: Error: Can't resolve 'crypto' in '/Users/athith/secure_data/angular_dev/secure-data-explorer/node_modules/minio/dist/main'
ERROR in ./node_modules/minio/dist/main/signing.js
Module not found: Error: Can't resolve 'crypto' in '/Users/athith/secure_data/angular_dev/secure-data-explorer/node_modules/minio/dist/main'
ERROR in ./node_modules/minio/dist/main/transformers.js
Module not found: Error: Can't resolve 'crypto' in '/Users/athith/secure_data/angular_dev/secure-data-explorer/node_modules/minio/dist/main'
ERROR in ./node_modules/minio/dist/main/object-uploader.js
Module not found: Error: Can't resolve 'crypto' in '/Users/athith/secure_data/angular_dev/secure-data-explorer/node_modules/minio/dist/main'
ERROR in ./node_modules/minio/dist/main/minio.js
Module not found: Error: Can't resolve 'fs' in '/Users/athith/secure_data/angular_dev/secure-data-explorer/node_modules/minio/dist/main'
ERROR in ./node_modules/mkdirp/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/athith/secure_data/angular_dev/secure-data-explorer/node_modules/mkdirp'
ERROR in ./node_modules/minio/dist/main/minio.js
Module not found: Error: Can't resolve 'http' in '/Users/athith/secure_data/angular_dev/secure-data-explorer/node_modules/minio/dist/main'
ERROR in ./node_modules/minio/dist/main/minio.js
Module not found: Error: Can't resolve 'https' in '/Users/athith/secure_data/angular_dev/secure-data-explorer/node_modules/minio/dist/main'

I am facing the same issue. I am not able to create the mini-browser.js. Could you please share the steps to fix this issue?

**Comment by kanagarajkm** [comment]
> I am facing the same issue. I am not able to create the mini-browser.js. Could you please share the steps to fix this issue?

@athithrao did you run `yarn browserify`? it should generate `dist/main/minio-browser.js` which you can use.

**Comment by athithrao** [comment]
Update - Was able to create mini-browser.js but still not able to build the angular 7 project successfully. Any help would be appreciated.

**Comment by kanagarajkm** [comment]
@athithrao can you provide a sample AngularJS code using this?

**Comment by athithrao** [comment]
I am using Angular 7 and not angularJS. Question - Am I supposed to import Minio or Minio-browser in the following statement?

import * as Minio from "minio"

**Comment by kanagarajkm** [comment]
You cannot import like this since minio-browser.js uses AMD module format. You need to include minio-browser.js directly on the html page.  And in your code
```
var minioClient = new window.Minio.Client({
    ....
})
```

**Comment by athithrao** [comment]
I included the mini-browser.js in a angular 7 project using the following instructions.

https://stackoverflow.com/questions/37081943/angular2-import-external-js-file-into-component

I still get the same errors as mini-browser.js depends on main/minio.js. Any pointers would be appreciated. Thank you.

**Comment by kanagarajkm** [comment]
@athithrao you need to include minio-browser.js in html directly like
`<script src="./somepath/minio-browser.js"></script>`, importing into your angular 7 might not due to incompatible module definitions. Once you have add it to the html, you can access it like `window.Minio.Client`

**Comment by ng-plex** [comment]
I was trying to follow the instruction to add to Angular project but without success:

Step 1. Run `yarn browserify` in the minio-js project.
Step 2. Copy the generated `minio-browser.js`  file from the dist folder to the angular `src/assets/js/minio-browser/minio-browser.js` path.
Step 3. Change the `angular.json` `scripts` to this one:

```js
"scripts": [
    "src/assets/js/minio-browser/minio-browser.js"
],
```

The result is the next error message:

![image](https://user-images.githubusercontent.com/26253716/67075163-ea49d980-f18a-11e9-9c7a-c59aed587c04.png)

**Comment by marcomag89** [comment]
@ng-plex same problem with same procedure. reopen please!
```
ReferenceError: regeneratorRuntime is not defined
```

**Comment by pgsekaran** [comment]
Even i am also getting the same issue pls let me how to use the 'const Minio = require('minio');'

**Comment by prakashsvmx** [comment]
@ng-plex @pgsekaran  
Please try
```
import * as Minio from 'minio'
const S3 = new Minio.Client(...)
```
