### ISSUE TITLE
Error: malformed HTTP request 

### ISSUE THREAD

**Issue by lagorsse** [minio/minio-js#720]
Hi, I have some difficulties with Minio-js, I have setup 4 minio docker with the generated docker compose from the website and it works well I can access the service and create a bucket without issue with browser or from shell with mc.

But with Minio-js  there is some corruption It seems to connect well.

Error: malformed HTTP request ??P?=??p??2??T?+?<?x?????@??Qw?n?/?+?0?,??'g?(k?$??, from 172.19.0.2:9000

????s?2n?/?+?0?,??'g?(k?$??, from 172.19.0.3:9000]?????I@-|?1?F???s
minio3_1      |        remoteAddr=172.19.0.7:42380, localAddr=172.19.0.3:9000
minio3_1      |        1: cmd/logger/logger.go:294:logger.LogIf()
minio3_1      |        2: cmd/http/listener.go:268:http.(*httpListener).start.func2()

I tried with different minio, with and without ssl.

Error returned
 { Error: write EPROTO 139761000773440:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827: at WriteWrap.afterWrite (net.js:868:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write' }

If I use play.minio.io it works well, so there something that is not matching with the docker minio configuration

My docker compose look like this

version: '2'
services:
  minio1:
    image: minio/minio
    volumes:
      - minio_data1:/data/export
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: cloud
      MINIO_SECRET_KEY: key
    command: server http://minio{1...4}/export
  minio2:
    image: minio/minio
    volumes:
      - minio_data2:/data/export
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: cloud
      MINIO_SECRET_KEY: key
    command: server http://minio{1...4}/export
  minio3:
    image: minio/minio
    volumes:
      - minio_data3:/data/export
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: cloud
      MINIO_SECRET_KEY: key
    command: server http://minio{1...4}/export
  minio4:
    image: minio/minio
    volumes:
      - minio_data4:/data/export
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: cloud
      MINIO_SECRET_KEY: key
    command: server http://minio{1...4}/export
volumes:
  minio_data1:
  minio_data2:
  minio_data3:
  minio_data4:

**Comment by vadmeste** [comment]
@lagorsse most probably, minio client in your js code is configured with SSL enabled, just set useSSL to false like the following snippet:

```
var minioClient = new Minio.Client({
    endPoint: 'play.minio.io',
    port: 9000,
    useSSL: true,
    accessKey: 'Q3AM3UQ867SPQQA43P2F',
    secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
});
```

**Comment by lagorsse** [comment]
Misstype issue.
