### ISSUE TITLE
Cannot add user-defined Metadata in "getObject"

### ISSUE THREAD

**Issue by StevenYuysy** [minio/minio-js#723]
I use SSE-C by adding metadata to upload files. But I also need to getObject with SSE-C, can we support by adding metadata options in getObject?

related: https://github.com/minio/minio-js/issues/674

**Comment by kannappanr** [comment]
@StevenYuysy Thanks for filing this issue. The better thing to do here would be to add support for `SSE` encryption instead of handling this using `metadata`. We will try to add support for this in the near future.

**Comment by deekoder** [comment]
Will do after we close some current items on our plate. @StevenYuysy
