### ISSUE TITLE
Support for server-side encryption

### ISSUE THREAD

**Issue by Brunni** [minio/minio-js#726]
As far as I can see, server-side encryption headers are not supported :(

Minio server supports providing the three necessary header fields.

see https://github.com/minio/cookbook/blob/master/docs/how-to-use-minio-server-side-encryption-with-aws-cli.md

**Comment by kannappanr** [comment]
We welcome PRs for this issue. Marking this issue as hacktoberfest.

**Comment by deekoder** [comment]
We will keep this in our future milestone and add support for it when we have some more bandwidth.

**Comment by shernshiou** [comment]
Hi @deekoder, 

Any news on server-side encryption support? If not I will try to make a PR because my project needs this aws-kms feature.

Thanks.

**Comment by kannappanr** [comment]
@shernshiou please go ahead and send a PR

**Comment by mtsyganov** [comment]
In the meanwhile it is possible to do SSE-C but only when you put an object to minio. Unfortunately there is no support yet to use SSE-C by getting objects back from minio.

Here how you can use SSE-C to store objects

`minioClient.putObject('mybucket', 'myobjectname', file.buffer, metaData)`

to use SSE-C you have to provide metaData as follows:
```
const metaData = {
  'X-Amz-Server-Side-Encryption-Customer-Algorithm': 'AES256',
  'X-Amz-Server-Side-Encryption-Customer-Key': 'MzJieXRlc2xvbmdzZWNyZXRrZXltdXN0cHJvdmlkZWQ=',
  'X-Amz-Server-Side-Encryption-Customer-Key-MD5': '7PpPLAK26ONlVUGOWlusfg=='
};
```

I think it is a good solution to give the possibility to call getObject by providing the metaData as parameter similar to the approach with putObject.

**Comment by prakashsvmx** [comment]
@mtsyganov  Please have a look at https://github.com/minio/minio-js/pull/901 for getObject Changes.

**Comment by mtsyganov** [comment]
This PR https://github.com/minio/minio-js/pull/902 adds support for SSE-C for getObject functions. Similar implementation as putObject functions.

**Comment by prakashsvmx** [comment]
This can be tested in latest release.

**Comment by beeing** [comment]
Thanks for this release.

The typescript definitions needs update as well. In https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/minio
