### ISSUE TITLE
Basic JS presigned put with minio server results in 'unknown protocol' error in client

### ISSUE THREAD

**Issue by FranzSkuffka** [minio/minio-js#727]
Hey there - I have now struggled for a fer hours to get minio started running locally:

I am using the following code
```sh
MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=miniostorage minio server minio-data
```

```js
import * as Minio from 'minio'

var client = new Minio.Client({
  endPoint: 'localhost',
  port: 9000,
  useSSL: true,
  accessKey: 'minio',
  secretKey: 'miniostorage'
})

client.presignedPutObject('tunes', 'file.mp3', 60, (err, url) => {
  console.log(err, url)
})
```

Which I modified from https://docs.minio.io/docs/upload-files-from-browser-using-pre-signed-urls.html.
Note that inside the cookbook, the `secure: true` parameter is outdated.

*now the actual error:* The server

minio-js:
```
{ Error: write EPROTO 140532343682880:error:140770FC:SSL routines:SSL
23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_
clnt.c:827:

    at WriteWrap.afterWrite (net.js:868:14) errno: 'EPROTO', code: 'E
PROTO', syscall: 'write' } undefined
```

minio server
```
API: SYSTEM()
Time: 23:48:41 CET 10/30/2018
Error: malformed HTTP request from '127.0.0.1:9000'
       remoteAddr=127.0.0.1:44226, localAddr=127.0.0.1:9000
       1: cmd/logger/logger.go:295:logger.LogIf()
       2: cmd/http/listener.go:274:http.(*httpListener).start.func2()
```

**Comment by kannappanr** [comment]
@FranzSkuffka I think you might not have enabled TLS on the server, can you modify the client code to 

```
import * as Minio from 'minio'

var client = new Minio.Client({
  endPoint: 'localhost',
  port: 9000,
  useSSL: false,
  accessKey: 'minio',
  secretKey: 'miniostorage'
})

client.presignedPutObject('tunes', 'file.mp3', 60, (err, url) => {
  console.log(err, url)
})
```

This should work

**Comment by FranzSkuffka** [comment]
Okey two things to draw from this issue:
- have the backend return a more comprehensive error message
- update the signed url example

**Comment by kannappanr** [comment]
@FranzSkuffka Thanks for the suggestions. I have already sent a PR to update the signed url example. As far as the returning a more comprehensive error message, I will see if the client can display a better and more obvious error message.

**Comment by Piliponful** [comment]
> @FranzSkuffka I think you might not have enabled TLS on the server, can you modify the client code to
> 
> ```
> import * as Minio from 'minio'
> 
> var client = new Minio.Client({
>   endPoint: 'localhost',
>   port: 9000,
>   useSSL: false,
>   accessKey: 'minio',
>   secretKey: 'miniostorage'
> })
> 
> client.presignedPutObject('tunes', 'file.mp3', 60, (err, url) => {
>   console.log(err, url)
> })
> ```
> 
> This should work

Worked for me to, but the error is very very unintuitive, this should be fixed
