### ISSUE TITLE
ES6 modules and minio-js

### ISSUE THREAD

**Issue by djlauk** [minio/minio-js#729]
Hello

I am using minio-js with a Polymer 3 application. Polymer 3 uses npm and ES6 modules, but I could not get minio to work as a ES6 module after running `npm install minio`.

I did manage to manually create (with the browserify gulp task) `minio-browser.js` and I could then import and use that file, but it's not included in the npm package (minio 7.0.1).

The problem is, I would rather not have to hand build the `minio-browser.js` file and distribute it together with my sources; I'd very much like to have it as a dependency (in package.json).

I've been stuck with this for days and only could come up with what feels like a mediocre workaround. If the browserify build is considered the official way to use minio-js in the browser, why is it not included in the npm package? Am I missing something? (Sorry if it's something obvious.)

Thanks!
DJ

**Comment by kannappanr** [comment]
@djlauk Thanks for the detailed explanation. We will talk internally and get back to you on this.

**Comment by Praveenrajmani** [comment]
Hi @djlauk, Which npm version are you using? Did you try installing with `--save`/`--save-prod` flag ?

**Comment by Praveenrajmani** [comment]
Well, i tried cloning a sample polymer 3 application `https://github.com/PolymerLabs/start-polymer3`. And did a `npm install minio`.. I can see that it gets added in the package.json dependencies as expected. [ with npm version 6.4.1 ]
 
Can you try updating the npm version ? Or to use minio globally, u can do `npm install minio -g` to update the node_modules globally

**Comment by Praveenrajmani** [comment]
npm versions 5.0 and above does not require --save flags

**Comment by djlauk** [comment]
I am sorry. I think you misunderstood my problem. Let me rephrase: I want to use minio-js in the browser, but the file `minio-browser.js` is not part of the npm package (at least not in 7.0.1 or the current 7.0.5).

The project provides a gulpfile that contains a task called *browserify*. This task will create `minio-browser.js`, but currently I need to build this manually outside of the project and copy it into my source tree.

So for my use case (miniojs in the browser) this means, I cannot use npm for dependency management (because the npm package lacks the required file).

I'll be more detailed...

-----

# What I did

## Preparation of a [MCVE](https://stackoverflow.com/help/mcve)
```sh
$ mkdir test-issue729
$ cd test-issue729
$ polymer init --name polymer-3-application --npm
$ polymer serve
# open browser at http://localhost:8081/ to verify it works
# the web page shows "Hello test-issue729-app!"
# shut down polymer serve with ^C
```

## Steps to reproduce the issue
```sh
$ npm install minio
# add ES6 module import for minio
$ sed -i '1 a import { Minio } from "minio";' src/test-issue729-app/test-issue729-app.js
$ polymer serve
# open browser at http://localhost:8081/
```

# What I observed
- minio is included/referenced in `package.json`
- minio is included/referenced in `package-lock.json`
- Browser shows only a blank (white) page.
- Error message in the browser's console:
  `Uncaught SyntaxError: The requested module '../../node_modules/minio/dist/main/minio.js' does not provide an export named 'Minio'`

# What I expected to happen
- Browser shows the web page with "Hello test-issue729-app".
- No error in browser console for importing minio.

-----

Now, as said previously, when I use the source of minio-js (i.e. `git clone` into a separate directory somewhere), I can run `gulp browserify` and then use the output of that in my project. But then I don't get to have the benefits of dependency management through npm.

So, in short: Please add `minio-browser.js`(generated by `gulp browserify`) to the official npm package contents.

**Comment by Praveenrajmani** [comment]
@djlauk understood, looks like the gulpfile.js in minio-js has to do be checked. Will come up with a fix.

**Comment by djlauk** [comment]
I think, most changes need to be done in [package.json](https://docs.npmjs.com/files/package.json). The gulpfile itself seems fine, i.e. it can produce the minio-browser.js file successfully.

Here's what I think needs to be changed (in package.json):

1.  `gulp browserify` needs to be run before publishing the npm package (I don't know which element in [*scripts*](https://docs.npmjs.com/misc/scripts) is the correct one, might be *prepublish* or *prepare*)

2.  `dist/main/minio-browser.js` probably needs to be included through a *files* section in [package.json](https://docs.npmjs.com/files/package.json)

    Chances are, it would otherwise not be included in the npm package, even if it is built by the corresponding script, as the *main* file (`./dist/main/minio.js`) does not reference it.

Please beware: This is what I **deduced from reading documentation only**. So please double check, because I am a complete beginner with regard to building and publishing npm packages.

**Comment by Praveenrajmani** [comment]
@djlauk I can see the the minio-browser.js file is intentionally left un-exported. Let me discuss with the team here and conclude on whether we need that to be published.

**Comment by Praveenrajmani** [comment]
We are intentionally preventing this because of one of the following reasons

- The minio-browser.js in not properly tested. 
- We did not see a use case for that to fit. Developers use `minio-js` as nodejs package on the server      side and use presigned-urls from the browser.
- One important thing is that <b>it exposes secretkey to the clients</b> which is highly vulnerable and not appreciated.

**Comment by djlauk** [comment]
I think I understand... So... just to be sure I understand that correctly, let me re-phrase in my own words:

- The minio JS library is not intended to be used from inside the browser.
- In the browser our code should instead use presigned URLs and GET / POST / PUT / DELETE directly from the browser (e.g. through `fetch` or XHR).

Is that correct?

**Comment by Praveenrajmani** [comment]
> I think I understand... So... just to be sure I understand that correctly, let me re-phrase in my own words:
> 
>     * The minio JS library is not intended to be used from inside the browser.
> 
>     * In the browser our code should instead use presigned URLs and GET / POST / PUT / DELETE directly from the browser (e.g. through `fetch` or XHR).
> 
> 
> Is that correct?

Yes you are correct!

**Comment by djlauk** [comment]
Alright. Now it's clear. In that case, I consider the matter closed.

Thanks a lot!
