### ISSUE TITLE
callback should be of type "function"

### ISSUE THREAD

**Issue by Werewolve** [minio/minio-js#730]
I receive the error **callback should be of type "function"** with the following code:
`var test = await storage.presignedUrl('GET', 'stuff', '', 24*60, {});`
`console.log(test);`

I also tried without the params!

Using this is no problem:
`var test = await storage.presignedGetObject('stuff', 'file', 24*60)`

I think its a bug in the framwork. What do you think?

**Comment by kannappanr** [comment]
@Werewolve Thanks for a PR to solve this issue. https://github.com/minio/minio-js/pull/732
