### ISSUE TITLE
Content-disposition for the postPolicy

### ISSUE THREAD

**Issue by oeN** [minio/minio-js#736]
Hi,

I've started a couple of days ago using minio, but I cannot find how to set the `Content-Disposition` on a `postPolicy`

There is a way to set `metadata` on a `postPolicy`?

**Comment by kannappanr** [comment]
@oeN It is possible to do both. Here is an example to do it.

```

var Minio = require('minio')

var s3Client = new Minio.Client({
  endPoint: 'play.minio.io',
  port: 9000,
  accessKey: 'Q3AM3UQ867SPQQA43P2F',
  secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
  useSSL: true // Default is true.
})

// Construct a new postPolicy.
var policy = s3Client.newPostPolicy()
// Set the object name my-objectname.
policy.setKey("my-objectname")
// Set the bucket to my-bucketname.
policy.setBucket("testbucket")

var expires = new Date
expires.setSeconds(24 * 60 * 60 * 7) //7 days
policy.setExpires(expires)

policy.setContentLengthRange(1, 1024*1024) // Min upload length is 1KB Max upload size is 1MB

s3Client.presignedPostPolicy(policy, function(e, data) {
  if (e) return console.log(e)
  var curl = []
  curl.push(`curl ${data.postURL}`)
  for (var key in data.formData) {
    if (data.formData.hasOwnProperty(key)) {
      var value = data.formData[key]
      curl.push(`-F ${key}=${value}`)
    }
  }
  // Print curl command to upload files.
  curl.push('-F file=/etc/issue')
  curl.push("-F content-disposition='attachment'")
  curl.push("-F x-amz-meta-custom-header=customvalue")
  console.log(curl.join(' '))
})

```

**Comment by ebozduman** [comment]
Thank you @kannappanr 

@oeN,
Please let us know if @kannappanr's explanation/example works for you and is good enough to close the issue.

**Comment by oeN** [comment]
Thank you @kannappanr I'll try this way and see if works for my project, but I was searching for a way to set the `content-disposition` from the server side. I have an endpoint, that the frontend can call, and get a pre-signed `postURL` and the `formData` but I need to set the `content-disposition` based on a certain set of rules and I cannot replicate them in the frontend side.

**Comment by kannappanr** [comment]
you can use nginx to do this, if you are using it. Here is an example https://gist.github.com/un33k/7119264

Closing this issue now.
