### ISSUE TITLE
AngularJS

### ISSUE THREAD

**Issue by dineplan** [minio/minio-js#741]
Guys,
Do you have any references to use the Minio in AngularJS (Version 1.x) applications ?

**Comment by nitisht** [comment]
cc // @kaankabalak

**Comment by kannappanr** [comment]
@dineplan Why do you want to use `minio-js` in the browser? You can use pre-signed urls?

**Comment by shmoulana** [comment]
I can able to use .net api to upload the files to minio

It is two process if I do it from browser to asp.net controller and from controller to push it to minio

If it’s easy it to push directly to minio from browser, it is much easier 

If the pre-signed URL does the job and can be used in AngularJS controller, please share and it will be helpful

**Comment by kanagarajkm** [comment]
@shmoulana did you look at this https://docs.minio.io/docs/upload-files-from-browser-using-pre-signed-urls.html

`1. Create the Server` - would be your asp.net controller
`2. Create the Client-side Web Application` - this uses jquery, i hope you can easily find how to do this in AngularJS.

**Comment by kaankabalak** [comment]
@shmoulana Given that you have a server where you have configured an endpoint with the format `/presignedUrl?name=filename` in which you would be invoking [PresignedPutObject](https://docs.minio.io/docs/dotnet-client-api-reference.html#presignedPutObject) on the .NET API to generate a pre-signed URL for the file called `filename`, and assuming that your front-end app resides in a folder called `public` with the following structure:

```
```

index.html:
```html
<!DOCTYPE html>
<html ng-app="angularApp">
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.6/angular.min.js"></script>
    <script src="index.js"></script>
    <script src="services.js"></script>
    <script src="directives.js"></script>
  </head>
  <body>
    <div ng-app="angularApp" ng-controller="indexCtrl">
      <input
        type="file"
        name="file"
        ng-model="files"
        ng-file-model
        multiple
      />
      <button ng-click="upload();">Upload</button>

      <div id="status">{{ status }}</div>
    </div>
  </body>
</html>
```

index.js:
```js
angular
  .module("angularApp", [])
  .controller("indexCtrl", [
    "$scope",
    "service",
    function($scope, service) {
      // Initialize variables
      $scope.files = [];
      $scope.status = "No uploads";
      $scope.service = service;

      $scope.upload = function() {
        angular.forEach(($scope.files), function(file) {
          // Retrieve a URL from our server.
          service.retrieveNewURL(file, function(url) {
            // Upload the file to the server.
            service.uploadFile(file, url)
              .then(function successCallback() {
                $scope.status = "Upload complete!";
              })
              .catch(function errorCallback(err) {
                $scope.status = "An error has occurred";
              })
          })
        });
      }
    }
  ]);
```

services.js:
```js
angular
  .module("angularApp")
  .service("service", ["$http", function($http) {
    this.retrieveNewURL = function(file, cb) {
      $http.get(`/presignedUrl?name=${file.name}`)
      .then(function successCallback(url) {
        cb(url.data)
      })
    };
    this.uploadFile = function(file, url) {
      return $http.put(url, file, {
        headers: {
          'Content-Type': file.type
        },
      })
    };
  }]);
```

directives.js:
```js
```

**Comment by kannappanr** [comment]
@dineplan @shmoulana Closing this as answered. Please feel free to re-open the issue if you feel otherwise
