### ISSUE TITLE
Functional tests are failing

### ISSUE THREAD

**Issue by jefvel** [minio/minio-js#742]
When #739 was merged into master it seems to have made the functional tests to fail: https://travis-ci.org/minio/minio-js/builds/474536689
I'm not sure if it is that commit that caused it, since the tests passed in its own branch.

**Comment by harshavardhana** [comment]
I restarted them, it is perhaps because I restarted play.minio.io deployment.

**Comment by jefvel** [comment]
https://travis-ci.org/minio/minio-js/builds/477626515 could this build job have the same issue?

**Comment by jefvel** [comment]
Ah, I see. Perfect, the tests passed
