### ISSUE TITLE
PutObjectPart has user metadata in the header

### ISSUE THREAD

**Issue by jefvel** [minio/minio-js#743]
If I try to upload a file larger than 5mb with metadata to AWS, the metadata will be added in the PutObjectPart request too, which results in an error: `Metadata cannot be specified in this context.`.

To follow S3 standards, metadata should only be provided in the multipart initiation call

**Comment by harshavardhana** [comment]
Yes you are right this is a bug. Thanks we will fix it.

**Comment by kannappanr** [comment]
@jefvel Thanks for sending a fix.
