### ISSUE TITLE
Ability to create users via this SDK? 

### ISSUE THREAD

**Issue by mgcrea** [minio/minio-js#745]
I've quickly looked at the docs but it does not look like it is possible to create users with this SDK. Was looking for a way to create users on-the-fly from a NodeJS server backend.

Any other way to achieve this?

Thanks!

**Comment by harshavardhana** [comment]
No not yet, there is a plan to add in future.  You can use the `mc` command directly.

**Comment by kannappanr** [comment]
@mgcrea closing this issue now. Please feel free to reach out to us if you have further questions.

**Comment by LeBovin** [comment]
Any news about it ?

**Comment by maaft** [comment]
Would also be very interested!

Using precompiled binaries with `exec(...)` in your backend-code (for i.e. automatic user creation) feels very hacky..

**Comment by denolfe** [comment]
It would be great if this functionality could be added. The Go package [madmin-go](https://github.com/minio/madmin-go) implements this along with other admin functions.

**Comment by prakashsvmx** [comment]
@denolfe it would not be available in any other SDK.

**Comment by 4D5A90** [comment]
any news ?

**Comment by prakashsvmx** [comment]
@4D5A90 Please check https://github.com/minio/madmin-go
it will not be part of any sdks
