### ISSUE TITLE
Android upload images failure

### ISSUE THREAD

**Issue by PWDream** [minio/minio-js#746]
We found that our users have failed to upload images using Android devices, and there is no problem with iOS devices.
Our upload method is background signature, front-end upload
The following is the error message:

`<Error>
	<Code>SignatureDoesNotMatch</Code>
	<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
	<Resource>/ekuaibao/Screenshot_20190114-180557-1547544432632-502.png</Resource>
	<RequestId>1579FB7A7D70DC75</RequestId>
	<HostId>3L137</HostId>
</Error>`

**Comment by kannappanr** [comment]
@PWDream I am unable to understand this statement
`Our upload method is background signature, front-end upload`

I am assuming that you are using `minio-js`. If yes, you can enable tracing in `minio-js` by printing to the console. Usually it will be ` client.traceOn(traceStream)`

What is the S3 server that you are trying to connect to?
Is it Minio? If yes, you can also enable tracing on the minio side by starting say minio by specifying `MINIO_HTTP_TRACE=/dev/stdout minio server /data`

**Comment by PWDream** [comment]
My signature is signed in the background,did not use minio-js

**Comment by krishnasrinivas** [comment]
> My signature is signed in the background,did not use minio-js

How do you sign it? Did you write custom code to sign it? We advise you to use standard libraries to compute signature as it is very hard to write custom signing code.

Also if you are not using minio-js, you can raise the issue on github.com/minio/minio, also what version of minio server are you using?

**Comment by kannappanr** [comment]
@PWDream Closing this issue now. Please feel free to re-open the issue if you need further clarification.
