### ISSUE TITLE
presignedPutObject returns no url in promise mode

### ISSUE THREAD

**Issue by cipher-code** [minio/minio-js#747]
Steps to reproduce:

Call presignedPutObject() without a callback.

Expected Result:
A promise to be returned

Actual Result:
Nothing is returned

Example code: https://github.com/cipher-code/libr-api/blob/4cd67053b047a07466fbce4361498e48b378e99b/src/actions/presign-put-object.ts#L8

**Comment by nitisht** [comment]
Thanks for reporting @cipher-code , we'll take a look

**Comment by cipher-code** [comment]
I should add that if you do pass a callback a url will be returned as expected

**Comment by kanagarajkm** [comment]
@cipher-code presignedPutObject returns a Promise when the callback function is not passed.

From your code, 
```javascript
   let url : string;
    try {
        let url = await minioClient.presignedPutObject('temp', request.query.name, 600);
    } catch(error) {
        response.status(500);
        response.send('Internal Server Error when obtaining presigned put object');
        return Promise.resolve();
    }
```
`let url` is defined twice, you might have to remove `let` from try block to avoid creating local scoped url and use the function scope `url`.

**Comment by kannappanr** [comment]
@cipher-code Closing this is as answered. Please feel free to re-open the issue if you feel otherwise.
