### ISSUE TITLE
Allow to define chunk size

### ISSUE THREAD

**Issue by Farkal** [minio/minio-js#757]
I am piping a stream from an http request to minio and the website don't share file size in content-length.

Minio split this file in 3 chunk (the file size is 1.7GB) and the upload become extremely slow.

If I first download the object and send it to minio after with fPutObject, everything is fine and we get lot of small chunks.

Is it possible to allow user to define the chunk size or by default start using small chunk size ?

**Comment by kannappanr** [comment]
@Farkal In the case of unknown size, the part size is probably set to 512 MB. Will check internally and see if this can be configured in this scenario.

**Comment by kannappanr** [comment]
@Farkal we will add a way to set the part_size in this scenario.

**Comment by Farkal** [comment]
Ok thank you very much !

**Comment by kannappanr** [comment]
Here is the PR https://github.com/minio/minio-js/pull/759

**Comment by kannappanr** [comment]
Closing this as #759 has been merged
