### ISSUE TITLE
Upload folder ?

### ISSUE THREAD

**Issue by Farkal** [minio/minio-js#758]
Is there any way to upload a folder to minio easily ?

Or i have or I have to use fs and execute fPutObject on each file inside the folder ?

**Comment by Farkal** [comment]
If someone is interested by my code to make it work (i use walk for recursive folder listing):
```
const walk = require('walk')
const minioPath = 'test/'

const walker = walk.walk('tmp/')
walker.on('file', (root, fileStats, next) => {
  const filePath = root + '/' + fileStats.name
  console.log('Upload', filePath)
  minioClient.fPutObject(minioBucket, minioPath + filePath, 'tmp/' + filePath, err => {
    console.log(filePath, ' uploaded)
    if (err) {
      console.error(err)
    }
    next()
  })
})

walker.on('end', function() {
  console.log('End upload')
})
```

**Comment by harshavardhana** [comment]
Thanks this is the expected solution, minio-js provides API level abstractions. But other richer functionalities such as upload a folder is written in your application.

Thanks for sharing the snippet.

**Comment by jlegido** [comment]
@Farkal thanks for sharing, but since I'm newbie, could you please point to the documentation on how to extend minio with your snippet?

Thanks in advance.

**Comment by Farkal** [comment]
> @Farkal thanks for sharing, but since I'm newbie, could you please point to the documentation on how to extend minio with your snippet?
> 
> Thanks in advance.

There is no extend needed, just declare your minio client like the readme say and then use walk.
I improved my snippets with the declaration of the minio client 😉
