### ISSUE TITLE
`fPutObject` does not detect content-type automatically

### ISSUE THREAD

**Issue by ndxbn** [minio/minio-js#763]
https://github.com/minio/minio-js/blob/master/examples/fput-object.js#L38-L46

`fPutObject` should detect  content-type automatically, but after https://github.com/minio/minio-js/pull/698 , it doesn't work.

**Comment by nitisht** [comment]
Thanks for reporting @ndxbn we'll take a look

**Comment by kaankabalak** [comment]
We also would need to update the example file as it only applies for the versions before #698 came in
