### ISSUE TITLE
Cannot read property 'Client' of undefined

### ISSUE THREAD

**Issue by realivanjx** [minio/minio-js#769]
I'm simply tried to follow the tutorial. When im trying to do:
```
import Minio from 'minio';
import { minioConfig } from '../config';
const client = new Minio.Client(minioConfig);
```
I got this error `TypeError: Cannot read property 'Client' of undefined`

Installation:
```
"@types/minio": "^7.0.1"
"minio": "^7.0.8"
```

VS Code intellisense works, installation good, but when trying to run i just stuck with that error.

**Comment by kanagarajkm** [comment]
@realivanjx i couldn't find any docs which refer this `import Minio from 'minio';`, can you please give the link?

**Comment by kanagarajkm** [comment]
@realivanjx i couldn't find any docs which refer this `import Minio from 'minio';`, can you please give the link?

**Comment by realivanjx** [comment]
Hm, wait. This works:
`import * as Minio from 'minio';`
instead of:
`import Minio from 'minio;`

I think it is better to put this in the doc. Thanks for your time...

**Comment by kanagarajkm** [comment]
@realivanjx this happens only with `tsc`, will check further and update the docs if required. Thanks.

**Comment by realivanjx** [comment]
You're welcome :)

**Comment by WolvenSpirit** [comment]
This still happens when importing in `commonjs` style.
Both import methods `import Minio from "minio"` and `import * as Minio from "minio"` fail.
The solution is quite simple though:
```ts
import Minio from "minio";
const _minio = require("minio");

export let minioClient: Minio.Client = _minio.Client(params);
```
This way you can have the intellisense while still importing it as in the example.

**Comment by prakashsvmx** [comment]
A.sample usage on web can also be found here. 
https://github.com/prakashsvmx/minio-js-web-browser-example/blob/master/src/mc.js
