### ISSUE TITLE
Is it ok to use `makeRequest()` directly?

### ISSUE THREAD

**Issue by mlschuh** [minio/minio-js#771]
I was wondering if it is an ok practice to call `makeRequest()` (inside `src/main/minio.js`) in our source. We would like to use STS and create temporary credentials (AssumeRole) and it would be easier to use the existing client connection that to figure out the signing/auth on our own.

**Comment by kannappanr** [comment]
In general we recommend people to use `mc` to generate temporary credentials.

cc @krishnasrinivas

**Comment by krishnasrinivas** [comment]
@mlschuh `makeRequest()` is not documented and is not supposed to be used by applications directly. But if you know what you are doing, it is OK to use it. i.e you will have to be aware that `makeRequest()` may change in future which might brake your application. (If you pin the minio-js version it should be OK)

**Comment by mlschuh** [comment]
Using `mc` wouldn’t be ideal as we’re running the JS SDK inside a node app in a docker container so the abstraction would leave me a bit uneasy. I have no problem pinning the version number and verifying any updates that come along. 

Would there be any thought behind making some kind of generic request SDK call? There’s been a ton of things added lately that would be nice to access, even if the SDK hasn’t yet been updated with a dedicated function call. I know it wouldn’t be directly in line with s3 compatibility, though.

**Comment by kannappanr** [comment]
@mlschuh Will check internally to see if we can provide you with such a call

**Comment by kannappanr** [comment]
@mlschuh `makeRequest` is that call. Like explained by @krishnasrinivas , if you can pin the `minio-js` version, it should be OK.

**Comment by mlschuh** [comment]
Works for me! Closing as I now have an answer.
