### ISSUE TITLE
Can't use setBucketNotification with minio server

### ISSUE THREAD

**Issue by PacoDu** [minio/minio-js#775]
Hi, I can't find a wait to use setBucketNotification with minio server and amqp notifications.

I have a minio server with amqp notification enabled and I can set notification from mc client with:
```
mc event add  myminio/mybucket arn:minio:sqs::1:amqp --prefix myprefix/
```

But when I try to set notifications from the minio-js client it returns this error:
```
S3Error: MinIO server does not support Topic or Cloud Function based notifications.
```

I'm unable to reproduce this example with a minio server : https://github.com/minio/minio-js/blob/master/examples/set-bucket-notification.js

**Comment by nitisht** [comment]
> I'm unable to reproduce this example with a minio server : https://github.com/minio/minio-js/blob/master/examples/set-bucket-notification.js

Are you saying this works with MinIO but not with AWS S3?

**Comment by PacoDu** [comment]
No, I don't know if this works with AWS (but the example seems written for AWS). I'm only using minio and it doesn't work. It returns the `MinIO server does not support Topic or Cloud Function based notifications.` error, which is strange because I'm able to setup the same notification using mc CLI client.

**Comment by PacoDu** [comment]
This works:
```
mc event add  myminio/mybucket arn:minio:sqs::1:amqp --prefix myprefix/
```

This doesn't work:
```
const minio = require('minio')

const client = new minio.Client({
  endPoint: 'localhost:9000',
  accessKey: '*********',
  secretKey: '*********'
})

const config = new minio.NotificationConfig()
const arn = minio.buildARN('minio', 'sqs', '', 1, 'amqp')
const topic = new Minio.TopicConfig(arn)

topic.addFilterPrefix('myprefix/')
topic.addEvent(Minio.ObjectCreatedAll)

config.add(topic)

client.setBucketNotification('mybucket', config, function(e) {
  if (e) {
    return console.log(e)
  }
  console.log("Success")
})
```

**Comment by PacoDu** [comment]
With additional logs:
```
arn: arn:minio:sqs::1:amqp
topic:
TopicConfig {
  Topic: 'arn:minio:sqs::1:amqp',
  Filter: {
    S3Key: { FilterRule: [ { Name: 'prefix', Value: 'myprefix/' } ] }
  },
  Event: [ 's3:ObjectCreated:*' ]
}
```

**Comment by PacoDu** [comment]
I finally find the issue after digging in the source code.

I have to use `minio.QueueConfig` instead of `minio.TopicConfig`, I think this should be documented in the official minio doc, we faced the issue with javascript and python clients.

**Comment by kannappanr** [comment]
MinIO doesn't support `TopicConfig`, the examples were written for generic S3 servers. I agree that we should change the examples to use `QueueConfig` instead of `Topicconfig`, so users can verify it with `MinIO` instead of `AWS S3`
