### ISSUE TITLE
Minio play still not available

### ISSUE THREAD

**Issue by thomaslange24** [minio/minio-js#777]
Hi, minio play is still not available. when executing the command "mc admin info play" it says offline.

**Comment by nitisht** [comment]
Just checked @thomaslange24 Play is available 

```
$ mc admin info play
●  127.0.0.1:9000
   Status : online
   Uptime : 22 hours 
  Version : 2019-07-02T09:29:52Z
   Region : us-east-1
  Storage : Used 2.3 GiB
   Drives : 4/4 OK
```

**Comment by thomaslange24** [comment]
when i run it, it says offline. Maybe i should reinstall the minio client?
Also trying to access minio play in the browser does not work for me.

**Comment by nitisht** [comment]
> when i run it, it says offline. Maybe i should reinstall the minio client?

Does this work `ping play.minio.io`?

**Comment by thomaslange24** [comment]
Yes, it seems to work
![snapshot](https://user-images.githubusercontent.com/18648000/60576655-22651200-9d7e-11e9-9a16-3e95758bd0c2.PNG)

**Comment by nitisht** [comment]
Do you have `mc` alias set? Can you try `mc config host list` as paste the results after removing credentials

**Comment by thomaslange24** [comment]
isn't the alias for minio play set per default?
![Capture](https://user-images.githubusercontent.com/18648000/60577230-407f4200-9d7f-11e9-9ac6-590adffb6ef8.PNG)

**Comment by thomaslange24** [comment]
I meant mc is pre-configured with play

**Comment by nitisht** [comment]
> I meant mc is pre-configured with play

Yes, it is. But just wanted to ensure if it is not edited.  
Looks like somehow `mc` requests to play are not being sent from the client, because Play is up and running..

**Comment by thomaslange24** [comment]
But i can not access the ui in the browser too. So it probably does not have to do with the mc installation

**Comment by kannappanr** [comment]
@thomaslange24 Play is accessible to me too. Can you try

https://play.min.io on your browser?

**Comment by thomaslange24** [comment]
No, that does not work either

**Comment by harshavardhana** [comment]
@thomaslange24 play is available publicly and working. you must have a local proxy which is disallowing the requests. 

We will close this issue.
