### ISSUE TITLE
using `makeRequest()` to get 'assumeRole'

### ISSUE THREAD

**Issue by pedromguerra** [minio/minio-js#778]
according to https://github.com/minio/minio-js/issues/771 I'm trying to use makeRequest() to use ''AssumeRole". My code looks like this:
```
minioClient.makeRequest(
		{
			method: 'POST',
			headers: { ['Content-Type']: 'application/x-www-form-urlencoded' }
		},
		'Action=AssumeRole&DurationSeconds=3600&Version=2011-06-15',
		200,
		'us-east-1',
		true,
		(err, res) => {
			if (err) return _cb(err);
			_cb(null, res);
		}
	);
```

but I always get this error:
```
{
    "error": {
        "error": {
            "Type": [
                ""
            ],
            "Code": [
                "InternalError"
            ],
            "Message": [
                "We encountered an internal error generating credentials, please try again."
            ]
        },
        "requestid": "15ADFE695D8A2372",
        "amzRequestid": null,
        "amzId2": null,
        "amzBucketRegion": null
    }
}
```

I tried everithing, some idea what's wrong ?
Thanks in advance

**Comment by kannappanr** [comment]
@pedromguerra Can you use `mc admin trace` command and verify you are sending same as when you would use `mc`?

**Comment by mlschuh** [comment]
@kannappanr I'm working with @pedromguerra on this. It doesn't look like `mc` has any facility for Assume Role to be able to mimic. When we went further and tried with the AWS JS SDK, it is now returning `AccessDenied: Generating temporary credentials not allowed for this request.`. We are using the global key and secret.

We're also looking into adding and removing users manually but the `makeRequest()` only takes query parameters for the signing so we'd have to roll our own. While possible, I'd like to avoid doing this and rather not fork the library. Would we be better trying to use the stock AWS JS SDK that is a bit better coverage for all of the S3 features?

**Comment by reessing** [comment]
@mlschuh and @pedromguerra Did you finally succeed using makeRequest() with AssumeRole? I ran into the same question and wondered if you were able to make any headway on this issue?

**Comment by reessing** [comment]
@mlschuh Thank you for your feedback. Meanwhile, I gathered some insights on this issue. I was about to assume that there is a general problem with the AssumeRole functionality of MinIO when I found out that it is actually possible to generate temporary credentials using `aws-cli` and MinIO. 

Later I reproduced the results using the AWS JS SDK. I was able to use the generated temporary credentials to sucessfully access a MinIO bucket. I'm not sure if you are aware of such a solution or if you just ruled out using AWS JS SDK. At least we can conclude that MinIO's AssumeRole functionality generally works. 

While using AWS JS SDK might be a solution for the time being, it would still be nice to do all this using minio-js. Maybe we could monitor the communication between AWS JS SDK and MinIO to find out if we can reproduce such requests using `makeRequest()`?

**Comment by mlschuh** [comment]
For us, one of the biggest problems was that we would need to create a non-super user inside Minio to assume-role from, which requires `mc`. As we very rarely directly interact with Minio on our systems, we would need to automate that process with `mc`. Given that, we have `mc` anyway, we didn't feel a need to introduce the AWS JS SDK beyond that and it forced us to make sure our interaction with `mc` was reliable. We are more of an edge case so I'd recommend other people use the AWS JS SDK before trying to automate a command line software.

**Comment by sinhaashish** [comment]
@mlschuh @reessing @pedromguerra  The `makeRequest()` function signs the request and sends it to server. The server find a mismatch in sign and returns the error. The error is returned from `reqSignatureV4Verify` in the `auth-handler.go` file from minio server.  For `assumeRole` functionality the request need not to be signed , this is specifed in S3 spec as well .  [ Refer](https://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html).  `Some requests do not need to be signed, such as anonymous requests to Amazon Simple Storage Service (Amazon S3) and some API operations in AWS Security Token Service (AWS STS) such as AssumeRoleWithWebIdentity.` You can try and make a client call without signing the request .

**Comment by prakashsvmx** [comment]
Closing this as there will be a new API to make such calls. open issue: #928
