### ISSUE TITLE
S3Error: 413

### ISSUE THREAD

**Issue by oratck** [minio/minio-js#780]
Hi,

I found error while uploading this file. It was happened both by upload via MinIO Browser and put object by this lib.

- MinIO Browser : Stuck at 100%
- Put Object: S3Error: 413

![99800359-ee3d-49f7-b746-2722a0f98816](https://user-images.githubusercontent.com/23364833/61439672-255e2600-a96c-11e9-8741-8fbd54197407.gif)

**Comment by nitisht** [comment]
what is the minio server version here @oratck ?

**Comment by oratck** [comment]
@nitisht 

<img width="596" alt="Screen Shot 2562-07-18 at 16 55 16" src="https://user-images.githubusercontent.com/23364833/61448568-51ce6e00-a97d-11e9-8868-bce51754ae2c.png">
<img width="596" alt="Screen Shot 2562-07-18 at 16 56 05" src="https://user-images.githubusercontent.com/23364833/61448570-52670480-a97d-11e9-8d09-a63d8cb47cae.png">

**Comment by nitisht** [comment]
can you update the MinIO server to latest and try again. This issue was fixed already AFAIK.

**Comment by kannappanr** [comment]
@oratck I was unable to reproduce this issue against the minio version `2019-03-27...` I used the web browser.

**Comment by kannappanr** [comment]
@oratck Closing this issue as stale. Please feel free to re-open this issue when you have more information for us to reproduce this issue
