### ISSUE TITLE
Hope improving the api for modifying the metaData of Object

### ISSUE THREAD

**Issue by nicholasyih520** [minio/minio-js#784]
1. Hope to add a new feature that I can modify the metaData directly of existing Objects.
2. Also, hope that I can modify the metaData of Object when I call copyObject() API. 
thanks

**Comment by kannappanr** [comment]
@nicholasyih520 Thanks for the suggestion. Please feel free to send a PR.

**Comment by kannappanr** [comment]
@nicholasyih520 Both the requests can be done by your request 2). Closing this issue as it has been stale for a while. Please feel free to send a PR. We are a little short on cycles right now, if you cannot get to it, we will get to it in the near future.
