### ISSUE TITLE
Rename a file with minio js

### ISSUE THREAD

**Issue by JensPauwels** [minio/minio-js#787]
Can someone provide an example how to rename a filename in the S3 storage?

I can't find it in the docs or the src code.

Thanks in advance

**Comment by kannappanr** [comment]
@JensPauwels There is no S3 API to do this. The only thing you can do is to `copy` this object to the new filename and then delete this object

**Comment by JensPauwels** [comment]
Will there be a rename function in the future? Becuase there's no transactional way to interact with S3 api right?

**Comment by kannappanr** [comment]
@JensPauwels Yes, they are not transactional in nature. MinIO implements `S3 APIs` which currently doesn't have a rename API.  

Closing this now. Please feel free to reach out to us on slack at https://slack.min.io for further such questions.

**Comment by JensPauwels** [comment]
Npm S3 has a build in function to copy and delete objects safely. Is this the libary that you are using?
```
client.moveObject(s3Params)
See http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#copyObject-property

s3Params are the same. Don't forget that CopySource must contain the source bucket name as well as the source key name.

Under the hood, this uses copyObject and then deleteObjects only if the copy succeeded.

Returns an EventEmitter with these events:

'error' (err)
'copySuccess' (data)
'end' (data)
```

**Comment by harshavardhana** [comment]
There is no safe way to do it @JensPauwels its just two different disconnected operations - they are not locked and not atomic.

**Comment by JensPauwels** [comment]
And will you implement the moveObject or not?

**Comment by harshavardhana** [comment]
> And will you implement the moveObject or not?

We will not @JensPauwels

**Comment by lcanavesio** [comment]
Any update ?

**Comment by prakashsvmx** [comment]
You can use copyobject api to achieve rename functionality. there would not be move object api. Please use the latest.
@lcanavesio

**Comment by OSA413** [comment]
I guess in this case you should keep files in minio as their IDs and keep file name-ID relation separately, that's the only safe way of renaming the files.
