### ISSUE TITLE
Possibility to override the host as option in presignedGetObject

### ISSUE THREAD

**Issue by toovy** [minio/minio-js#791]
Hi,
I'm having a scenario where a minio instance is accessed both from clients in a local network (e.g. docker swarm) as e.g. http://minio1 and from the internet (e.g. https://minio.customer-friendly-domain.com).

Looking at function https://github.com/minio/minio-js/blob/64d0a7f391b8a831d16debb9416c6017b806118f/src/main/minio.js#L1635 and https://github.com/minio/minio-js/blob/64d0a7f391b8a831d16debb9416c6017b806118f/src/main/minio.js#L164 the host is blindly assumed to be the same as the client connection parameters. If one could pass the host as parameter to the signing methods, it would be possible to have the client connect to http://minio1 but to generate presigned URLs for https://minio.customer-friendly-domain.com . While there might be some workarounds this option would be nice. The Go-API accepts a host passed from outside if I'm not mistaken: 
https://github.com/minio/minio/blob/3385bf3da894e5f1da72553ff6d89707a09496c5/cmd/web-handlers.go#L1787

BR, toovy

**Comment by toovy** [comment]
Furthermore, it would be great to be able to override the region so that the call to `this.getBucketRegion` is not needed: https://github.com/minio/minio-js/blob/64d0a7f391b8a831d16debb9416c6017b806118f/src/main/minio.js#L1607
This way one could generate the URL without calling the Minio instance (=faster).

**Comment by kanagarajkm** [comment]
> Furthermore, it would be great to be able to override the region so that the call to `this.getBucketRegion` is not needed:
> 
> https://github.com/minio/minio-js/blob/64d0a7f391b8a831d16debb9416c6017b806118f/src/main/minio.js#L1607
> 
> 
> This way one could generate the URL without calling the Minio instance (=faster).

you can pass the region while creating the client https://github.com/minio/minio-js/blob/master/docs/API.md#1--constructor

**Comment by kanagarajkm** [comment]
if you want to create presignedUrl for a different hostname, you can initialize Minio Client with that hostname. for example

```js
var Minio = require('minio')

var minioClient = new Minio.Client({
    endPoint: 'minio1',
    port: 9000,
    useSSL: false,
    accessKey: 'minio',
    secretKey: 'minio',
    region: 'us-east-1'
});

// expires in a day.
minioClient.presignedGetObject('mybucket', 'hello.txt', 24*60*60, function(err, presignedUrl) {
  if (err) return console.log(err)
  console.log(presignedUrl)
})
```

**Comment by toovy** [comment]
@kanagarajkm thank you for this workaround, that is a good thing. 

From a API design I personally don't like it, as it is kind of misleading for me. I would have to initalised two clients, one that is just for signing and one that does the heavy lifting (like uploading). 

Initialising only one client that allows me to override the host & region during the `presignedGetObject` call makes more sense for me, but I think you could argue about that.

Thanks again!
