### ISSUE TITLE
NoSuchBucket

### ISSUE THREAD

**Issue by imagineLife** [minio/minio-js#793]
Hello there,

**PROBLEM**  
I get the NoSuch Bucket, even though the bucket definitely exists. Any Thoughts?

**CURRENTLY**
I can create buckets, create files in buckets, && getObject from buckets.
I am hosting minio locally at the moment.
Below are 2 screenshots, 1 of the code && one of the console. 
![Screen Shot 2019-08-15 at 9 43 56 AM](https://user-images.githubusercontent.com/24195040/63098923-038f9900-bf42-11e9-8327-9bbd5868bea6.png)
![Screen Shot 2019-08-15 at 9 44 16 AM](https://user-images.githubusercontent.com/24195040/63098925-038f9900-bf42-11e9-8946-b849ea8f6e8f.png)

**Comment by kanagarajkm** [comment]
@imagineLife first argument of presignedUrl function should be `httpMethod`
```js
presignedUrl(httpMethod, bucketName, objectName[, expiry, reqParams, requestDate, cb])

```

**Comment by kannappanr** [comment]
@imagineLife PTAL https://docs.min.io/docs/javascript-client-api-reference.html#presignedUrl 

Please reach out to us on slack at https://slack.min.io for such questions
