### ISSUE TITLE
SignatureDoesNotMatch on Minio Server Docker

### ISSUE THREAD

**Issue by inovramadani** [minio/minio-js#794]
Hi,
 
I got an issue to write/upload image file to bucket using minio-js.
The error says: SignatureDoesNotMatch.
But I can read the existing image files from minio server. Only I can't upload image files.

Environment of minio server is on docker app. I am thinking maybe related to wrong port mapping during write.

How I get it works somehow is by using ngrok to host the server IP address exposing port 9000 (which is the minio server on the container) and use that ngrok url on endpoint (without passing port 9000 on MinioClient constructor). But this is not the ideal solution for me to go to production. Need to use direct IP only.

Can you explain what actually causes this and what is the ideal solution?

Below is the error screenshot:
![image](https://user-images.githubusercontent.com/27492820/63151543-ef2bc900-c033-11e9-80fc-e923978d319d.png)

What I have tried and did not work:
1. Changing the bucket policy to be Read and Write from Read-Only.
2. Restarting minio server on docker container

PS: I tried in my local minio server, it has no problem like this.

**Comment by inovramadani** [comment]
The client on java does not have the problem, as android app works properly on this case. Using exact same minio server on docker app and same backend environment.

**Comment by kannappanr** [comment]
We will take a look and get back to you

**Comment by kanagarajkm** [comment]
@inovramadani  Few questions
1. How did you import minio-js into the browser?
2. Can you give the sample code for Minio Client initialization and putObject?
3. Are you using the same client instance for downloading and uploading files to Minio?

**Comment by inovramadani** [comment]
1 & 2. Please find below the code for minio client.
```javascript
import { Client as MinioClient } from 'minio';
import fileToArrayBuffer from 'file-to-array-buffer';
import arrayBufferToBuffer from 'arraybuffer-to-buffer';
import ConnectionSetting from 'settings/connection';

const PORT = 9000;
const ACCESS_KEY = '12345678';
const SECRET_KEY = '87654321';
const REGION = 'some-region';
export const BUCKET = 'some-bucket';

const BUCKET_POLICY = {
  "Version":"2012-10-17",
  "Statement":[
    {
      "Sid":"AddPerm",
      "Effect":"Allow",
      "Principal": "*",
      "Action":["s3:GetObject"],
      "Resource":[`arn:aws:s3:::${BUCKET}/*`]
    }
  ]
}

class MinioManager {
  constructor() {
    const endPoint = ConnectionSetting.s3Endpoint; //endPoint here taking from user input, ideally would be direct IP or I tested also with ngrok public url

    let minioClient = new MinioClient({
        endPoint,
        port: PORT,
        useSSL: false,
        accessKey: ACCESS_KEY,
        secretKey: SECRET_KEY
    });

    minioClient.bucketExists(BUCKET, (err, exists) => {
      if (err) return console.log(err)

      if (!exists) {
        minioClient.makeBucket(BUCKET, REGION, (err) => {
          if (err) return console.log(err)
          console.log(`Bucket ${BUCKET} created successfully in ${REGION}`)
          this.isBucketCreationFinish = true;

          minioClient.setBucketPolicy(BUCKET, JSON.stringify(BUCKET_POLICY), err => {
            if (err) return console.log(err)
            console.log('Bucket read-only policy set')
          })
        });
      } else if (exists && !this.isBucketCreationFinish) {
        this.isBucketCreationFinish = true;
      }
    })

    this.endPoint = endPoint;
    this.minioClient = minioClient;
  }

  upload(file, cb) {
    const { name } = file;
    const key = Date.now() + name;

    fileToArrayBuffer(file).then(arrayBuffer => {
      const buffer = arrayBufferToBuffer(arrayBuffer);

      if (!this.isBucketCreationFinish) {
        // retry in 1 sec until bucket created
        setTimeout(() => {
          this.upload(file, cb);
        }, 1000);
      } else {
        this.minioClient.putObject(
          BUCKET,
          key,
          buffer,
          (err, etag) => {
            if (cb) { 
              const fileUrl = `http://${this.endPoint}:${PORT}/${BUCKET}/${key}`;
              cb(err, key, fileUrl);
            }
          }
        )
      }
    })
  }
}

export default MinioManager;

```

3. Yes

**Comment by inovramadani** [comment]
@kanagarajkm @kannappanr may I know what causes signature does not match usually? How could generated signature doesn't match with minio server signature provided?

**Comment by kanagarajkm** [comment]
@inovramadani the code works fine for me. Can you get the output of `mc admin trace <ALIAS> -v` when the call fails?

**Comment by inovramadani** [comment]
@kanagarajkm did you try it on docker environment or minio server on linux?

> Can you get the output of mc admin trace <ALIAS> -v when the call fails?
Not sure where should I put this command?

**Comment by kanagarajkm** [comment]
@inovramadani i have test with docker, it worked fine.

You can read about trace here https://docs.min.io/docs/minio-admin-complete-guide.html#trace

**Comment by inovramadani** [comment]
Finally found the issue is it doesn't reach minio server on docker when the request is passed through nginx docker. This is more of environment problem. Fixed by mapping the 9000 port directly on minio docker.
