### ISSUE TITLE
MinIO JavaScript Client SDK on React Native

### ISSUE THREAD

**Issue by vstung89** [minio/minio-js#795]
I need to upload files from a React Native application.
Is there a way to use MinIO JavaScript Client SDK (just putObject) on React Native?
Thanks!

**Comment by kanagarajkm** [comment]
@vstung89 minio-js is not supported in React Native environment. Instead, you can use aws js sdk to connect to MinIO. 

For example,
```js
import AWS from "aws-sdk";

var s3 = new AWS.S3({
  accessKeyId: "Q3AM3UQ867SPQQA43P2F",
  secretAccessKey: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
  endpoint: "https://play.min.io",
  s3ForcePathStyle: true,
  signatureVersion: "v4"
});

s3.listObjects({ Bucket: "test" }, (err, data) => {
  console.log(data);
});
```

**Comment by vstung89** [comment]
@kanagarajkm Yes, it worked, thank you! Sorry for the late confirmation.

**Comment by snigdhasahoo** [comment]
I need to upload files from next js. How can i use Minio js here

**Comment by prakashsvmx** [comment]
> I need to upload files from next js. How can i use Minio js here

Do you want to use aws sdk or minio-js sdk ?

You can find the instructions of udane in README.md.

**Comment by mrcMesen** [comment]
@kanagarajkm hey thanks, Is there any update to use minio-js in React Native ?
