### ISSUE TITLE
Can minio.js create folders?

### ISSUE THREAD

**Issue by ITHcc** [minio/minio-js#796]
I didn't see this API in the minio documentation, but i can make folders at buckets in minio Browser

**Comment by nitisht** [comment]
you can upload objects with prefixes @ITHcc , it will create the prefix inside the bucket

**Comment by ITHcc** [comment]
> you can upload objects with prefixes @ITHcc , it will create the prefix inside the bucket
Thanks for your help. My issue is solved

**Comment by elitan** [comment]
This how you create a folder with the [minio js sdk](https://docs.min.io/docs/javascript-client-api-reference):

```js
minioClient.putObject("nhost", "test/", "");
```

You can also create folders similar to `mkdir -p test2/hello/`:

```js
minioClient.putObject("nhost", "test2/hejsan/", "");
```

where `nhost` is the bucket name.
