### ISSUE TITLE
Support max_keys param for listObjectsV2 

### ISSUE THREAD

**Issue by donnior** [minio/minio-js#800]
https://github.com/minio/minio-js/blob/13831e1ab265c652df7dec826b3185567a47af17/src/main/minio.js#L1375

Currently the `max_keys` is hard coded to `1000`, can we make it as a param for `listObjectsV2`?

**Comment by kannappanr** [comment]
@donnior Can you please elaborate why you need `max_keys` parameter? We generally do not want to add too many options.

**Comment by donnior** [comment]
@kannappanr 

We use Minio to store machine learning data, for example the dataset, usually they are huge; so we need to use paging navigation on web for users; but the default `1000` it's not friend to query with paging;

And also, we checked aws s3 js-sdk， it supports `max_keys`； we really appreciate you cloud consider this requirement, thanks!

**Comment by harshavardhana** [comment]
minio-js lists everything in an iterator @donnior 1000 at a time - are you saying show 1000 elements at a time in slower on UI?

**Comment by kannappanr** [comment]
Closing this issue based on the above comment.
