### ISSUE TITLE
Error when use within an Angular 8 project.

### ISSUE THREAD

**Issue by ng-plex** [minio/minio-js#806]
I'm trying to use within my Angular 8 project but I get the next errors:

```
ERROR in ./node_modules/minio/dist/main/object-uploader.js
Module not found: Error: Can't resolve 'crypto' in 'D:\ng-minio\node_modules\minio\dist\main'
ERROR in ./node_modules/minio/dist/main/transformers.js
Module not found: Error: Can't resolve 'crypto' in 'D:\ng-minio\node_modules\minio\dist\main'
ERROR in ./node_modules/minio/dist/main/signing.js
Module not found: Error: Can't resolve 'crypto' in 'D:\ng-minio\node_modules\minio\dist\main'
ERROR in ./node_modules/minio/dist/main/minio.js
Module not found: Error: Can't resolve 'crypto' in 'D:\ng-minio\node_modules\minio\dist\main'
ERROR in ./node_modules/minio/dist/main/minio.js
Module not found: Error: Can't resolve 'fs' in 'D:\ng-minio\node_modules\minio\dist\main'
ERROR in ./node_modules/mkdirp/index.js
Module not found: Error: Can't resolve 'fs' in 'D:\ng-minio\node_modules\mkdirp'
ERROR in ./node_modules/minio/dist/main/minio.js
Module not found: Error: Can't resolve 'http' in 'D:\ng-minio\node_modules\minio\dist\main'
ERROR in ./node_modules/minio/dist/main/minio.js
Module not found: Error: Can't resolve 'https' in 'D:\ng-minio\node_modules\minio\dist\main'
ERROR in ./node_modules/mime-types/index.js
Module not found: Error: Can't resolve 'path' in 'D:\ng-minio\node_modules\mime-types'
ERROR in ./node_modules/minio/dist/main/minio.js
Module not found: Error: Can't resolve 'path' in 'D:\ng-minio\node_modules\minio\dist\main'
ERROR in ./node_modules/mkdirp/index.js
Module not found: Error: Can't resolve 'path' in 'D:\ng-minio\node_modules\mkdirp'
ERROR in ./node_modules/json-stream/lib/json-stream.js
Module not found: Error: Can't resolve 'stream' in 'D:\ng-minio\node_modules\json-stream\lib'
ERROR in ./node_modules/minio/dist/main/object-uploader.js
Module not found: Error: Can't resolve 'stream' in 'D:\ng-minio\node_modules\minio\dist\main'
ERROR in ./node_modules/minio/dist/main/helpers.js
Module not found: Error: Can't resolve 'stream' in 'D:\ng-minio\node_modules\minio\dist\main'
ERROR in ./node_modules/minio/dist/main/minio.js
Module not found: Error: Can't resolve 'stream' in 'D:\ng-minio\node_modules\minio\dist\main'
ERROR in ./node_modules/xml/lib/xml.js
Module not found: Error: Can't resolve 'stream' in 'D:\ng-minio\node_modules\xml\lib'
ERROR in ./node_modules/xml2js/lib/parser.js
Module not found: Error: Can't resolve 'timers' in 'D:\ng-minio\node_modules\xml2js\lib'
```

How can I do to add to my Angular project as a dependency and use it?

My package.json is composed by:

```
{
  "name": "ng-minio",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "core-js": "^2.5.4",
    "minio": "^7.0.12",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.3",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/minio": "^7.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}
```

Then I use in my app.component.ts as follow:

```
import { Component, OnInit } from '@angular/core';
import * as minio from 'minio';
import { environment } from '../environments/environment';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  title = 'ng-minio';
  public minioClient;

  ngOnInit(): void {
    this.minioClient = new minio.Client({
      endPoint: 'play.min.io',
      port: 9000,
      useSSL: true,
      accessKey: 'Q3AM3UQ867SPQQA43P2F',
      secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
    });
  }

  constructor() {

  }
}
```

**Comment by kannappanr** [comment]
@ng-plex We will take a look and get back to you.

**Comment by mindfocus** [comment]
This means that minio-js supports server mode nodejs and **not** browser mode

**Comment by harshavardhana** [comment]
@mindfocus most definitely that is what we have always told - browser is only advisory support it is not part of the plan to support browser mode fully.

**Comment by xyJen** [comment]
In my project, when i try to upload file object, `putObject` has a error that third argument must be stream or buffer or string. I have to user filereader-stream transfer the file to stream. By the way, s3 `putObject`  can upload file obejct directly. Why not consider supporting browser mode?

**Comment by bingiu** [comment]
Hi @harshavardhana @mindfocus . Did you guys figure out a way to use minio javascript client in the browser ?. If so,  could you let me know the steps on how to use it in a React app.

**Comment by harshavardhana** [comment]
> Hi @harshavardhana @mindfocus . Did you guys figure out a way to use minio javascript client in the browser ?. If so,  could you let me know the steps on how to use it in a React app.

The previous message still holds there is no intention to fully support this in browser, you can still build one locally, but we do not really plan to publish to ship a browser version in the near future

**Comment by bingiu** [comment]
> > Hi @harshavardhana @mindfocus . Did you guys figure out a way to use minio javascript client in the browser ?. If so,  could you let me know the steps on how to use it in a React app.
> 
> The previous message still holds there is no intention to fully support this in browser, you can still build one locally, but we do not really plan to publish to ship a browser version in the near future

Thanks for the response @harshavardhana . Is there any swagger spec which I could use to build my own client ? or is there any example on how to build it ?

**Comment by harshavardhana** [comment]
> > > Hi @harshavardhana @mindfocus . Did you guys figure out a way to use minio javascript client in the browser ?. If so,  could you let me know the steps on how to use it in a React app.
> > 
> > The previous message still holds there is no intention to fully support this in browser, you can still build one locally, but we do not really plan to publish to ship a browser version in the near future
> 
> Thanks for the response @harshavardhana . Is there any swagger spec which I could use to build my own client ? or is there any example on how to build it ? 

We used browserify I think it is `npm run browserify`, we are happy to accept PRs if you can help with swagger spec.

**Comment by loremaps** [comment]
@bingiu minio-js seems to work fine with react. Please have a look here:

https://codesandbox.io/s/react-minio-js-example-9xtgo

**Comment by loremaps** [comment]
In case this helps anyone, this seems related to: angular/angular-cli#1548

There is a workaround by customizing webpack configuration (as explained in the linked issue) and it worked for me: https://github.com/loremaps/ng-minio-crypto/commit/8f2089e05664f66a219df559019794aea60a73a5

But yeah, maybe it is better to stick with nodejs 😄

**Comment by muyuanqiang7** [comment]
i found a solution, git clone node-js repository and run ```npm run browserify```, this will create minio-browser.js.
add ```<script src="assets/minio-brower/minio-browser.js" type="text/javascript"></script>``` to index.html
then you can use `window.MinIO`

**Comment by baphuc1998** [comment]
> i found a solution, git clone node-js repository and run `npm run browserify`, this will create minio-browser.js. add `<script src="assets/minio-brower/minio-browser.js" type="text/javascript"></script>` to index.html then you can use `window.MinIO`

I tried but seems it doesn't work :((. Do you have any other way?

**Comment by cfmj** [comment]
> 我找到了一个解决方案，git clone node-js 存储库并运行`npm run browserify`，这将创建 minio-browser.js。 添加`<script src="assets/minio-brower/minio-browser.js" type="text/javascript"></script>`到 index.html 然后你可以使用`window.MinIO`

Can you describe it in detail? Thank you.

**Comment by prakashsvmx** [comment]
https://github.com/minio/minio-js/issues/1053#issuecomment-1196291784

Please have a look and make adjustments to the build config of the project.

**Comment by lmq352489099** [comment]
Does Vite support Minio client now ??

**Comment by Nierifeng** [comment]
> Vite 现在支持 Minio 客户端了吗？？

Have you solved it yet
