### ISSUE TITLE
`listObjects` function return Stream doesn't emitting `finish` event

### ISSUE THREAD

**Issue by wisn** [minio/minio-js#809]
From what I seen, `listObjects` function on the `src/main/minio.js` file doesn't emitting `finish` event.
The problem is that I want to know whether the stream event is finished.

```js
function objects(attachment = {}) {
  const { minio, logger } = attachment;

  const ret = async (attributes = {}) => {
    const { bucketName } = attributes;
    const prefix = attributes.prefix || '';
    const recursive = attributes.recursive === true;

    const promise = new Promise((resolve, reject) => {
      const stream = minio.listObjects(bucketName, prefix, recursive);
      const objects = [];

      stream.on('data', obj => objects.push(obj));
      stream.on('error', err => {
        logger.error(err);

        reject(err);
      });
      stream.on('finish', () => resolve(objects));
    });

    return promise;
  };

  return ret;
}
```

I want to collect the available objects on the specific bucket.
After all objects completely collected, I want to `return` them.

Based on the code above, the promise will be always pending since the `resolve` is executed in the `finish` event. However, `finish` event never reached.

**Comment by imyller** [comment]
Try ```stream.on('end', () => resolve(objects));```

`end` and `finish` are the same event but on different types of Streams:
* stream.Readable fires only `end` and never `finish`
* stream.Writable fires `finish` and never `end`

**Comment by wisn** [comment]
@imyller Thanks to pointing this out. After created this issue, in several minutes later, I actually tried to use `end` event and it is works just fine. Thanks to you now I know the difference between those two.
I think we can close this issue.
