### ISSUE TITLE
How to get the MinIO server version?

### ISSUE THREAD

**Issue by maertv** [minio/minio-js#810]
It is possible that I missed it while reading the documentation but I did not find a way how to get the MinIO server version via the JavaScript client.

**Comment by harshavardhana** [comment]
Each request that you send to server - server returns back with `Server:` header which contains server information.

Let's take more questions at https://slack.min.io

**Comment by maertv** [comment]
> Each request that you send to server - server returns back with `Server:` header which contains server information.
> 
> Let's take more questions at https://slack.min.io

Thank you for your prompt reply.

**Comment by SamuelHassine** [comment]
Hello, @harshavardhana, I re-open this issue, it seems on the latest version of Minio the header "Server" is just "MinIO", no more version number. Is that normal?

Thanks for your answer.

Kind regards,
Samuel
