### ISSUE TITLE
Create New user from MinioClient Python SDK

### ISSUE THREAD

**Issue by gouravbns** [minio/minio-js#814]
I have looked at the whole documentation of Minio and couldn't find method to add new user from Python SDK.
can you please tell me the status for the same.

#Minio #Python #adduser

**Comment by harshavardhana** [comment]
Not possible from python SDK, we may implement perhaps in future for now use `mc` . Closing this issue.

**Comment by optimus-kart** [comment]
is this still the case?

**Comment by prakashsvmx** [comment]
@optimus-kart  Please use https://github.com/minio/madmin-go for all admin APIs. there are no other language specific implementation . may be mino-java has some references for few of the admin APIs.

**Comment by optimus-kart** [comment]
@prakashsvmx are there are REST API docs available for admin apis incase we want to implement any clients on our own? o
