### ISSUE TITLE
Canned policy not applied when using AssumeRoleWithClientGrants and JS SDK

### ISSUE THREAD

**Issue by GuillaumeNachury** [minio/minio-js#818]
## Expected Behavior

When using the JS SDK to sign in a client with temp. credentials - token and policy provided by keycloak- the policy should be applied no matter if it is a  **default** or a **custom** one.

## Current Behavior

When using default policy e.g. `readwrite` everything is ok (I can list the buckets) but when I set the policy to `restricted` (a custom policy I created) I have a `S3Error: Access Denied.` message.
Notice that the custom policy is correctly applied when using the OpenID button on the Minio browser.

## Steps to Reproduce (for bugs)

1. Create a user with a custom policy in Keycloak
2. Get the Token from Keycloak for the user
3. Use the AssumeRoleWithClientGrants to get temp credentials
4. Use the JS SDK the list the buckets
=>  `S3Error: Access Denied.`

## Your Environment

* Version used (`minio version`): docker minio/minio:edge
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): windows
* Link to your project:

**Comment by GuillaumeNachury** [comment]
Ok, but I don't really understand your reply. 
Beside from the issue I'm facing, I can get the JS SDK working with STS. I mean as long as I use default policy.

**Comment by harshavardhana** [comment]
> Ok, but I don't really understand your reply.
> Beside from the issue I'm facing, I can get the JS SDK working with STS. I mean as long as I use default policy.

JS SDK cannot work with STS yet @GuillaumeNachury in future it will but not right now.

**Comment by GuillaumeNachury** [comment]
Thank you @harshavardhana . 
Can you point me a MinioSDK that supports STS ?

**Comment by harshavardhana** [comment]
@GuillaumeNachury https://github.com/minio/minio-go/blob/master/pkg/credentials/sts_client_grants.go

**Comment by harshavardhana** [comment]
> My problem is not to retrieve **AccessKeyID** / **SecretAccessKey** / **SessionToken** but to Initialize a Minio client (with those key/secret/token) with the correct policy applied.
> 
> So what you mean from your previous reply ( [#818 (comment)](https://github.com/minio/minio-js/issues/818#issuecomment-575066082) ) is by using the Go client API https://docs.min.io/docs/golang-client-api-reference I shouldn't got the issue. Am I right ?

in minio-js that's not allowed in minio-go it is allowed using the credential.Credentials structure look at the method *minio.NewWithCredentials*

**Comment by GuillaumeNachury** [comment]
Perfect.
Thank you.

**Comment by prakashsvmx** [comment]
@GuillaumeNachury  please have a look at : https://github.com/minio/minio-js/pull/960
