### ISSUE TITLE
Support listObjectsV2WithMetadata

### ISSUE THREAD

**Issue by Nepoxx** [minio/minio-js#822]
It would be great to have support for the minio-specific extension `ListObjectsV2WithMetadata` that was merged recently: https://github.com/minio/minio/pull/8539

Also: https://godoc.org/github.com/minio/minio-go#Client.ListObjectsV2WithMetadata

Cheers!

**Comment by harshavardhana** [comment]
@Nepoxx it is not implemented on purpose, it is an extension API and only meant to be used by specific application requirements such as `mc`

minio-js scope doesn't include that - feel free to implement it yourself by forking the project.

**Comment by Nepoxx** [comment]
Would you be open to having an extension namespace within this project so that extensions are available but it is made clear to the end user that they are extensions?

Something like:

```js
minioClient.makeBucket(...) // regular
minioClien.extensions.listObjectsV2WithMetadata(...) // extension
```

**Comment by harshavardhana** [comment]
> ```js
> minioClient.makeBucket(...) // regular
> minioClien.extensions.listObjectsV2WithMetadata(...) // extension
> ```

That is acceptable would you able to send the PR ? @Nepoxx

**Comment by Nepoxx** [comment]
@harshavardhana I'll look into it this week or next week :)

**Comment by Max9419** [comment]
This should be closed @harshavardhana

**Comment by prakashsvmx** [comment]
@Max9419  thank you. I will close this.
