### ISSUE TITLE
minio-js doesn't support session token based presigned URL

### ISSUE THREAD

**Issue by fcomte** [minio/minio-js#829]
Hello,

Minio JS does not support session token presigned url 
This code does not work... the url generated don't have a token.

`var s3Client = new Minio.Client({
  endPoint: 'myminio.domain',
  accessKey: 'X',
  secretKey: 'Y',
  sessionToken: 'Z',
  useSSL: false // Default is true.
})
// Presigned get object URL for my-objectname at my-bucketname, it expires in 7 days by default.
var presignedUrl = s3Client.presignedGetObject('tm8enk', 'file', 1000, function(e, presignedUrl) {
  if (e) return console.log(e)
  console.log(presignedUrl)
})`

`http://myminio.domain/tm8enk/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=PB7Q16DM932BW65NRYJC%2F20200214%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200214T102516Z&X-Amz-Expires=1000&X-Amz-SignedHeaders=host&X-Amz-Signature=bdf009f6c6b3a85f39e2d7253a62d60dbf30ee86fd23cc5c68028d96eb846e68`

This would be helpful to me if it could work ..

**Comment by fcomte** [comment]
You just released 7.0.14 but it does not solve this issue in fact. 7.0.14 did not generate an URL containing a sessionToken

**Comment by harshavardhana** [comment]
Please paste a test program @fcomte

**Comment by harshavardhana** [comment]
Please paste a test program @fcomte

**Comment by fcomte** [comment]
I used the same : 

`var s3Client = new Minio.Client({ endPoint: 'myminio.domain', accessKey: 'X', secretKey: 'Y', sessionToken: 'Z', useSSL: false // Default is true. }) // Presigned get object URL for my-objectname at my-bucketname, it expires in 7 days by default. var presignedUrl = s3Client.presignedGetObject('tm8enk', 'file', 1000, function(e, presignedUrl) { if (e) return console.log(e) console.log(presignedUrl) })`

**Comment by harshavardhana** [comment]
Reopening to investigate

**Comment by olevitt** [comment]
I just tested the new PR and #832 fixes it for us.  
Thanks a lot !
