### ISSUE TITLE
cannot find any api to set lifecycle policy

### ISSUE THREAD

**Issue by hamedminaee** [minio/minio-js#831]
Hi,

I am using nodejs and trying to set a lifecycle policy for minio. 
However it seems there is no way to set a lifecycle policy with this library.
Is there any way we can set lifecycle policy?

For example similar code in golang:

```
`lifecycle := `<LifecycleConfiguration>
 <Rule>
   <ID>expire-bucket</ID>
   <Prefix></Prefix>
   <Status>Enabled</Status>
   <Expiration>
     <Days>365</Days>
   </Expiration>
 </Rule>
</LifecycleConfiguration>`

err = minioClient.SetBucketLifecycle("my-bucketname", lifecycle)
if err != nil {
    fmt.Println(err)
    return
}`
```

**Comment by kannappanr** [comment]
@hamedminaee We do not have that API implemented yet. Please feel free to send a PR
