### ISSUE TITLE
Overwrite header host when making resigned URL

### ISSUE THREAD

**Issue by b4nst** [minio/minio-js#833]
Is your feature request related to a problem? Please describe.

Currently it is not possible to change the host of the generated presigned url. This could be useful in many cases like this one :

A gateway running inside a docker container, communicating with Minio server through docker network (http://minio:9000) will generate a presigned url with minio:9000 link. But the final user will use the Minio public endpoint to use this link.

Describe the solution you'd like
To be able to overwrite the host option through presignedUrl function, which is already used and implemented.

Describe alternatives you've considered
Setting Minio public endpoint inside the gateway (not ideal in terms of network isolation, and do not work on local stacks)

**Comment by kannappanr** [comment]
There is one way to do this

```
var Minio = require('minio')

var s3Client = new Minio.Client({
  endPoint: 'my.example.com',
  accessKey: 'minio',
  secretKey: 'minio123',
  useSSL: true, // Default is true.
  region: 'us-east-1'
})

// Presigned get object URL for my-objectname at my-bucketname, it expires in 7 days by default.
var requestDate = new Date('2020-03-01');
var presignedUrl = s3Client.presignedUrl('GET', 'test', 'issue', 24*60*60, function(err, presignedUrl) {
  if (err) return console.log(err)
  console.log(presignedUrl)
})
```
You generate a url like this
```
curl -v --header "HOST: my.example.com" "https://play.min.io/test/issue?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20200301%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200301T153549Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=2a14a9679a38b59e5ed1c2ad42c2ab250d2bf4e807dd615baa2d7db11d1de141"
```
Since the sdk uses the endpoint used to generate the host header signature, we can use the host header you want to use instead of the endpoint you want to connect to. Then replace `my.example.com` with `play.min.io` and add `my.example.com` as the host header while issuing the curl command
https://my.example.com/test/issue?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20200301%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200301T153549Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=2a14a9679a38b59e5ed1c2ad42c2ab250d2bf4e807dd615baa2d7db11d1de141
```
You replace the endpoint to say `play.min.io`

and issue a curl command like this

```

**Comment by harshavardhana** [comment]
@kannappanr thanks this is the correct approach.. there is no reason to do this in our SDK. 

It is meant to be used in the manner you described.

**Comment by b4nst** [comment]
Thanks @kannappanr, this is a working solution. However I think that forcing the end user to know about your internal network architecture is a bad approach (both in term of security and usability).

Let me know if you change your mind in the future.

**Comment by b4nst** [comment]
Update: The solution with the header does not work. It returns a 404 not found

**Comment by harshavardhana** [comment]
@b4nst we cannot do these type of infrastructure overrides in our SDK - you should use the right endpoint with the MinioClient constructor to generate the correct presigned URL as needed.

@kannappanr lets close this issue, we have closed similar issues in the past as well.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-js/issues/514 is the previous issue on something similar.

**Comment by kannappanr** [comment]
@b4nst Closing this issue based on the previous comment.

**Comment by christianechevarria** [comment]
> @kannappanr thanks this is the correct approach.. there is no reason to do this in our SDK.
> 
> It is meant to be used in the manner you described.

I see it's a wontfix on the original issue, is there a recommended workaround for this? 

> However I think that forcing the end user to know about your internal network architecture is a bad approach (both in term of security and usability).

I think @b4nst is absolutely right, it takes time to first discover the nature of the problem and then a fair amount of effort / research to create / find a workaround to resolve what is fundamentally a design decision

**Comment by christianechevarria** [comment]
I was chatting with someone on the MinIO slack and apparently there's a `withProxy` parameter in the c# and golang libraries that allows for a simple workaround to this. It would work something like this:

let Minio = require('minio')

const minioClientConfig = {
  endPoint: "localhost",
  port: 9000,
  useSSL: true,
  accessKey: MINIO_ACCESS_KEY,
  secretKey: MINIO_SECRET_KEY,
  withProxy: "minio:9000",
}
