### ISSUE TITLE
S3 Error malformed XML for removeObjects with non-Latin characters

### ISSUE THREAD

**Issue by loremaps** [minio/minio-js#836]
If we use Greek or Chinese  characters in object names,  all methods work except the `removeObjects` (even `removeObject` works). The error is:

```
S3Error: The XML you provided was not well-formed or did not validate against our published schema. (XML syntax error on line 1: unexpected EOF)
```

From my investigation so far, if I use a filename like `fileΩ` the error occurs here:

https://github.com/minio/minio-js/blob/465caae4606f6647837a3c778faf6652ece5c4dd/src/main/minio.js#L1501

The payload is `"<Delete><Quiet>true</Quiet><Object><Key>fileΩ</Key></Object></Delete>"`

But then I run out of time debugging 😞

**Comment by nitisht** [comment]
Thanks for reporting, @loremaps we'll take a look

**Comment by keeneagle** [comment]
We also met the issue, when can this issue be fixed?

**Comment by harshavardhana** [comment]
@keeneagle feel free to send a fix, this is a lower priority issue for us at this moment.
