### ISSUE TITLE
Default region should be configurable

### ISSUE THREAD

**Issue by innovate-invent** [minio/minio-js#837]
https://github.com/minio/minio-js/blob/b859a0360d422eea54b546e92477f2c7cf314b68/src/main/minio.js#L561

I would prefer that the default region be configurable in the constructor.
The constructor already has a region parameter, should it default to that or should a `defaultRegion` parameter be added?

**Comment by harshavardhana** [comment]
just use the required region in the constructor

**Comment by innovate-invent** [comment]
> just use the required region in the constructor

This function doesn't make use of that variable other than validation:
https://github.com/minio/minio-js/blob/b859a0360d422eea54b546e92477f2c7cf314b68/src/main/minio.js#L515-L563

**Comment by innovate-invent** [comment]
@harshavardhana please remove the 'working as intended' tag as the code does not reflect the intended functionality

**Comment by harshavardhana** [comment]
@innovate-invent it does, that's why its kept as is.  makeBucket is meant to take custom region not default to the constructor.

**Comment by innovate-invent** [comment]
How do you make buckets in the constructor specified region without calling makeBucket?

**Comment by harshavardhana** [comment]
> How do you make buckets in the constructor specified region without calling makeBucket?

Pass the same region in MakeBucket!

**Comment by innovate-invent** [comment]
haha, the point is to provide a default in the constructor so I don't have to pass it around in the code.

**Comment by harshavardhana** [comment]
> haha, the point is to provide a default in the constructor so I don't have to pass it around in the code.

makeBucket is allowed to create buckets for different regions regardless of your default region in the constructor, so the code is nothing different. You can pass it just as you did for your constructor since you wish to keep this as default.

makeBucket is special so it is treated as a special operation.

**Comment by innovate-invent** [comment]
Yes, but that requires passing the region variable to every piece of code that calls makebucket.
Why not just provide a means of setting a default for each client instance?
This just adds pollution to every function signature that accepts a client object.

**Comment by harshavardhana** [comment]
I don't think that is idiomatic in nature because `makeBucket()` without region means its `us-east-1` not your constructor default region.  This is to behave as per S3 spec.

makebucket is a rare operation so if you are doing it frequently you have an architectural issue.

**Comment by innovate-invent** [comment]
It isn't that I am calling it frequently, it is that I am calling it several layers deep in the call stack compared to the instantiation of the client.
If it is simply a matter of strictly adhering to a specification, then I guess there is nothing to be done.
