### ISSUE TITLE
InvalidEndpointError for valid url

### ISSUE THREAD

**Issue by fernard** [minio/minio-js#838]
Hello, I'm trying to setup the minio client for a given url, which has the following form:

```
const minioClient = new Minio.Client({
    endPoint: 'myexample.co.uk/minio/mybucketname',
    accessKey: process.env['MINIO_USERNAME_ENV'],
    secretKey: process.env['MINIO_PASSWORD_ENV'],
});
```

I get a InvalidEndpointError when running the script. Why does the validation method fail on this url pattern?

**Comment by vadmeste** [comment]
@fernard, hello.

You should not put any path in the endpoint field, only the host name.

Also would you mind join https://slack.min.io ? you can ask any question there
