### ISSUE TITLE
Support IAM for Service Account

### ISSUE THREAD

**Issue by Jeffwan** [minio/minio-js#841]
aws add [IAM For Service Account](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) feature. It uses Web Identity Credentials and this is not support in minio-js yet. It would be better to bump SDK version or add this resolver. 

minio-go changes: https://github.com/minio/minio-go/pull/1183

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/WebIdentityCredentials.html

**Comment by kannappanr** [comment]
Please feel free to send a PR @Jeffwan

**Comment by Vaneste** [comment]
Definitely needed !

**Comment by karlschriek** [comment]
Is anyone able to take this up? @Jeffwan made the needed changes for minio-go, but we still need this for minio-js.

**Comment by prakashsvmx** [comment]
@karlschriek  @Jeffwan  Please have a look at : PR #960
