### ISSUE TITLE
403 error when trying to retrieve a file (image - 1mb)

### ISSUE THREAD

**Issue by Michael6493** [minio/minio-js#843]
I am trying to get minio retrieving an image from a bucket from a nodejs backend.
It can access the bucket, as it gives me an error if I change the bucket name.
This error in the console when requesting this endpoint says" [HTTP/2 504 Gateway Timeout 62150ms]

With port set to 443 I get this error instead:
    **Incomplete response received from application**

```
var Minio = require('minio')

const port = 443

var minioClient = new Minio.Client({
    endPoint: 'example.example.com',
    port: 9000,
    useSSL: true,
    accessKey: example,
    secretKey: example,
});

app.get('/test', (req, res) => {
    var size = 0
    minioClient.getObject('bucketname', 'folderName/imageName.png', function(err, dataStream) {
      if (err) {
        return console.log(err)
      }
      dataStream.on('data', function(chunk) {
        size += chunk.length
      })
      dataStream.on('end', function() {
        console.log('End. Total size = ' + size)
        res.send(dataStream)
      })
      dataStream.on('error', function(err) {
        console.log(err)
      })
    })
})
```
 
## Expected Behavior
I expect a result sent back to the browser with the image stream so I can make the image show om the screen. Right now it is giving me a 504 gateway timeout issue. The image is 1.3mb and my internet connection is at least 60mbps so I don't think it is that as it takes quite a few seconds before I even see the error as it freezes first while waiting.

## Your Environment

* Version used is the latest installed via npm
* Environment name
Nodejs latest, nginx latest.

**Comment by kannappanr** [comment]
I moved the issue to `minio-js` repo.

Can you please try downloading an image or another object of similar size from `play`

I have given a sample code here

```
var Minio = require('minio')

var s3Client = new Minio.Client({
  endPoint: 'play.min.io',
  accessKey: 'minio',
  secretKey: 'minio123'
})

var size = 0
// Get a full object.
s3Client.getObject('test', 'issue', function(e, dataStream) {
  if (e) {
    return console.log(e)
  }
  dataStream.on('data', function(chunk) {
    size += chunk.length
  })
  dataStream.on('end', function() {
    console.log("End. Total size = " + size)
  })
  dataStream.on('error', function(e) {
    console.log(e)
  })
})
```
Then you can try the same against your MinIO backend with and without the nginx

**Comment by munkhorgil** [comment]
@kannappanr, How to get dataStream buffer along with size?

**Comment by kannappanr** [comment]
@Michael6493 Closing this issue as stale. Please feel free to reach out to us when you have more information
