### ISSUE TITLE
Support for selectObjectContent

### ISSUE THREAD

**Issue by lchayoun** [minio/minio-js#846]
As supported in the Java SDK:
https://docs.min.io/docs/java-client-api-reference.html#selectObjectContent

**Comment by kannappanr** [comment]
@lchayoun Please feel free to send a PR. We welcome community contributions.

**Comment by sasanksasi** [comment]
Please release this change it is very important.

**Comment by prakashsvmx** [comment]
@lchayoun , @sasanksasi  PR #846 has been created to implement this. PTAL.
