### ISSUE TITLE
putObject does not work in browser to upload file 

### ISSUE THREAD

**Issue by hanu18** [minio/minio-js#855]
I am using MinIO JS SDK in my React App
I want to upload a file using MinIO JS SDK which is not possible without any  SSR
but S3 SDK provides a feature to upload a file directly from the browser using `"s3.upload"`
I need a similar kind of behavior in MinIO SDK as well.

While using `"minioClient.putObject"` it used fs which is not accessible in React environment 
Please help in this scenario, its kind of a must to have feature in JS SDK  

please do let me know if any more details required from my side

**Comment by disarticulate** [comment]
You probably need a fs shim.

https://github.com/jvilk/BrowserFS

**Comment by dianamariand92** [comment]
Hi @hanu18,

I have the same problem. Could you find a solution? Thanks

**Comment by prakashsvmx** [comment]
@hanu18  did you try https://github.com/harshavardhana/minio-js-browser-upload ?

**Comment by prakashsvmx** [comment]
@hanu18  Please find a working sample https://github.com/prakashsvmx/minio-js-web-browser-example ( test with local minio server )
