### ISSUE TITLE
Error when using minio-js in ant design , TypeError: _fs.default.stat is not a function

### ISSUE THREAD

**Issue by cloudtry** [minio/minio-js#858]
## An error occurs when I use minio-js in the ant design project, the error message is TypeError: _fs.default.stat is not a function

![{4EDE6528-708C-49AA-B941-8752A6F83B62}_20200702144145](https://user-images.githubusercontent.com/38524062/86325152-303fc280-bc72-11ea-82f6-5a0d779ebb07.jpg)

**Comment by kannappanr** [comment]
@cloudtry minio-js is not supported on browser. Can you provide a reproducer for us to take a look?

**Comment by cloudtry** [comment]
@kannappanr  I got this error when using minio-js in the react framework of "ant design". I'm not sure if this is the case in all minio-js projects. PS: my browser is chrome

**Comment by cloudtry** [comment]
my code is the example you provided

like this
```js
var Minio = require('minio')

var minioClient = new Minio.Client({
    endPoint: 'play.min.io',
    port: 9000,
    useSSL: true,
    accessKey: 'Q3AM3UQ867SPQQA43P2F',
    secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
});

minioClient.fPutObject('xxx', 'xxxx.png', file, metaData, function(err, etag) {
      if (err) return console.log(err)
      console.log('File uploaded successfully.')
});
```

**Comment by harshavardhana** [comment]
> my code is the example you provided
> 
> like this
> 
> ```js
> var Minio = require('minio')
> 
> var minioClient = new Minio.Client({
>     endPoint: '127.0.0.1',
>     port: 9000,
>     useSSL: false,
>     accessKey: 'minioadmin',
>     secretKey: 'minioadmin'
> });
> 
> var metaData = {
>   'Content-Type': 'image/png',
> }
> 
> minioClient.fPutObject('xxx', 'xxxx.png', '~/xxxx.png', metaData, function(err, etag) {
>       if (err) return console.log(err)
>       console.log('File uploaded successfully.')
> });
> ```

fputObject doesn't work on browsers @cloudtry it requires filesystem access. You need to use putObject

**Comment by kannappanr** [comment]
@cloudtry closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for further questions
