### ISSUE TITLE
Versioning Support

### ISSUE THREAD

**Issue by charleshall888** [minio/minio-js#863]
I see versioning support has been added for the Java SDK, but still not for the JavaScript SDK. I would imagine that JS is used by many users of Minio with the popularity of NodeJS. My team is depending on the versioning support for the JS SDK and would like to not have to add the support ourselves.
Is there a timeline for when/if the support will be added?

**Comment by kayotimoteo** [comment]
I would like the functionality, to think that after being made available on the core, it would be made available on all sdk's but I didn't see it happen 😕

**Comment by harshavardhana** [comment]
> I would like the functionality, to think that after being made available on the core, it would be made available on all sdk's but I didn't see it happen

We are working the best we can with the amount of time with multiple things. It is beneficial if community members such as yourself send us a PR instead. 

If you need a prioritized work you are more than welcome to get our subscription to steer our directions @kayotimoteo

**Comment by kayotimoteo** [comment]
@masihjahangiri, Sorry I think I expressed myself badly, that was not my intention, I know how things are. Unfortunately for the time being I don't have an advanced skill in JS, but I recognize the work of the community and I don't have a priority, I work with what I have and that already suits me very well. Hugs.

**Comment by prakashsvmx** [comment]
@charleshall888 @kayotimoteo  Versioning support has been merged in master. Please have a look.

**Comment by prakashsvmx** [comment]
Please test with the latest version.7.0.20. @charleshall888  @kayotimoteo
