### ISSUE TITLE
removeObjects causes malformed XML error when using German umlauts

### ISSUE THREAD

**Issue by orangefoil** [minio/minio-js#864]
Calling removeObjects with objects that have UTF-8 encoded German umlauts (äöüÄÖÜ) in the name you get the error `S3Error: The XML you provided was not well-formed or did not validate against our published schema.`  
Deleting a single object using removeObject works just fine.

This is likely related to #836 which is was closed. But as of version 7.0.16 there are still problems with unicode filenames. The error can also still be recreated using Greek letters (such as ΩΣβ).

**Comment by vadmeste** [comment]
We fixed a similar issue in minio-go. The only way to fix this is to send separate DeleteObject S3 calls inside removeObjects() when removing objects with names containing unsupported characters in XML.

**Comment by orangefoil** [comment]
> We fixed a similar issue in minio-go. The only way to fix this is to send separate DeleteObject S3 calls inside removeObjects() when removing objects with names containing unsupported characters in XML.

Thanks for your suggestion, that's also what I'm doing right now.
However I consider that a workaround and not a fix. That's why I opened this issue.

**Comment by vadmeste** [comment]
> However I consider that a workaround and not a fix. That's why I opened this issue.

I meant we should make switching between single and multi remove transparent in removeObjects() js API.

**Comment by loremaps** [comment]
Hi @orangefoil the fix for #836 was released in `7.0.17`. If you upgrade it should work with German umlauts too.

**Comment by ebozduman** [comment]
@orangefoil ,

Please upgrade and let us know if your issue is already addressed by PR#847 introduced to address issue #836.
If you agree, please close the bug.
I marked this bug as duplicate of issue #836.

**Comment by orangefoil** [comment]
> @orangefoil ,
> 
> Please upgrade and let us know if your issue is already addressed by PR#847 introduced to address issue #836.
> If you agree, please close the bug.
> I marked this bug as duplicate of issue #836.

Thanks for coming back to me. This issue is indeed resolved in version 7.0.17. Thanks everyone!
