### ISSUE TITLE
listObjects and ListBuckets  ETIMEDOUT 

### ISSUE THREAD

**Issue by duard** [minio/minio-js#865]
I aways get ETIMEDOUT 

```
ERRAMS =>  Error: connect ETIMEDOUT 134.70.84.3:9000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '134.70.84.3',
  port: 9000
}
=> Erro ao listar buckets Error: connect ETIMEDOUT 134.70.84.3:9000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '134.70.84.3',
  port: 9000
}
```

`  @Override()
  async getMany(@ParsedRequest() req: CrudRequest, @Query() query) {
    console.log('\n\n\n\n 0=>', 'Checkpoint -----------------------------');

    const s3Client = new Client({
      endPoint: 'goiabada-3d.sincero.objectstorage.sa-saopaulo-1.oraclecloud.com',
      port: 9000,
      useSSL: true,
      accessKey: 'kjfhasdkjfhadklsfhkadlsfhdksajfhklasdjfhaklsdjhfjklasdhfkajfhdskjl',
      secretKey: 'd78fa9sd876fad9s087f9asd78fy09asd78f',
    });

    var params = {
      Bucket: 'blutecqa',
      Delimiter: '/',
      Prefix: 'foldername/',
    };

    **const stream = await s3Client.listObjectsV2(params.Bucket,  '', true,'');**

    stream.on('data', obj => {
      console.log('DATA => ', JSON.stringify(obj, null, 2));
    });
    stream.on('error', err => console.error('ERRAMS => ', err));

    stream.on('end', fim =>  {
      console.log('END => ', fim);
    });

    console.log('\n\n\n\n 1=>', 'Checkpoint -----------------------------');

    **await s3Client.listBuckets((e, buckets)** => {
      if (e) return console.log('=> Erro ao listar buckets', e);
      console.log('buckets encontrados:', buckets);
    });

    console.log('\n\n\n\n 2=>', 'Checkpoint -----------------------------');

    return this.base.getManyBase(req);
  }`

**Comment by dropbox99** [comment]
what is the conclusion dude ??? i need to know this!

**Comment by prakashsvmx** [comment]
@dropbox99 
could you try
`minioClient.setRequestOptions({timeout:<xxxx>})`

**Comment by ganeshgrandhi** [comment]
Yes, I also need to know this how its solved. Can you help me @duard ?
