### ISSUE TITLE
Extracting the bucket region is an object,throwing an error

### ISSUE THREAD

**Issue by stringang** [minio/minio-js#868]
I'm using my local minio service to run this repository example(examples/bucket-exists.js). The program is terminated with an error.

error message：
```
TypeError: region should be of type "string"
    at signV4 (/*/signing.js:236:11)
    at _makeRequest (/*/minio.js:499:51)
    at DestroyableTransform.<anonymous> (/*/minio.js:564:11)
    at DestroyableTransform.emit (events.js:315:20)
....
```
I debugged and found that the program was terminating because the `extractRegion` method was receiving `data` as an object type

source code:
```
var extractRegion = (response) => {
      var transformer = transformers.getBucketRegionTransformer()
      var region = 'us-east-1'
      pipesetup(response, transformer)
        .on('error', cb)
        .on('data', data => {
          if (data) region = data  // fault point, data is an object type
        })
        .on('end', () => {
          this.regionMap[bucketName] = region
          cb(null, region)
        })
    }
```

Received `data` format:

```
{
  "Name": [
    "xxxx"
  ],
  "Prefix": [
    "xxxxx"
  ],
  "Marker": [
    ""
  ],
  "MaxKeys": [
    "1"
  ],
  "IsTruncated": [
    "false"
  ],
  "EncodingType": [
    "url"
  ]
}
```

**When I construct the minio client, add the `region` parameter and the example works fine!!!**

```
var s3Client = new Minio.Client({
  endPoint: 'localhost',
  accessKey: '*',
  secretKey: '*',
  region: 'us-east-1'
})
```

**Comment by stringang** [comment]
source code:

```
var _makeRequest = (e, region) => {
  ...
  var authorization = signV4(reqOptions, this.accessKey, this.secretKey, region, date)
  ...
}
```

the `signv4` method validation parameter throws an error and the process is terminated.

should the error be called back instead of letting the process end?

**Comment by kannappanr** [comment]
@stringang We are unable to reproduce the issue. Tried it with and without the region being set. Can you please let us know the version of MinIO, the mode in which it is being run, the command line parameters used, environment variables used if any. output of `mc admin config export myminio` . Version of minio-js in use. Finally, are you able to reproduce this against `play.min.io`?

**Comment by stringang** [comment]
I can't reproduce the issue even now. It's really amazing.

I will close the issue first. If I can reproduce it, I'll open it again.
