### ISSUE TITLE
Minio JS API presigned url duration not working!!

### ISSUE THREAD

**Issue by thomaslc66** [minio/minio-js#874]
## Expected Behavior

When I set a duration on a pre-signed URL, the URL should not work when this duration is expired.

Please make sure the duration is handled correctly

## Current Behavior

When I set the duration of the presignedGetObject method to 5 sec, the file can still be accessed even 10 minutes after.

Current behavior doesn't handle the duration properly

## Steps to Reproduce (for bugs)

create a js file and connect it to your client.
Then using the presignedGetObject method pass a bucketname a filename and a small number in sec (in my example 5 sec).
Simply print the output in a console log.
Copy paste the URL in you web browser. If you've taken more than five sec to do this, the file should not be downloaded. 
But you will see that you will be able to download it even after several minutes.

````
const client = new Minio.Client({
            endPoint: this.exoscaleConfig.endpoint,
            useSSL: this.exoscaleConfig.useSSL,
            accessKey: this.exoscaleConfig.access_key,
            secretKey: this.exoscaleConfig.secret_key
});

console.log(client.presignedGetObject(bucketId, fileName, duration))
````

## Context

Clearly a security issue if my files can be downloaded even week after.
I was trying to use presigned URL of 3 to 5 seconds to let the user download a sensitive file to his computer and then make the link useless to a possible attacker.

User click on a download button, backend generate the presigned URL, send it to front-end, front end use it to download the secured file. When the download is done the link would be expired.

## Your Environment

* Version used (`minio --version`): 7.0.16
* Server setup and configuration: node 14.15.0
* Operating System and version (`uname -a`): localhost windows 10 machine

**Comment by prakashsvmx** [comment]
This is working as expected . 
Sample project URL:
`https://github.com/prakashsvmx/minio-js-web-browser-example`

  ```javascript
//ListObjects.js Line 38 : update as per your needs. it should be minimum 1 second. in the sample project
const presignedUrl = await minioClient.presignedGetObject(bucketName, objectName, 5) //5 seconds
```

The error when downloading after 5 seconds is:
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<Key>MyFile</Key>
<BucketName>test-bucket</BucketName>
<Resource>/test-bucket/MyFile</Resource>
<RequestId>169BBCA479286292</RequestId>
<HostId>be958c7f-a4a0-4850-9f1e-923f1f29d86e</HostId>
</Error>
```
