### ISSUE TITLE
ERROR: xmlobj.CommonPrefixes.forEach is not a function

### ISSUE THREAD

**Issue by HeJueting** [minio/minio-js#876]
**minio version：^7.0.17**

</br>

 found this problem when I used the **listobjects** API

1、When the third parameter recursive of listobjects is set to true, the result returned is correct
```javascript
// code
const bucketName = params.bucketName || '';
const prefix = params.prefix || '';
const stream = app.minio.listObjects(bucketName, prefix, true);
return new Promise(resolve => {
    const res = [];
    stream.on('data', obj => {
        res.push(obj);
    });
    stream.on('end', () => {
        resolve({
            code: 0,
            data: res,
        });
    });
    stream.on('error', err => {
        resolve({
            code: 1,
            msg: err,
        });
    });
});

// result
[
    {
        "name":"child/aa.txt",
        "lastModified":"2020-12-01T04:04:18.148Z",
        "etag":"166bcae2d953f92b1fa3b40d218d2a38",
        "size":57
    },
    {
        "name":"bb.jpg",
        "lastModified":"2020-12-01T02:39:41.026Z",
        "etag":"ba02b3771a3ceeaf1d4925c62d05780b",
        "size":8730
    },
    {
        "name":"cc.jpg",
        "lastModified":"2020-12-01T02:40:21.905Z",
        "etag":"aed69181e64900aeaaf4b18798c7bcc4",
        "size":10891
    }
]
```

2、However, when the third parameter recursive is set to false, an error is reported

```javascript
// code
app.minio.listObjects(bucketName, prefix, false);
......

// result
ERROR: xmlobj.CommonPrefixes.forEach is not a function
```

I entered the wrong node_ modules\minio\dist\main\xml- parsers.js:381 : 27 files, printing xmlobj.CommonPrefixes The results are as follows：
```javascript
// Error source code
if (xmlobj.CommonPrefixes) {
    console.log('xmlobj.CommonPrefixes', xmlobj.CommonPrefixes);
    xmlobj.CommonPrefixes.forEach(function (commonPrefix) {
        var prefix = commonPrefix.Prefix[0];
        var size = 0;
        result.objects.push({
            prefix,
            size
        });
    });
}

// console.log result
xmlobj.CommonPrefixes { Prefix: 'child/' }
```

**Comment by ebozduman** [comment]
@HeJueting,

I tried to reproduce the issue and no matter what I tried, could not reproduce it. 

However, looking into the code, I saw a potential problem and fixed it; 
[PR#877]([https://github.com/minio/minio-js/pull/877)

Please try to reproduce the issue and make sure it is still there. 
Then test the fix to verify the it addresses the problem.
As I don't know the details of your reproduction steps, I cannot verify the fix.
I appreciate your help.

Here is the script I used to repro the problem:
```
var Minio = require('minio')

var client = new Minio.Client({
  endPoint: '<host-name-or-ip>',
  port: <port#>,
  accessKey: '<access-key>',
  secretKey: '<secret-key>',
  useSSL: false
})
// List all object paths in bucket my-bucketname.
var objectsStream = client.listObjects('bucket1', 'child/', false)
objectsStream.on('data', function(obj) {
  console.log(obj)
})
objectsStream.on('error', function(e) {
  console.log(e)
})
```
I you'd like, please also send me the detailed repro steps, like what is your bucket/pre/fix/es/objects data is structured, what kind of minio server you were running, exactly what inputs or input produce(s) the issue, etc. Please try to be comprehensive.

**Comment by SamuelHassine** [comment]
Same bug here:

```
/var/data/app/opencti-platform/opencti-graphql/node_modules/minio/dist/main/xml-parsers.js:433
    xmlobj.CommonPrefixes.forEach(function (commonPrefix) {
                          ^

TypeError: xmlobj.CommonPrefixes.forEach is not a function
    at parseListObjectsV2 (/var/data/app/opencti-platform/opencti-graphql/node_modules/minio/dist/main/xml-parsers.js:433:27)
    at DestroyableTransform._flush (/var/data/app/opencti-platform/opencti-graphql/node_modules/minio/dist/main/transformers.js:88:19)
    at DestroyableTransform.prefinish (/var/data/app/opencti-platform/opencti-graphql/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:129:10)
    at DestroyableTransform.emit (events.js:315:20)
    at prefinish (/var/data/app/opencti-platform/opencti-graphql/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:611:14)
    at finishMaybe (/var/data/app/opencti-platform/opencti-graphql/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:620:5)
    at endWritable (/var/data/app/opencti-platform/opencti-graphql/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:643:3)
    at DestroyableTransform.Writable.end (/var/data/app/opencti-platform/opencti-graphql/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:571:22)
    at IncomingMessage.onend (_stream_readable.js:681:10)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by ebozduman** [comment]
@SamuelHassine ,

Since you can reproduce the problem in your setup, could you pick up PR#877 and test the fix?

If you cannot test and verify the fix/PR#877 for any reason, then please send us the details of your reproduction steps, like; how do you start MinIO, what is your configuration, what was running when the issue/error happened, what kind of hierarchical data structure you have in your bucket, especially the part of the data related to the command that reproduces the problem, etc.

**Comment by HeJueting** [comment]
@ebozduman ,

I tried to git clone https://github.com/minio/minio-js.git，and updated the code you modified in [#877](https://github.com/minio/minio-js/pull/877)，After recompiling the code, I found that the problem had been resolved.

Thank you for your reply and answer

**Comment by SamuelHassine** [comment]
Hello @ebozduman, I tested the PR#877. This PR actually fixed the bug. No crash since 12 hours.

**Comment by ebozduman** [comment]
@HeJueting , @SamuelHassine 

If you don't mind, can you test and verify the fix, #877, one more time for your scenario?
I refactored the code to address some other similar issues and I cannot reproduce your case to test in my environment. I appreciate your help.

**Comment by HeJueting** [comment]
@ebozduman 

I tried to compile your [latest code](https://github.com/minio/minio-js/blob/0d94636c2a9cc93906bdfc4e51810a1fd0dea673/src/main/xml-parsers.js). The [#876](https://github.com/minio/minio-js/issues/876) problem has been solved. In addition, I found that the [#879](https://github.com/minio/minio-js/issues/879) problem has been fixed .

**Comment by ebozduman** [comment]
Thank you @HeJueting

**Comment by mitni455** [comment]
This seems to occur if there is only one object in the bucket, then `xmlobj.Contents` returns the object (not an array of Objects). 

e.g. 
See `main/xml-parsers.js` 

```js
// this is an object, rather than an array
xmlobj.Contents = {
  Key: 'i-am-an-image.jpg',
  LastModified: '2021-06-09T02:53:16.760Z',
  ETag: '&#34;2d7feecd79365d213328b45b1cda0ca9&#34;',
  Size: 47572,
  Owner: {
    ID: '02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4',
    DisplayName: 'minio'
  },
  StorageClass: 'STANDARD'
}
```

#### Expected 
```js
// should be an array
xmlobj.Contents = [
  {
    Key: 'i-am-an-image.jpg',
    LastModified: '2021-06-09T02:53:16.760Z',
    ETag: '&#34;2d7feecd79365d213328b45b1cda0ca9&#34;',
    Size: 47572,
    Owner: {
      ID: '02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4',
      DisplayName: 'minio'
    },
    StorageClass: 'STANDARD'
  }
];
```

**Comment by prakashsvmx** [comment]
@mitni455 Yes. this is fixed in the master. it will be released as soon as we are done with few more APIs.

**Comment by ebozduman** [comment]
Thank you @mitni455 for the information.
Thank you @prakashsvmx for replying. 
This fix and quite some API support changes are on the way to release.
Please stay tuned.

**Comment by raynaldilalang** [comment]
i just had the same issue, and avoided the error using listObjectsV2
