### ISSUE TITLE
ListObjectV2WithMetadata return undefined metadata

### ISSUE THREAD

**Issue by Max9419** [minio/minio-js#880]
Hello!

I found out today that since v7.0.15(excluded), ListObjectV2WithMetadata return undefined metadata for me.

I digged a bit and found out that this bit of code 

```
      if (content.UserMetadata != null) {
        metadata = content.UserMetadata[0];
      } else {
        metadata = null;
      }
```

Need to be 

```
      if (content.UserMetadata != null) {
        metadata = content.UserMetadata;
      } else {
        metadata = null;
      }
```

For it to work for me. You can find this codein xml-parser.js L473.

Can you confirm that this should be the way?

Thank you!

**Comment by ebozduman** [comment]
@Max9419 ,

If you don't mind, can you test and verify the fix, #877, one more time for your scenario?
I refactored the code to address some other similar issues and I cannot reproduce your case to test in my environment. I appreciate your help.

**Comment by Max9419** [comment]
@ebozduman,

Hello, I can confirm that it did the trick for me!

Thank you very much!

**Comment by ebozduman** [comment]
@Max9419 
Thank you.
