### ISSUE TITLE
Minio @7.0.17 returns different result for listObjectsV2 from @7.0.16

### ISSUE THREAD

**Issue by gmacmaster** [minio/minio-js#881]
I have a folder within a bucket with ~1750 files in it. When I use:
    `const stream = minioClient.listObjectsV2('my-bucket', 'folder-name', true);`
In @7.0.16 it returns a list of the full ~1750 objects but in @7.0.17 it returns a list of only 289 objects. 

Steps to reproduce:

1. Install minio@7.0.16
2. use `minioClient.listObjectsV2('my-bucket', 'folder-name', true);`
3. Note number of returned files
4. Install minio@7.0.17
5. use `minioClient.listObjectsV2('my-bucket', 'folder-name', true);`
6. Note number of returned files, my result is different from step 3

**Comment by ebozduman** [comment]
@gmacmaster 
Is it possible to tell us what files are missing and/or what files are extra in what relese, and
how is your data structure, that is what is your folder ,'folder-name', content in terms of directories/prefixes and files/objects etc.

**Comment by arnediekmann** [comment]
While I can't provide details to reproduce the issue with a file structure etc. at this time, I just wanted to weigh in since we had a possibly related issue this morning: After upgrading from `7.0.16` to `7.0.17` last week `listObjectsV2` capped results to 1000 objects exact which is the page size used by minio-js I believe. A downgrade to `7.0.16` fixed the issue and returned all objects again.

**Comment by ebozduman** [comment]
@gmacmaster , @arnediekmann ,

If you don't mind, can you test and verify the fix, #877, for your scenario?
I refactored the code to address this issue with some other similar issues and I cannot reproduce your case to test in my environment. I appreciate your help.

**Comment by arnediekmann** [comment]
@ebozduman 

First of I can now reproduce the issue locally when using version `7.0.17` and a Minio server with the Docker image `minio/minio:RELEASE.2020-11-25T22-36-25Z`. I just create over 1000 objects in a bucket for example via the bash command:

```
for i in {1..1100}; do mkdir -p test_$i && touch test_$i/foo; done
```

When listing the objects via `listObjectsv2` the stream will consistently only yield 1000 objects.

I will now your pr #877 to see if it remedies the behaviour.

**Comment by arnediekmann** [comment]
@ebozduman I just tried pr #877 and this does not fix issue. The amount of objects returned is still stuck at 1000.

**Comment by arnediekmann** [comment]
Here is the code that we use to fetch objects in case this is related to how the library is used: https://github.com/neoskop/papergirl/blob/master/src/update/s3/s3.service.ts#L72

**Comment by ebozduman** [comment]
@arnediekmann 

Could you please give it another try?
I have a few more changes to address this issue. I tested and verified the fix, but I'd like to make sure your scenario is also covered.
Thanks for all your help.

**Comment by arnediekmann** [comment]
@ebozduman I have just re-tested and can confirm that your latest changes in pr #877 do fix the problem described here :partying_face:
