### ISSUE TITLE
Question: user tags support

### ISSUE THREAD

**Issue by onip** [minio/minio-js#884]
Hi all,

I've seen that other languages sdk ( golang, python ) support setting and getting user tags on objects. Is there any plan for it in the javascript library?

thanks

**Comment by kannappanr** [comment]
@onip We have plans of getting js SDK on par with other SDKs. Hopefully we will get started on that effort soon

**Comment by onip** [comment]
thank you.

**Comment by prakashsvmx** [comment]
@onip  Please have a look at the PR.

**Comment by onip** [comment]
@prakashsvmx I'm not a `minio-js` developer nor an S3 API expert, all I can do is sending a big thank you for your work.
