### ISSUE TITLE
Question or Feature Request: Is there a way to stat multiple files in one request?

### ISSUE THREAD

**Issue by abir-taheer** [minio/minio-js#889]
I know there's a way to stat a file using the [statObject](https://docs.minio.io/docs/javascript-client-api-reference.html#statObject) method but is there a way to stat multiple files from the same bucket?

Something like this following: 
```javascript
const objectNames = ['1.txt', '2.txt', '3.txt'];

minioClient.statObjects(bucketName, objectNames, (er, files) => {
    // files should be an array of metadata objects
});
```

This would be super useful when working with dataloaders in graphql or other environments that are prone to a N+1 issue otherwise.

**Comment by kannappanr** [comment]
@abir-taheer SDK will still have to make a call individually and return the values. There is no S3 API that corresponds to this feature request. I think the application itself can handle this instead of the SDK.Closing this issue, please feel free to reach out to us if you feel otherwsie
