### ISSUE TITLE
composeObject for JS SDK?

### ISSUE THREAD

**Issue by kwaithex** [minio/minio-js#895]
Hello everyone. 
I can see that minio python and java SDK has composeObject operation, but JS doesn't. 
I have a situation where I need to stream data directly to minio storage, without sacrificing storage on my backend. I went through the docs and couldn't find any way of appending data to an existing object so I thought i could compose multiple objects together. Turns out JS SDK can't do that either. Is there any way I could possibly combine multiple objects into one so I can stream back that object to my backend or my only option here is to prepare whole piece and deliver it to minio (thus using storage I was trying to avoid of using)

**Comment by prakashsvmx** [comment]
Please have a look at PR #940
