### ISSUE TITLE
Missing x-amz-security-token in presignedPostPolicy

### ISSUE THREAD

**Issue by joshuaavalon** [minio/minio-js#898]
Minio JS Version: 7.0.18

Even if you provide `sessionToken`, `presignedPostPolicy` response `formData` does not contains `x-amz-security-token`.

**Comment by prakashsvmx** [comment]
@joshuaavalon  Could you please verify the fix in the linked PR?

**Comment by ebozduman** [comment]
@joshuaavalon 

Could you please test the fix if you have your environment ready?

**Comment by joshuaavalon** [comment]
Yes, it works in my environment.

**Comment by ebozduman** [comment]
It also works in my environment.
I have tested the fix with Keycloak and web identity.
Please let me know if you need help testing the PR.
