### ISSUE TITLE
listObjects for bucket with "folders" results in TypeError: xmlobj.CommonPrefixes.forEach is not a function

### ISSUE THREAD

**Issue by starpit** [minio/minio-js#904]
When we call `client.listObjects("someBucketName")` for a bucket that contains a "folder" (i.e. an object with a trailing slash), the callback actually hangs! When we hack xml-parsers.parseListObjectsQuery to wrap the body with a try/catch, we see:

```
TypeError: xmlobj.CommonPrefixes.forEach is not a function
    at parseListObjects (xml-parsers.js:382)
```

further modifying that function to print out `xmlobj.CommonPrefixes` gives:

```javascript
{Prefix: "f1/"}
```

We see this in 7.0.17.

With 7.0.18, the client still hangs, but now the hanging exception is:

```
TypeError: xmlobj.Contents.forEach is not a function
    at parseListObjects (xml-parsers.js:388)
```

I suspect that 7.0.18 just has more bugs, because CommonPrefixes is still not forEach-able, in 7.0.18; it's still not an array:

```javascript
{Prefix: "f1/"}
```

Related? https://github.com/minio/minio-js/issues/886

**Comment by starpit** [comment]
This seems to be fixed on master. Can we expect a release on npm sometime soon? Thanks.

**Comment by standy** [comment]
Same issue here, fix https://github.com/minio/minio-js/pull/887 is merged already 
@prakashsvmx can you make a release please?

**Comment by ondra-m** [comment]
Can you please make next release?

**Comment by gitzjp** [comment]
> I just checked, and this seems to be fixed on master. Can we expect a release on npm sometime soon? Thanks.

I had the same problem and i solved it using listObjectsV2().

**Comment by prakashsvmx** [comment]
Please test with latest released version.
