### ISSUE TITLE
Minio server version is not in response headers anymore

### ISSUE THREAD

**Issue by SamuelHassine** [minio/minio-js#905]
Hello,

I would like to report an issue related to #810. Since the last versions of the MinIO server, the response header `Server:` just contains "Minio"  and not the version. Is there any reason to this change on the server side? Do you have a new method to get the remote Minio server version?

Kind regards,
Samuel

**Comment by harshavardhana** [comment]
It was for security reasons @SamuelHassine - it is the most common way production systems work https://www.acunetix.com/blog/articles/configure-web-server-disclose-identity/ 

Having this as public information is dangerous, if you are authenticated you can verify the server version with `mc admin info`.
