### ISSUE TITLE
Download folder as a ZIP

### ISSUE THREAD

**Issue by ToLToL** [minio/minio-js#906]
Hi,

I see that MinIO browser calls `POST {minio_server}:9000/minio/zip?token={token}` to download a folder as a ZIP.
Can we do the same with MinIO JS client SDK or S3 client?

Thanks for your reply.

**Comment by klauspost** [comment]
This library is for S3 compatible storage backends. This call is a minio specific extension and do not belong in this library.

**Comment by prakashsvmx** [comment]
@ToLToL  are you looking for something like https://github.com/orangewise/s3-zip ?

**Comment by klauspost** [comment]
@ToLToL This is the JS that handles it: https://github.com/minio/minio/blob/d12831eb0726c16383b8010e8a5d50473ad9a4a5/browser/app/js/objects/actions.js#L437

**Comment by ToLToL** [comment]
So it's the browser that creates the zip file not MinIO server ?
