### ISSUE TITLE
get-object.html 中 minio-browser.js 找不到的问题

### ISSUE THREAD

**Issue by zhangyalong123feiyu** [minio/minio-js#907]
在 html 使用   var Minio = require('minio') 的方式会报错，找不到。看example中的 get-object.html 中有引用minio-browser.js,但是也没有找到，minio-browser.js.

**Comment by zhangyalong123feiyu** [comment]
求教在html 中如何集成并使用minio-client.js。

**Comment by prakashsvmx** [comment]
Could you please add more details?
