### ISSUE TITLE
setBucketVersioning throwing NotImplemented error

### ISSUE THREAD

**Issue by LukeeeeBennett** [minio/minio-js#908]
Seems using `setBucketVersioning` is causing the following error. As far as I know, I have the latest release of minio, but I'm using helm charts so not 100% sure.

```
UnhandledPromiseRejectionWarning: S3Error: A header you provided implies functionality that is not implemented
```

**Comment by harshavardhana** [comment]
Because you are running in a single drive mode @LukeeeeBennett - run in erasure-coded or distributed erasure-coded mode for versioning.
