### ISSUE TITLE
presignedUrl doesn't give same results depending on file's upload

### ISSUE THREAD

**Issue by Eriion** [minio/minio-js#911]
Hi, i am currently facing an issue using javascript API for Minio.

I am getting HTML files from a minio server with "presignedUrl" and add this url to an iframe to display data (which has link to other files in minio folder). 

If I upload my html file from minio interface, everything work as expected, my iframe is loading, but if I upload from javascript API (putObject method), my html file is downloaded instead of used by my iframe. 

Already tested:
- Add bucket policy to "*" for Read and Write

Any clues ? 
Thank's

**Comment by Eriion** [comment]
There is some code used by our applications (NodeJS + Angular)  : 

### For uploading: 
`async putObject(minio: Minio.Client, bucket: string, path: string, buffer: string) {`
`await minio.putObject(bucket, path, buffer);`
` }`
Buffer came from 'UploadedFiles()' decorator (from NestJS) 

### For getting URL
Function returning url:
`const path = 'relativePathToMyFolder/index.html';`
`const url = await this.minioService.presignedUrl(req.minio, req.bucket, path, 24 * 60 * 60);`
`return url;`

presignedUrl from minioService is the classic presignedUrl function: 
`return await minio.presignedUrl('GET', bucket, path, expiration)`

### In Front-End
Url returned is simply used in an iframe block with [src]="url" in frontEnd

### Steps 
For all steps, same code as above is used, only changes is, if i uploading from minio interface (localhost:9000/minio), it works but if i'm using my upload function from my API, it download the files instead of adding it into iframe 

- Create folder on minio interface (Folder1)
- Add HTML file into it (File1)
- Create folder from Front-End app (Folder2)
- Add HTML file from Front-End app with code above (File2) 
- Getting File1 URL from API, adding in an iframe, works fine
- Getting File2 URL from API, it's downloading file instead of adding URL in iframe

I have seen that is not the Front-End the problem for getting URL since the URL generated for File1 in a chrome tab is loading html page but URL for File2 is downloading it. 

I have also tried to download File2 from Minio interface, rename it File3 and Import back from minio interface, it works

Maybe an issue with my putObject function ? 

I'm gonna try to send you a repo to test if i have time.

**Comment by Eriion** [comment]
There are repos to reproduce the issue: 
- App (https://github.com/Eriion/minioapp)
- API (https://github.com/Eriion/minioapi)
- Files are upload here: https://play.minio.io:9000/minio/eriion/ (If bucket deleted, feel free to create it 'eriion')

### Step to reproduce the bug
- Install depencies (npm i)
- Run APP and API (npm run start for APP and npm run start:dev for API)
- Upload File1.html (in app/src folder) in minio using minio website
- Open app (port 4200) 
- Click on 'Upload File'
- Choose File2.html (in app/src folder) and click on Send File2
- Click on Get File1 to console log presignedUrl in API Console
- Open that link, you have a page with FILE 1 Header
- Click on Get File2 to console log presignedUrl in API Console
- Open second link, File2.html file is downloaded

Files are already uploaded on eriion bucket following same steps. 

It's a basic repo, i can't send our real applications (confidentiality), i hope it helps.

**Comment by pedraldo** [comment]
Hi @Eriion,

I'm currently facing the exact same problem as yours.
So I wonder if you found a solution (please say yes 🙏 )

To upload a file, I send from my Front App a form-data (including the file) to my NestJS server, then, just like you, I use `putObject` function like this for example : 
```ts
  interface UploadFileOptions {
    bucketName: string;
    metaData?: { [key: string]: any };
  }
  
  public uploadFile(file: Express.Multer.File, options: UploadFileOptions): Promise<string> {
    const { bucketName, metaData } = options;
    return this.minioClient.putObject(bucketName, file.originalname, file.buffer, file.size, metaData);
  }
```

I also use MinIO `presignedGetObject` to download a file and to try to build a preview in an iframe with `[src]` (using Angular DomSanitizer to prevent 'unprotected( url issue).

I feel something strange that uploading in MinIO UI (localhost:9000) and with the JS Minio Client produce something a bit different so I think I will try to upload files in a different way, for example with `presignedPutObject` function.  
I really don't know if it's a good idea.
If it is I'll share it in a next comment 😉

**Comment by pedraldo** [comment]
An hour later, I can confirm that usage of `presignedPutObject` to upload file fix this issue.
I've the feeling with that method, file is uploaded with his mimeType correctly set. With the previous method (with `putObject`) when a file was uploaded, it appeared with a grey logo on its left (in MinIO UI files list).
Now for an image (for example) uploaded, logo is red (same color than an upload directly in MinIO UI).

Here are different parts of my code : 

**Front (Angular) :**
*Template HTML*
```html
<input type="file" class="file-input d-none"
       (change)="onFileSelected($event)" #fileUpload>

<div class="file-upload">

   {{fileName || "No file uploaded yet."}}

    <button mat-mini-fab color="primary" class="upload-btn"
      (click)="fileUpload.click()">
        <mat-icon>attach_file</mat-icon>
    </button>
</div>

<div class="mt-4">
  <mat-list>
    <mat-list-item *ngFor="let file of files">
      <button mat-icon-button (click)="getViewUrl(file.name)">
        <mat-icon>visibility</mat-icon>
      </button>
      <span>{{ file.name }}</span>
    </mat-list-item>
  </mat-list>
</div>

<div *ngIf="viewFileUrl" class="mt-4">
  <iframe style="width:100%;height:600px" [src]="viewFileUrl"> </iframe>
</div>
```
*Component TS*
```ts
  public onFileSelected(event): void {
    const file: File = event.target.files[0];

    // A proxy is configured on my project to redirect request /minio/* to localhost:9000 --> my local minio
    this.http.get<{ presignedUrl: string }>(`/minio/files/uploadUrl?objectName=${file.name}`).subscribe(urlObject => {
      const url = urlObject.presignedUrl;
      this.http.put(url, file).subscribe(() => {
        this.getFiles();
      });
    });
  }
  
  public getViewUrl(fileName: string): void {
    // A proxy is configured on my project to redirect request /minio/* to localhost:9000 --> my local minio
    this.http.get<{ presignedUrl: string }>(`/minio/files/viewUrl?objectName=${fileName}`).subscribe(urlObject => {
      this.viewFileUrl = this.sanitizer.bypassSecurityTrustResourceUrl(urlObject.presignedUrl);
    });
  }
```

**Server Node JS (NestJS) :**
*Controller (where routes are declared)*
```ts
  @Get('uploadUrl')
  async uploadFileUrl(
    @Query() query: PresignedUrlOptions,
  ): Promise<any> {
    const presignedUrl = await this.filesService.getPresignedUploadUrl(query);
    return { presignedUrl };
  }
  
  @Get('viewUrl')
  async viewFileUrl(
    @Query() query: PresignedUrlOptions
  ): Promise<any> {
    const presignedUrl = await this.filesService.getPresignedViewUrl(query);
    return { presignedUrl };
  }
```

*My file service*
```ts
  interface PresignedUrlOptions {
    bucketName: string;
    objectName: string;
  }

  public getPresignedViewUrl(options: PresignedUrlOptions): Promise<string> {
    const expiry = 24 * 60 * 60; // Expired in one day
    let { bucketName, objectName } = options;
    return this.minioClient.presignedGetObject(bucketName, objectName, expiry);
  }
  
  public getPresignedUploadUrl(options: PresignedUrlOptions): Promise<string> {
    const expiry = 24 * 60 * 60; // Expired in one day
    let { bucketName, objectName } = options;
    return this.minioClient.presignedPutObject(bucketName, objectName, expiry);
  }
```
I hope it will help at least one person 😉 
Cheers

**Comment by Eriion** [comment]
Hi @pedraldo 

Thank's for your code and answer ! It help me to find the solution about my issue. 

I've tried your solution but didn't work as expected, maybe i missed something or not exactly same used in our project. 

I've seen during testing with your solution that i only uploading the buffer of my file and missing some file information like size, mimetype and other... I've tried to add size and metaData as below and now it's working as expected for my use case.

```ts
async putObject(minio: Minio.Client, bucket: string, path: string, file: any) {
  await minio.putObject(bucket, path, file.buffer, file.size, {
    'Content-Type': file.mimetype,
  });
}
```

Thank's again for your help, we have now 2 kind of solutions, hope this will help 😉

**Comment by pedraldo** [comment]
Hey @Eriion 

Happy that my comments helped you 😊 .
Ok so what you introduced here confirmed that with our old common use of `putObject`, mime type wasn't correctly set and so not correctly recognized by MinIO once the file was uploaded.
Thank you for your additionnal solution, I wonder if I will not prefer yours 😉
