### ISSUE TITLE
InvalidArgumentError: Invalid port : 9000

### ISSUE THREAD

**Issue by ashishdocforce** [minio/minio-js#914]
I am bit confused about minio s3 gateway. Do we required aws sdk when we are running the minio server with s3 gateway? My server started running and browsers is showing me the s3 buckets but I can't connect to the server through my node app. It is stating that port 9000 is invalid. Is that anything relevent to aws sdk or something else needs to be done here?

I have gone through the document of minio but didn't find anything for this.

The error is as as below:

```
InvalidArgumentError: Invalid port : 9000,
    at new Client (/var/www/html/learn-otter-api/node_modules/minio/dist/main/minio.js:97:13)
```

**Comment by prakashsvmx** [comment]
How are you starting the server (command line arguments)?

**Comment by ashishdocforce** [comment]
> How are you starting the server (command line arguments)?
> 

Yes

**Comment by harshavardhana** [comment]
> Yes. Minio server is working properly. I can access minio browser as well and everything seems fine until I call the instance from my node server.

The issue here is your endpoint configuration @ashishdocforce - please share your sample code .

**Comment by prakashsvmx** [comment]
@ashishdocforce  is it resolved?

**Comment by ashishdocforce** [comment]
>  @ashishdocforce  is it resolved?

Don't know much. Just commented port part and it worked. Now juggling with another error. The error message shows `S3Error` that's it. I don't understand what's wrong with s3. As it is already working properly on minio browser.

**Comment by prakashsvmx** [comment]
Please feel free to re-open with replication steps and possibly  code example with configuration settings.
