### ISSUE TITLE
fGetObject returns undefined but downloads file

### ISSUE THREAD

**Issue by marnec** [minio/minio-js#915]
I'm writing an API that should let users download files. I'm using the `fGetObject()` functions. its return value is `undefined` but the file is downloaded
## Expected Behavior
`fGetObject()` should return a promise of file

## Current Behavior
`fGetObject()` returns undefined but downloads file

## Context
NestJS backend with MinIO for file managing

## Your Environment

* minio version 7.0.18
* NestJS 
* Ubuntu20@WSL2.0

**Comment by prakashsvmx** [comment]
@marnec 
to get a promise, the last argument has to be a callback. as in the below example

```
s3Client.fGetObject('my-bucketname', 'my-objectname', '/tmp/objfile', function(e) {
  if (e) {
    return console.log(e)
  }
  console.log('done')
})
```

Please share the snippet used.

**Comment by marnec** [comment]
thanks for the answer, however unfortunately it is not helpful in my case.

This is the function call
```
let fileInserted;
    if (!fileFounded) {
      fileInserted = await this.minioClient.fGetObject(
        this.bucketName,
        attachToDownload.path,
        `${this.cachePath}${attachToDownload.originalName}`
      );
    }
```

I tried both with the callback and without the callback. 

Furthermore, [the documentation](https://docs.min.io/docs/javascript-client-api-reference.html#fGetObject) states the contrary:

> Callback is called with err in case of error. **If no callback is passed, a Promise is returned.**

**Comment by prakashsvmx** [comment]
Yes. @marnec  You are correct as per doc
.

**Comment by prakashsvmx** [comment]
Since it is an `async` action with streaming file write operation and it does not have a return value.
but you could still try if any post processing is required also can found in functional tests:
```
function fGet(bucketName, objName){

  const fGetPromise = minioClient.fGetObject(bucketName, objName, `./download/${objName}`, {})

  fGetPromise.then(() => {
    console.log("fGetObject Written file to the specified location...")
  })
    .catch(()=>{
      console.log("fGetObject Error")
    })

}
```
