### ISSUE TITLE
listenBucketNotification responds with 'AccessDenied' in JS client although permitted

### ISSUE THREAD

**Issue by made-by-traxam** [minio/minio-js#918]
Hey, I'm trying to listen to bucket notifications using the minio-js client but I'm getting an `Access Denied` error when running `listenBucketNotification`. I am running the poller on a user with the `s3:ListenBucketNotification` permission allowed for the bucket (the setup script is attached below).

I have already tried the following:
* receive notifications from the minio JS client **with the new user** - this doesn't work, throwing an `AccessDenied` error (JS code and error messages are attached below)
* receive notifications from the minio JS client **with the default admin user** - this does work, surprisingly
* receive notifications using the `mc` CLI client (`mc watch`) - this works with both the new user and the default admin
* receive notifications using the minio GO client - this works with both users too
* receive notifications using the minio Java client - this does not work with the new user but does with the admin user

I'm not sure if I've made a mistake with the permissions configuration or in using the JS client.

Thanks,
traxam

# JS code
The following code is mostly copied from the examples section in this repository: [`examples/minio/listen-bucket-notification.js`](https://github.com/minio/minio-js/blob/master/examples/minio/listen-bucket-notification.js)
```js
const Minio = require('minio')

var s3Client = new Minio.Client({
  endPoint: 'localhost',
  port: 9000,
  accessKey: 'newuser', // alternative: minioadmin
  secretKey: 'newpassword', // alternative: minioadmin
  useSSL: false
})

let poller = s3Client.listenBucketNotification('newbucket', '', '',
  ['s3:ObjectCreated:*', 's3:ObjectAccessed:*', 's3:ObjectRemoved:*'])

poller.on('notification', record => {
    console.log('New object: %s/%s (size: %d)', record.s3.bucket.name,
                record.s3.object.key, record.s3.object.size)
    poller.stop()
})
poller.on('error', err => {
    console.log('error in poller')
    console.error(err)
})
```
The following error is thrown when connecting with the new user:
```
error in poller
S3Error: Access Denied.
    at Object.parseError (/home/traxam/listen-notifications/node_modules/minio/dist/main/xml-parsers.js:79:11)
    at /home/traxam/listen-notifications/node_modules/minio/dist/main/transformers.js:156:22
    at DestroyableTransform._flush (/home/traxam/listen-notifications/node_modules/minio/dist/main/transformers.js:80:10)
    at DestroyableTransform.prefinish (/home/traxam/listen-notifications/node_modules/readable-stream/lib/_stream_transform.js:129:10)
    at DestroyableTransform.emit (node:events:327:20)
    at prefinish (/home/traxam/listen-notifications/node_modules/readable-stream/lib/_stream_writable.js:611:14)
    at finishMaybe (/home/traxam/listen-notifications/node_modules/readable-stream/lib/_stream_writable.js:620:5)
    at endWritable (/home/traxam/listen-notifications/node_modules/readable-stream/lib/_stream_writable.js:643:3)
    at DestroyableTransform.Writable.end (/home/traxam/listen-notifications/node_modules/readable-stream/lib/_stream_writable.js:571:22)
    at IncomingMessage.onend (node:internal/streams/readable:680:10) {
  code: 'AccessDenied',
  bucketname: 'newbucket',
  resource: '/newbucket',
  requestid: '167225529A613AEC',
  hostid: 'ba4ca585-0686-4b3f-8765-814fad7ae3d9',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}
```

# Setup script for the minio server
The following things are set up:
* create a new user `newuser`
* create a new bucket `newbucket`
* grant `s3:ListenBucketNotification` and `s3:CreateBucket` permissions to the new user on the new bucket
```bash
docker run -d -p 9000:9000 minio/minio server /data > minio_id
sleep 1
~/mc alias set docker-minio/ http://localhost:9000 minioadmin minioadmin
~/mc mb docker-minio/newbucket
~/mc admin user add docker-minio newuser newpassword
~/mc alias set docker-newuser/ http://localhost:9000 newuser newpassword
echo "this will fail (as expected):"
~/mc watch docker-newuser/newbucket
~/mc ls docker-newuser/newbucket
cat > newpolicy.json << EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:ListenBucketNotification",
        "s3:CreateBucket"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::newbucket/*"
      ],
      "Sid": ""
    }
  ]
}
EOF
~/mc admin policy add docker-minio/ newpolicy newpolicy.json
~/mc admin policy set docker-minio/ newpolicy user=newuser
sleep 1
~/mc watch docker-newuser/newbucket
read -p "Press enter"
docker stop "$(< ./minio_id)"
docker rm "$(< ./minio_id)"
```

# Alternative code using the go client
The following code (using the go minio client) will receive and print notifications without any access errors:
```go
package main

import (
        "context"
        "log"

        "github.com/minio/minio-go/v7"
        "github.com/minio/minio-go/v7/pkg/credentials"
)
// from the minio-go examples
func main() {
        minioClient, err := minio.New("localhost:9000", &minio.Options{
                Creds:  credentials.NewStaticV4("newuser", "newpassword", ""),
                Secure: false,
        })
        if err != nil {
                log.Fatalln(err)
        }
        for notificationInfo := range minioClient.ListenBucketNotification(context.Background(), "newbucket", "", "", []string{
                "s3:ObjectCreated:*",
                "s3:ObjectAccessed:*",
                "s3:ObjectRemoved:*",
        }) {
                if notificationInfo.Err != nil {
                        log.Fatalln(notificationInfo.Err)
                }
                log.Println(notificationInfo)
        }
}
```

**Comment by made-by-traxam** [comment]
Hi again,

while looking for the difference between the clients, I ran `mc watch` with the `--debug` flag and found out that the `mc` CLI sends a location-request before starting to listen for events (log attached below). This request fails because I have not added the `s3:GetBucketLocation` permission to the user policy for the bucket. Adding this permission also makes the node client work.

I think this has solved my problem but I'm curious:

Is this intended behaviour? (is the listenBucketNotifications request supposed to fail if only the location request fails? the go client for example ignores this error silently and starts listening for events anyways)

```
mc: <DEBUG> GET /newbucket/?location= HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-03-23T05-46-11Z
Authorization: AWS4-HMAC-SHA256 Credential=newuser/20210403/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210403T211502Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 270
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Sat, 03 Apr 2021 21:15:02 GMT
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 16727595CAAA77D4
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><BucketName>newbucket</BucketName><Resource>/newbucket/</Resource><RequestId>16727595CAAA77D4</RequestId><HostId>34777070-b715-4cb6-9cc7-1275df283ee2</HostId></Error>mc: <DEBUG> Response Time:  3.2481ms
```

**Comment by prakashsvmx** [comment]
@made-by-traxam i request you to kindly verify the behavior with AWS s3 /sdk and compare the same .

**Comment by made-by-traxam** [comment]
> @made-by-traxam i request you to kindly verify the behavior with AWS s3 /sdk and compare the same .

I'm not sure how to do this with the s3 SDK. Isn't `listenBucketNotification` an extension that only works on minio servers (and thus isn't supported by the aws SDK)? At least the [`s3:ListenBucketNotification` permission](https://docs.min.io/minio/baremetal/security/IAM/iam-policies.html#policy-action.s3-ListenBucketNotification) is supposed to be MinIO-exclusive, according to the docs.

**Comment by prakashsvmx** [comment]
@made-by-traxam i will investigate this further.

**Comment by prakashsvmx** [comment]
@made-by-traxam Thank you for the detailed replication steps. 

The new user needs explicit permission or the default region 'us-eat-1' set in the client initialization.

```
 new Minio.Client({
  endPoint: 'localhost',
  port: 9000,
  useSSL: false,
  region:"us-east-1", 
  accessKey: 'newuser', // alternative: minioadmin
  secretKey: 'newpassword', // alternative: minioadmin
})
```
I will send a fix  to send the (optional)  region. with default value.
