### ISSUE TITLE
xmlobj.Contents.forEach is not a function

### ISSUE THREAD

**Issue by Hazeman28** [minio/minio-js#921]
For some reason distribution version of the package does not wrap all `xmlobj.Contents` accesses with `toArray`. I checked source code, and it seems everything is fine there, but for some reason in the `node_modules/minio/dist/main/xml-parsers.js` first access of the `xmlobj.Contents` (line 387) is not wrapped with `toArray`.

I might be missing something obvious here.

## How to reproduce

I'm using [`express-middleware-minio` package](https://github.com/yucigou/express-middleware-minio/blob/master/src/utils.js), and when I try listing all files in the bucket, I get that error. I'm pretty sure, it's not related to that package.

I've tried to create an empty project, install minio with:
```
$ yarn add minio
```
and check `dist` directory of the package:
```
$ cat -n node_modules/minio/dist/main/xml-parsers.js | grep xmlobj.Contents
```
Output was:
```
386	  if (xmlobj.Contents) {
387	    xmlobj.Contents.forEach(function (content) {
436	  if (xmlobj.Contents) {
437	    toArray(xmlobj.Contents).forEach(function (content) {
481	  if (xmlobj.Contents) {
482	    toArray(xmlobj.Contents).forEach(function (content) {
```
As you can see, first access of the `xmlobj.Contents` is not wrapped with `toArray`.

**Comment by prakashsvmx** [comment]
Is it with latest mater or could you specify the exact version used ? Possibly with code example to replicate it. ?

**Comment by Hazeman28** [comment]
> Is it with latest master or could you specify the exact version used ? Possibly with code example to replicate it. ?

I'm using version 7.0.18. Since I'm using the mentioned `express-middleware-minio` package, the only code example I can provide is my usage of that package:
```
const expressMinio = require('express-middleware-minio');
const minioMiddleware = expressMinio.middleware();

const fileRouter = Router();

fileRouter.get("/", minioMiddleware({ op: expressMinio.Ops.list }), (req, res) => {
  if (req.minio.error) {
    console.error(req.minio.error);
    res.status(400).json({ error: req.minio.error });
  } else {
    res.send(req.minio.list);
  }
});
```
Internally that package calls `listObjects` method of the minio client. Here is [a link](https://github.com/yucigou/express-middleware-minio/blob/c373af31621f0cf294881fb38f1fadd836745527/src/minio-client.js#L99) for that file if it helps.

**Comment by prakashsvmx** [comment]
@Hazeman28  i think the latest version is `7.0.19` could you try to upgrade and  check ?

**Comment by Hazeman28** [comment]
> @Hazeman28 i think the latest version is `7.0.19` could you try to upgrade and check ?

When I install `minio` on a new project with `yarn add minio`, it installs version `7.0.18`. If I try to manually change its version to `7.0.19` in `package.json` and run `yarn install` I get this message:
```bash
$ yarn install
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "minio" that matches "^7.0.19"
? Please choose a version of "minio" from this list: (Use arrow keys)
❯ 7.0.18 
  7.0.17 
  7.0.16 
  7.0.15 
  7.0.14 
  7.0.13 
  7.0.12 
  7.0.11 
  7.0.10 
  7.0.9 
  7.0.8 
  7.0.7 
  7.0.6 
  7.0.5 
  7.0.4 
  7.0.3 
  7.0.2 
  7.0.1 
  7.0.0 
  6.0.0 
  5.0.2 
(Move up and down to reveal more choices)
```
Do I need to specify something like `yarn add minio@latest`?

**Comment by Hazeman28** [comment]
@prakashsvmx for now I resolved problem by installing minio directly from the GitHub. But updated npm package would be preferred.

**Comment by zoltan-mihalyi** [comment]
I think issues should not be closed before the release.
The same bug was reported multiple times, because we can't find the original issue. When I find the original issue, which is closed, I assume my bug report is different, because it still exists in the latest version.

**Comment by Hazeman28** [comment]
@zoltan-mihalyi you are right. Reopening this.

**Comment by narrowizard** [comment]
Any updates?

**Comment by prakashsvmx** [comment]
@narrowizard @Hazeman28  Please test with the latest version.7.0.20.

**Comment by narrowizard** [comment]
it works, thank you very much @prakashsvmx , you saved my day.  

> Seems the latest version is 7.0.19, but it doesn't matter. 7.0.19 works very well.
