### ISSUE TITLE
how to use minio in vite2.x?

### ISSUE THREAD

**Issue by NoManPlay** [minio/minio-js#922]
when I use minio in vite2.x,have wrong as
`sax.js:222 Uncaught TypeError: Cannot read property 'prototype' of undefined`
found in [https://github.com/vitejs/vite/issues/1770](url)
but when i `yarn add stream` have wrong as
`Uncaught TypeError: Super expression must either be null or a function`

**Comment by prakashsvmx** [comment]
could you link a sample code? like code sandbox etc ?

**Comment by kannappanr** [comment]
@NoManPlay Closing this issue. Please feel free to reach out to us when you have the requested information
