### ISSUE TITLE
xmlobj.Contents.forEach is not a function

### ISSUE THREAD

**Issue by Ailsa0823** [minio/minio-js#924]
In version 7.0.18, when there is only one piece of data in the bucket, call javascript api listObjects, parseListObjects function of xml-parsers.js file 387 line xmlobj.Contents.forEach error report

**Comment by prakashsvmx** [comment]
@Ailsa0823 

https://github.com/minio/minio-js/issues/921

Please have a look for a solution. Once there is a newer release , it would work fine.

**Comment by prakashsvmx** [comment]
Closing this as a duplicate.

**Comment by Ailsa0823** [comment]
When will the new npm version be released

**Comment by Ailsa0823** [comment]
@prakashsvmx When will the new npm version be released

**Comment by gogogo1024** [comment]
在线等～ waiting online

**Comment by prakashsvmx** [comment]
We are adding more APIs and they are in review before we could plan a release.

@gogogo1024 Priority fixes/releases require [SUBNET Subscription](https://min.io/pricing)

**Comment by gogogo1024** [comment]
> We are adding more APIs and they are in review before we could plan a release
thanks  , I fix it in local ~
![Uploading 截屏2021-05-12 下午5.50.43.png…]()
