### ISSUE TITLE
TypeError: xmlobj.Contents.forEach is not a function

### ISSUE THREAD

**Issue by zoltan-mihalyi** [minio/minio-js#926]
When the bucket contains a single file, this throws an error:

```javascript
const listObjects = client.listObjects('test');
listObjects.on('data', (item)=>{
    console.log(item);
})
```
`xml-parsers.js:387:21`

Probably, there is a missing toArray() call.

The toArray call was added then removed in this PR: in https://github.com/minio/minio-js/pull/877

added in https://github.com/minio/minio-js/pull/877/commits/0d94636c2a9cc93906bdfc4e51810a1fd0dea673
removed in https://github.com/minio/minio-js/pull/877/commits/fe16d07ef0724d577b676cc57aa609aaba44fee9

**Comment by prakashsvmx** [comment]
Please refer to 
#924
 https://github.com/minio/minio-js/issues/921#issuecomment-824749668

After a new release, it would be solved 

Marking this as a duplicate.
