### ISSUE TITLE
support to assume role with webIdentity

### ISSUE THREAD

**Issue by hauck-jvsh** [minio/minio-js#928]
MinIO supports  webIdentity, so the minio-js sdk should also support this. I made a small static function that get Temporally Credentials From a JWT Token using the assume role with webIdentity action.

**Comment by colorzzr** [comment]
Hi I am also wondering if we can support the webIdentity in SDK. Thanks!

**Comment by prakashsvmx** [comment]
@hauck-jvsh  Could you try this PR #960
