### ISSUE TITLE
Access an object by its URL in MinIO

### ISSUE THREAD

**Issue by MichaelGrigoryan25** [minio/minio-js#932]
Hello, I am trying to access a file at my local MinIO server at let's say `localhost:9000/foo/bar`, but I am getting redirected to the login page of MinIO, instead I want to get the object itself (image/video/etc.). 

How can I accomplish this and is there a way to do this without S3 policies?

So far, I have tried creating an Object URL, but it worked for a limited amount of time and I need a permanent access to my object without any limits.

**Comment by kannappanr** [comment]
@MichaelGrigoryan25 It is not possible to do this without setting bucket policies. If there is bucket policy set, this will not direct to the login page. This question itself doesn't have anything to do with minio-js SDK. Closing this as answered. Please feel free to reach out to us at https://slack.min.io for further clarifications
