### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by pyalpha** [minio/minio-js#933]
I am trying to connect a Vue.js( with Vite ) app to my Minio server, but I always get an error with "global is not defined".
My Code looks like this:
![grafik](https://user-images.githubusercontent.com/40123243/119360813-4d76e880-bcab-11eb-8025-f223c5024812.png)

This is the errror
![grafik](https://user-images.githubusercontent.com/40123243/119360860-59fb4100-bcab-11eb-9850-36e97d182300.png)

**Comment by prakashsvmx** [comment]
@pyalpha Please add or link a sample repo or codesandbox with replication steps.

**Comment by prakashsvmx** [comment]
Few node native packages might have to be installed.. like stream, fs etc..

**Comment by pyalpha** [comment]
Here, this should fit
https://codesandbox.io/s/brave-thunder-7eo1n?file=/src/App.vue

**Comment by prakashsvmx** [comment]
Could you follow this (since the link looks like browser lib instead of nodejs .)

https://github.com/minio/minio-js/issues/594#issuecomment-307268782

**Comment by pyalpha** [comment]
I will try it and then let you know

**Comment by pyalpha** [comment]
I've given up on it, it's a shame it's so incompatible. I will now write a small Python script so that I can use it at all.
