### ISSUE TITLE
respHeaders in Params, Why not in headers

### ISSUE THREAD

**Issue by rupamking1** [minio/minio-js#937]
presignedGetObject respHeaders in Params, Why not in headers,
because Params is not encrypted in https but headers is encrypted  in https.

how to pass respHeaders Object via headers? Please answer me...

**Comment by prakashsvmx** [comment]
Could you please add more details on what exactly is the problem may be with some examples or code snippets ?

**Comment by rupamking1** [comment]
var presignedUrl = s3Client.presignedGetObject('hkhk', 'b.svg', 10000, {'aaaaa': "bbbbb"} ,function(e, presignedUrl) {
  if (e) return console.log(e)
  console.log(presignedUrl)
})

{'aaaaa': "bbbbb"} it passed on param. 
https://play.min.io:9000/hkrish7/b.svg?aaaaa=bbbbb&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20210607%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210607T103438Z&X-Amz-Expires=10000&X-Amz-SignedHeaders=host&X-Amz-Signature=42eae85c77707ec2e9109a1f8bb3fc511525176b6b64c870ac381327107370f8

but i want to send it via API Header because API header is encrypted but param is not encrypted( https://play.min.io:9000/hkrish7/b.svg?aaaaa=bbbbb )

**Comment by prakashsvmx** [comment]
Since the request is signed, i think you do not have to be concerned. Else you could explore AssumeRole API  i guess.

**Comment by rupamking1** [comment]
> https://docs.min.io/docs/javascript-client-api-reference.html
> (presignedGetObject)
> 
> var presignedUrl = s3Client.presignedGetObject('hkhk', 'b.svg', 10000, {'aaaaa': "bbbbb"} ,function(e, presignedUrl) {
> if (e) return console.log(e)
> console.log(presignedUrl)
> })
> 
> {'aaaaa': "bbbbb"} it passed on param.
> https://play.min.io:9000/hkrish7/b.svg?aaaaa=bbbbb&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20210607%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210607T103438Z&X-Amz-Expires=10000&X-Amz-SignedHeaders=host&X-Amz-Signature=42eae85c77707ec2e9109a1f8bb3fc511525176b6b64c870ac381327107370f8
> 
> but i want to send it via API Header because API header is encrypted but param is not encrypted( https://play.min.io:9000/hkrish7/b.svg?aaaaa=bbbbb )

can you please answer this question, What is AssumeRole API.

**Comment by prakashsvmx** [comment]
https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html

**Comment by prakashsvmx** [comment]
Closing this as it is not related to any bug/issue.
