### ISSUE TITLE
Next Release Roadmap

### ISSUE THREAD

**Issue by oasisvali** [minio/minio-js#939]
Thanks for the great work on the minio ecosystem folks!

Just wondering if Is there a roadmap/plan for when the next version of minio-js will be released? It has been ~6 months since the last release and there are several new features added since then that we would like to leverage. Thanks once again!

**Comment by prakashsvmx** [comment]
Priority fixes and roadmap influence are available aa part of subscriptions (https://min.io/pricing). We are planning a release soon though. Please stay tuned. 
Closing this as it does not require any technical investigation.
