### ISSUE TITLE
Upload multiple file or folder

### ISSUE THREAD

**Issue by rupamking1** [minio/minio-js#941]
how to Upload multiple file or folder

**Comment by prakashsvmx** [comment]
you could try [mc client](https://docs.min.io/docs/minio-client-complete-guide.html)  
The following commands might be helpful based on your use case.

[mc cp](https://docs.min.io/docs/minio-client-complete-guide.html#cp)
[mc mv](https://docs.min.io/docs/minio-client-complete-guide.html#mv)
[mc mirror ](https://docs.min.io/docs/minio-client-complete-guide.html#mirror)

**Comment by rupamking1** [comment]
I want to upload without using Shell or cmd

**Comment by prakashsvmx** [comment]
> I want to upload without using Shell or cmd

```
const uploadMultipleFiles = (fileStreams) =>{

  const filesUploaded = fileStreams.map( (srcItem) =>  s3Client.putObject('<BucketName>','<ObjectName>',<fileStream>, {metaData:'any options'})  )

  Promise.all(filesUploaded).then(uploadResult =>{
    console.log("All files uploaded")
  }).catch((err)=>{
    console.log("Upload failed for one or more files")
  })
}
```
