### ISSUE TITLE
Is it planned to build a new release soon ? 

### ISSUE THREAD

**Issue by lerminou** [minio/minio-js#942]
the latest tag was on december 2020, is it planned to build a new release ? 

i'm very interested about tagging feature: https://github.com/minio/minio-js/pull/916

the minio official page links directly to master I think ? because the doc has already these methods
https://docs.min.io/docs/javascript-client-api-reference.html#getObjectTagging

**Comment by prakashsvmx** [comment]
Yes. We are planning a release soon. Stay tuned. 

We do not have versioned docs release. Please feel free to contribute.

Please note:
Priority releases/fixes require [subscription](https://min.io/pricing). 

Closing this since it not related to a bug or feature request.
