### ISSUE TITLE
listObjectsV2 when there is & in object name

### ISSUE THREAD

**Issue by aloupis** [minio/minio-js#943]
Version: **7.0.18**
Operation: **listObjectsV2**

When calling putObject operation for a file that contains the char & (example&.pdf), the file is correctly uploaded on minio. The created object has the name example&.pdf. If this object 's key is test/example&.pdf , when we call listObjectsV2 with prefix 'test/' the object that is returned, has the name example`&amp;`.pdf instead of the correct example&.pdf

**It is working correctly for version 7.0.16**

**Comment by klauspost** [comment]
> example&.pdf instead of the correct example&.pdf

Looks the same to me. Copy+Paste error?

**Comment by aloupis** [comment]
@klauspost sorry the editor has transformed `&amp;` to &  😅  .

**Comment by prakashsvmx** [comment]
I see that between the releases  `xml2js` has been replaced with `fast-xml-parser` .
So it might require  special handling as per S3 Guide :
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html

**Comment by OxCom** [comment]
Temp solution to decode file names:
```javascript
export default function decodeFileName(str) {
    // @see https://github.com/minio/minio-js/pull/959/files
    // the objects name from MinIO came as XML encoded lines
    return str
        .replace(/&#(\d+);/g, (match, dec) => String.fromCharCode(dec))
        .replace(/&apos;/g, '\'')
        .replace(/&quot;/g, '"')
        .replace(/&gt;/g, '>')
        .replace(/&lt;/g, '<')
        .replace(/&amp;/g, '&');
}


// ...

const list = [];

s3client
    .listObjectsV2(bucket., prefix, true)
    .on('data', object => {
        list.push(decodeFileName(object.name));
    })

// ...
```
