### ISSUE TITLE
Documentation does not correspond with the latest version

### ISSUE THREAD

**Issue by kazeens** [minio/minio-js#953]
JS  client documentation is misleading and is not corresponding with the latest release!

A lot of methods mentioned in the doc are absent.

When they are going to appear?

**Comment by prakashsvmx** [comment]
We have few PRs in Review/Test for the release. Please stay tuned.

@kazeens

**Comment by alinjie** [comment]
Any updates on this?

**Comment by prakashsvmx** [comment]
@alinjie the release is still in Work in progress.

**Comment by prakashsvmx** [comment]
@alinjie @kazeens Please test with the latest version.7.0.20.
