### ISSUE TITLE
removeObjects: "undefined is not a constructor (evaluating 'new _util.default.TextEncoder()')"

### ISSUE THREAD

**Issue by bhallstein** [minio/minio-js#954]
Hi there, really liking the minio library, thanks! Have come across an apparent issue with `removeObjects` that's blocking us from going live with it right now, as we want to.

A TypeError is being thrown inside `removeObjects()`. Here is a screenshot of the web inspector showing the location of the error within the method call. I've expanded the _utils variable in the right hand panel to illustrate how TextEncoder is not defined on the _utils object.

![Screenshot 2021-08-04 at 16 52 48](https://user-images.githubusercontent.com/3428028/128213336-a0fb4aea-5a80-4a65-ae94-1aa65d364491.png)

We're using parcel as our bundler and the ES module import/export syntax. However the same error occurs whether importing in either style:

```js
import * as Minio from 'minio'
const S3 = new Minio.Client(...)
// or
const Minio = require('minio')
const S3 = new Minio.Client(...)
```

Very happy to be educated if I'm doing something wrong. Thanks for your time!

Installed Minio JS version (from npm): 7.0.18

**Comment by prakashsvmx** [comment]
Please help us with a minimal steps /setup to replicate.

**Comment by bhallstein** [comment]
Hi @prakashsvmx, thanks for your reply! I've done a little more digging and I've found the cause of the problem.

Minio is relying on the 'util' package: https://www.npmjs.com/package/util As described in https://github.com/browserify/node-util/issues/46, `util` does not include node's utils.TextEncoder/Decoder. However Minio is expecting it to be there, as per the screenshot above.

For browser environments, Minio needs to fall back to the browser's global TextEncoder variable instead.

Re: replicate — any call to `removeObjects` made in a browser environment will throw the TypeError.

**Comment by prakashsvmx** [comment]
We will investigate this. We really have  not performed aggressive testing on the browser environment.

**Comment by bhallstein** [comment]
No worries, many thanks for your reply @prakashsvmx ! Really appreciated.

I got a forked copy of minio working for us with pretty minimal changes, you can see there here in case this is useful: https://github.com/bhallstein/minio-js/commit/685d47e7c99fa98c1fc43cfdfa10ee091ef8ee3f After substituting in the global browser copy of TextEncoder, I had just one further error that md5 was being run on a UInt8Array rather than a string, this apparently doesn't work in the browser.

**Comment by prakashsvmx** [comment]
@bhallstein  You could send across a PR if viable .

**Comment by prakashsvmx** [comment]
@bhallstein  The fixes are ready for review. Please have a look and possibly test and confirm the fixes.
Thank you again for reporting the issue.

A sample app for testing is available at https://github.com/prakashsvmx/minio-js-web-browser-example
