### ISSUE TITLE
metadata: null

### ISSUE THREAD

**Issue by hanumanjiblog** [minio/minio-js#967]
Please fix this error "metadata: null"

await s3.fPutObject('buckethk', `a0.hk`, './a0.hk', { example: '5379' })

var array = []
var stream = s3.extensions.listObjectsV2WithMetadata('buckethk', '', true, '')
stream.on('data', function (obj) { array.push(obj) })
stream.on('error', function (err) { console.log(err) })
setTimeout(async () => {
  console.log(array)
}, 3000);

output-
{
    name: 'a0.hk',
    lastModified: 2021-09-27T15:08:09.000Z,
    etag: '3214ffe77a6a804f2a7e7bdae4b52625',
    size: 118,
    metadata: null
  },

**Comment by prakashsvmx** [comment]
@hanumanjiblog  will check this and investigate. 
Thank you for reporting

**Comment by prakashsvmx** [comment]
`s3.extensions.listObjectsV2WithMetadata` is a minio only api (extension api ) . It works as expected as i tested with play.min.io and locally running minio instances. 

 And it is not expected to work with s3.
