### ISSUE TITLE
fPutObject: The specified multipart upload does not exist.

### ISSUE THREAD

**Issue by krainboltgreene** [minio/minio-js#969]
Hello! I am having issues and I think I've nailed it down to either network issues on my side or the client itself.

Here's the setup:

  1. I have a cluster of 3 minio instances
  	1. Each is on a vsphere virtual machine with 2gb of ram
  	2. Each is running inside the official docker instance
  	3. Each has 4 disks mounted to 4 docker mounts
  2. I have a cluster of 3 nginx instances in front
  3. I have a [github action](https://github.com/whalemare/minio-cache) that compresses a `node_modules/` directory and uploads it to the minio server
  4. I have two branches:
    1. One with the node_modules compressing to 170mb
    2. One with the node_modules compressing to 220mb

When the github action mentioned attempts to upload the compressed 220mb I get this error message:

```
The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.
```

The 170mb file cleanly uploads.

Here are things I have tried:

  1. I have manually uploaded a 220mb file via `mc` on my local machine *and it worked just fine* multiple times.
  2. I have tried configuring the nginx cluster in front of minio based on minio's guides and reading nginx documentation, only to get the same error message.
  3. I have tried having the github action talk directly to minio, bypassing the nginx cluster, instead talking to our consul DNS round-robin-ing between the minio cluster, only to get the same error message.
  4. I have tried having the github action talk directly to a singular minio instance, again via consul, only to get the same error message.
  5. I have tried having the github action talk directly via IP address, only to get the same error message.

Again, the 170mb github action payload successfully works and the local 220mb file successfully uploads.

So given all of the above details I hope it's my setup that's causing the issue and not minio, but I'm willing to give pretty much everything needed to debug this.

**Comment by kannappanr** [comment]
@krainboltgreene when you are executing this command, can you also run `mc admin trace -v -a <ALIAS>` and paste the output here? Let's stick to talking to one MinIO instance directly

**Comment by krainboltgreene** [comment]
I will do that immediately.

**Comment by krainboltgreene** [comment]
I'm closing this because after trying to trace it I'm no longer having an issue.

I believe firmly this means it's in the realm of my network layer and nothing to do with minio.
