### ISSUE TITLE
setBucketLifecycle send the wrong MD5

### ISSUE THREAD

**Issue by VoobanFTrepanier** [minio/minio-js#970]
This might be related to #964, I got similar issues when I try to use setBucketLifecycle as shown in minio's documentation : https://docs.min.io/docs/javascript-client-api-reference#setBucketLifecycle 

The error message that I got:
S3Error: The Content-Md5 you specified did not match what we received.

I had a quick check on the #968 fix and tried to apply it to LifeCycle's MD5, which actually fixed the issue. There might be a bigger issue with the MD5 generation for some methods.

My minio instance is running on Docker using image RELEASE.2020-06-18T02-23-35Z. At first I though I could have been the image's age that could be the issue, but the routes for Lifecycle seems to be in place properly using the MD5 generated by the strPayloadToMd5 method in fix #968.

**Comment by prakashsvmx** [comment]
I will test the fix in AWS environment once more .. and run functional tests.

**Comment by prakashsvmx** [comment]
This PR has been merged. Please upgrade to the latest.
