### ISSUE TITLE
InvalidEndpointError - in docker container

### ISSUE THREAD

**Issue by omondibrian** [minio/minio-js#977]
Hello, am having trouble running my app inside a container as I keep on having this error.  works outside my container though 

admin-service   | /Admin/app/node_modules/minio/dist/main/minio.js:103
admin-service   |       throw new errors.InvalidEndpointError(`Invalid endPoint : ${params.endPoint}`);
admin-service   |             ^
admin-service   | InvalidEndpointError: Invalid endPoint : '147.182.241.63'

**Comment by prakashsvmx** [comment]
please add more details about the setup . may be logs from containers as well.

**Comment by omondibrian** [comment]
fixed the issue my k8s cluster was adding new line characters  to the injected environment variables solved it by trimming and off any white space
