### ISSUE TITLE
getObject never calls end

### ISSUE THREAD

**Issue by michaelkruglos** [minio/minio-js#983]
I have a small file stored in minio bucket.
I use the code from the example at https://docs.min.io/docs/javascript-client-api-reference#getObject .
The on("end") doesn't seem to be called.
If I print the chunks, it prints the whole file over and over again.
The code I use is here: https://github.com/Soluto/tweek/blob/master/e2e/integration/utils/minio.js
And the file that was uploaded to the bucket is here: https://github.com/Soluto/tweek/blob/master/e2e/integration/spec/authoring-api/test-data/subject_extraction_rules.rego

**Comment by harshavardhana** [comment]
@michaelkruglos We will take a look.

**Comment by harshavardhana** [comment]
@michaelkruglos have you updated the dependency and tried with latest releases? 

https://github.com/Soluto/tweek/blob/master/e2e/integration/package.json#L31 - our latest release is v7.0.25

**Comment by michaelkruglos** [comment]
I tried with the latest version as well

**Comment by michaelkruglos** [comment]
I've found the problem. It's on my side. Sorry.
