### ISSUE TITLE
InvalidEndpointError: Invalid endPoint : undefined

### ISSUE THREAD

**Issue by jeffreyyi11** [minio/minio-js#984]
When trying to launch and test that I can connect I keep getting this error
event - compiled client and server successfully in 117 ms (203 modules)
wait  - compiling /_error (client and server)...
error - InvalidEndpointError: Invalid endPoint : undefined

**Comment by prakashsvmx** [comment]
Please add more details on how the client is. initialized?  
Any environment variables set ?

Which tests are being  run ?

**Comment by jeffreyyi11** [comment]
Client is being initialized with minio npm package using the example in the quickstart guide. 
Only env variables are the access key and secrete key.
Using the bucketExists function to see if I can connect to the minio server.
Bucket is present on the dashboard.

**Comment by prakashsvmx** [comment]
Please add some example/code to replicate the issue.

**Comment by jeffreyyi11** [comment]
const minioClient = new Minio.Client({
    endpoint: 'hoa-bc-fl.powerstonepm.com',
    port: 2082,
    accessKey: minio_access_key,
    secretKey: minio_secret
});

export default async(req, res) => {
    let data = req.body;
    console.log(data);
    try {
        minioClient.bucketExists(data, (err, exists) => {
            if(err) console.log(err);
            exists ? res.status(200).json('bucket exists') : res.status(200).json('no bucket found');
            console.log("🚀 ~ file: checkbucket.js ~ line 17 ~ minioClient.bucketExists ~ exists ", exists )
        })
    } catch (err) {
        console.log(err);
        res.status(500).json('error');
    }
}

**Comment by prakashsvmx** [comment]
The Object keys are case sensitive . 
`endPoint` would be the correct property. Please update the code. 

From the examples:
```javascript
var Minio = require('minio')

var minioClient = new Minio.Client({
    endPoint: 'play.min.io',
    port: 9000,
    useSSL: true,
    accessKey: 'Q3AM3UQ867SPQQA43P2F',
    secretKey: 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG'
});
````
