### ISSUE TITLE
copyObject encodes the slash / character needed by S3 

### ISSUE THREAD

**Issue by ariquinones** [minio/minio-js#985]
The current copyObject method encodes the object's full path including its forward slashes and therefore we get a 
headers['x-amz-copy-source'] = '%2Fname-of-bucket%2Ffile-to-copy.png' which throws an S3 400 error of InvalidArgument.

Should not encode the slashes of the path so the x-amz-copy-source header reads as '/name-of-bucket/file-to-copy.png'

**Comment by harshavardhana** [comment]
> Should not encode the slashes of the path so the x-amz-copy-source header reads as '/name-of-bucket/file-to-copy.png'

Yes they need to be path encoded not URL encoded - this our bug.
