### ISSUE TITLE
Question about special chars encoding

### ISSUE THREAD

**Issue by luigibalzano** [minio/minio-js#992]
Since 0.7.25 the listObjectsV2 function includes a call to a sanitizeObjectKey for each Contents (i.e. file).

https://github.com/minio/minio-js/blob/516f9336356d90a6a84dc41075b3457886c56633/src/main/xml-parsers.js#L398

The same does not happen for CommonPrefixes (i.e. folders), and this means that special chars are decoded only for files and not for folders.

Is this the expected behavior?

Examples:

The object with key:
61b6337e6ef31c002229a4f6/p%26g%27-_%7E%2C%3B%C3%A0%C3%B2%C3%B9%C3%A8%C3%A9%C3%AC%21%23%40%25%3D%C2%A3%E2%82%AC%C2%B0%C2%A7%26.jpg
Is returned as:
61b6337e6ef31c002229a4f6/p&g'-_~,;àòùèéì!#@%=£€°§&.jpg

The folder with prefix:
61b6337e6ef31c002229a4f6/Men%C3%B9/
Is returns as:
61b6337e6ef31c002229a4f6/Men%C3%B9/
Instead of:
61b6337e6ef31c002229a4f6/Menù/

**Comment by prakashsvmx** [comment]
@luigibalzano thank you for reporting.  :+1: 
Will investigate and send a fix.
