### ISSUE TITLE
`putObject` returns weird string but not an object `{ etag: 'xyz', versionId: null }`

### ISSUE THREAD

**Issue by LetsMelon** [minio/minio-js#995]
When I upload a small file ( <100MB) with `putObject` it returns something like `{ etag: '6cfd704e79b8ac04f6a0fb1f29f5e0e2', versionId: null }`, but when I try to upload a file with more than 200MB the same line returns only a number like this: `5f4b7382490c6471b3bdedad2f05d050-6`.

I can upload the same file via browser and Minio accepts the file. I'm not sure if this is even an error, but I have no idea why it returns something else.

That's my code:
```js
const out = await objectStorage.client.putObject(
      constants.objectStorage.bucket,
      `${id}/resource.zip`,
      file.data,
      { 'Content-Type': 'application/zip', 'Content-Length': file.size }
);
console.log(out);
```

**Comment by harshavardhana** [comment]
> 5f4b7382490c6471b3bdedad2f05d050-6

This is the ETag for the multipart object @LetsMelon - etag is not meant to be md5sum of the object always https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html 

### ETag

The entity tag represents a specific version of the object. The ETag reflects changes only to the contents of an object, not its metadata. The ETag may or may not be an MD5 digest of the object data. Whether or not it is depends on how the object was created and how it is encrypted as described below:

- Objects created through the AWS Management Console or by the PUT Object, POST Object, or Copy operation:

- Objects encrypted by SSE-S3 or plaintext have ETags that are an MD5 digest of their data.

- Objects encrypted by SSE-C or SSE-KMS have ETags that are not an MD5 digest of their object data.

- Objects created by either the Multipart Upload or Part Copy operation have ETags that are not MD5 digests, regardless of the method of encryption.
