### ISSUE TITLE
Generating presigned url with ACL

### ISSUE THREAD

**Issue by shahidcodes** [minio/minio-js#996]
Hi,

I am trying to generate a presigned url for the frontends to upload files. However I did not find in the docs how to create a url with ACL set to 'public-read'.

I tried passing through `reqParams` but it did not work.

```ts
const url = await this.s3.presignedUrl(
      'PUT',
      this.s3Config.defaultBucket,
      `${namespace}/${fileName}`,
      24 * 60 * 60,
      {
        'x-amz-acl': 'public-read',
        ACL: 'public-read',
      },
    );
```

I want to do something similiar like here https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_s3_presigned_post.html#generate-a-presigned-post but using minio sdk

I am using digitalocean spaces as my S3 provider.

**Comment by harshavardhana** [comment]
We do not really support ACLs on MinIO - and we discourage its usage. @shahidcodes - it is better to set read-only bucket policies on specific prefixes instead. 

Do this on DigitalOcean as well.

**Comment by shahidcodes** [comment]
Got it. What may be the reason to not use public-read ACL for file basis than the whole bucket?
