### ISSUE TITLE
presigned url size limit

### ISSUE THREAD

**Issue by PaPerM7** [minio/minio-js#997]
hello, is there a way to set a upload size limit for presigned urls that i'm generating?

**Comment by harshavardhana** [comment]
set the appropriate content-length as part of the presigned headers and you can restrict the size of the upload.

**Comment by PaPerM7** [comment]
can i do that when i'm generating the presigned url? is there some setting or options to set content-lentgh  or should i just add it manually?

**Comment by prakashsvmx** [comment]
https://raw.githubusercontent.com/minio/minio-js/9994dea80593456d4bc1a208611c351e0ca92d8e/examples/presigned-postpolicy.js

Please have a look at the example.
